### ISSUE TITLE
Create EBWiki Organizations

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1008]
I'm in the process of creating an EBWiki AWS [Organization](https://console.aws.amazon.com/organizations) so that we can work together and pool resources under the name.  Unfortunately, adding users is a manual, multi day process, and even after receiving the go ahead from AWS, I find myself still unable to add a user as of this morning
![screenshot 2017-09-04 at 9 57 50 am](https://user-images.githubusercontent.com/13509/30029651-0ca77e50-9158-11e7-8f66-f136e76e556b.png).

I've sent a response and we'll see how it goes.

**Comment by trystant** [comment]
I am waiting on contact from AWS in order to finish this job up. Once this is done, I will add the EBWiki org members.

**Comment by trystant** [comment]
I am going to expand upon this to deal with all the services for which we could/should be organized. Here is a list of services:
- [X]  Github
- [ ] Heroku
- [ ] AWS
- [ ] Rollbar
- [ ] New Relic
- [ ] @BOWiki/participants - If you can think of any other organizations that apply, please let me know.

**Comment by trystant** [comment]
Here is the update from Amazon re: organization setup.
```
Hi,

Thank you for getting back to us.

I am sorry to hear you still experiencing issues when trying to add accounts to your organization.

I've reached out to our Organization team to investigate this again. I'll hold onto your case and update as soon as I hear back from them.

Thank you for your patience.

Best regards,

Ngoni N.
```

**Comment by rlgreen91** [comment]
I just added Medium as a service that we'll use as an organization.  The assets I was using are on my Windows partition, so when I reset tonight I'll be able to add the publication.  I don't know that the credentials are listed on Trello.  @trystant can you invite me to that other board, so I can check and add them if need be?

Btw, I think it's really odd that I can just update your comment myself.

**Comment by rlgreen91** [comment]
Marked Medium as completed.  @trystant can't we mark Heroku as complete as well?

**Comment by trystant** [comment]
We can mark Heroku as complete. We can mark AWS because we're no going to use it, and I haven't addressed the others yet.

**Comment by rlgreen91** [comment]
@trystant at this point can we close this?

**Comment by trystant** [comment]
We're finished with this, as AWS organizations isn't a good fit for this open source priest as is.
