### ISSUE TITLE
Map info window overview shows HTML instead of plain text

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1027]
When you click on the location of a case on the map, the overview displays raw HTML as opposed to text.

A screenshot is below:
![screenshot 2017-09-19 at 10 34 49 am](https://user-images.githubusercontent.com/13509/30598214-322bbb66-9d27-11e7-801d-3a24f96c972c.png)

This should be plain text. The HTML is being saved from CK Editor.

**Comment by rlgreen91** [comment]
Actually @trystant can you expand on how exactly you cause the text to appear?  Because according to #912, a fix for this has already been merged into master.

**Comment by rlgreen91** [comment]
@trystant pinging again - can you recreate this?  Like I said, a fix for this was merged into master before.

**Comment by trystant** [comment]
Yup...

Go to https://ebwiki.org/cases/elijah-james-smith

Go to map of cases at bottom of article.

Click on one of the cases.

See: 
![screenshot 2018-04-23 at 15 08 08](https://user-images.githubusercontent.com/13509/39147668-47c22dda-4708-11e8-89dc-94b3d96b0f3e.png)

**Comment by rlgreen91** [comment]
@trystant to be clear, we want the HTML to be rendered properly here, right?  Like links show up properly?

Or do we want it to be just plain text, with no styling?

**Comment by rlgreen91** [comment]
@trystant Pinging again

**Comment by trystant** [comment]
We want plain text, I believe

**Comment by rlgreen91** [comment]
Ok.  This is coming from the overview, correct?  Shouldn't we enforce a character limit then, as well as tell them that it will be displayed in plain text?

**Comment by rlgreen91** [comment]
To provide more context - it looks like on the view, we already truncate the overview to 500 characters in the display.  I see no reason not to enforce that at the model level and require users to enter overviews that are 500 characters or less to begin with.  This will be two PRs - one that fixes the HTML, then another that adds the requirement for 500 characters.

**Comment by rlgreen91** [comment]
@trystant Wait, why do we allow the overview to be nil?  If that's what pops up in the marker, then shouldn't that always have a non-nil value?

**Comment by rlgreen91** [comment]
This has been addressed in #1593 and other PRs that fixed the corresponding rake task (#1627, #1629, #1623)
