### ISSUE TITLE
An editor can create multiple cases with the same name

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#104]
While updating the [Mansur Ball-Bey](http://ebwiki.org/articles/mansur-ball-bey) case, I added one for "Kajieme Powell". Somewhere along the line, two cases were created instead of one. One is [here](http://ebwiki.org/articles/376), while another is [here](http://ebwiki.org/articles/kajieme-powell).

Here's a screenshot
<img width="1280" alt="two_cases" src="https://cloud.githubusercontent.com/assets/13509/9424125/7abf0ab0-48ae-11e5-8fb0-573a8e2d8fac.png">

We need to ensure that one case is created and shown for each subject. Ideally, we should make it so we cannot have two cases on the same person.

**Comment by campgurus** [comment]
we need to have info so we can replicate this error.

**Comment by campgurus** [comment]
Just to clarify, you created a case for K Powell and it turns out we already had one. So we need to add validation for uniqueness of subject name and maybe other characteristics as well.

**Comment by trystant** [comment]
I'm changing the title of this issue from "Duplicate Cases created while editing one" to "A user can create multiple cases with the same name"

The larger issue is that a user can create multiple cases with the same name. Ideally, we want there to be one case per name and location, at least initially. 

How do we resolve this? The first stage is to have a validation upon user name and city. That should (hopefully) be enough of a unique identifier. We may need to get more specific as the cases mount.

Side note; down the road it may be good for individual users to have their own cases where they can collect their own version of the facts and compare to each other. I could see that being engaging.

This needs more discussion for the long term and a validation for the short term

**Comment by campgurus** [comment]
I just separated out the individual versions idea into it's own issue. In the meantime, what do we want to validate uniqueness of?  name/city or subject.name/city?

**Comment by StlMaris123** [comment]
@campgurus , what are the odds of people sharing a name from the same city?

**Comment by trystant** [comment]
I'm going to retire this for now, since this has not had a large presence in the data that has occurred and can be resolved with greater user involvement
