### ISSUE TITLE
Longer Term Ideas List

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#105]
### This is a place to store "blue sky ideas" that can help EBW be a remarkable tool for providing information about cases of violence against people of color.
- Personalized Case Versions -- Allow individual users to have their own cases where they can collect their own version of the facts and compare to each other.

**Comment by trystant** [comment]
There are ways we can encourage people to act that could be helpful. Those include:
* Showing people how to create a kickstarter or gofundme to help with legal costs for the family of someone who has been shot by police, or arrested unfairly.

**Comment by campgurus** [comment]
Agree with @trystant, fundraising for families to offset costs relating to the case, or some less so.  A family that has lost a primary breadwinner and has not yet received any settlement may be able to garner some aid for living expenses during the transition.

**Comment by campgurus** [comment]
I think in general terms, the way we can engage users is to let them build personalized content on the site.  One way is to let them customize how they see the content we are creating, for example, allowing their user profile pages to show the latest updates in the cases they are following on one page. Other ideas that give users something to come back to EBW for updates include:
* Circulating petitions (users return to see # of signatures they have received)
* creating/collecting participants for a "write your Congressman" campaign (users see # of people copying their email content)
* sharing whistleblower documents (users see # of people viewing their docs/videos)

I am trying to think of other ways to pull people in and get them engaged. Like Slack, as @trystant  and I were discussing, makes it very easy to begin and pretty soon, you have created something of value to yourself, that keeps you using it. MailChimp is another example.

**Comment by trystant** [comment]
@campgurus I think that we don't need to create content, just be a guide that shows people how to use what is already out there effectively.

I don't think that EBWiki needs to be circulating petitions, collecting emails for a campaign until it's found that there is something notably missing from those tools as applies to Black people killed by law enforcement.

I think we only create when what is out there isn't sufficient or effective.

**Comment by campgurus** [comment]
All your points are valid.  But, I think all of these things are well down the road. In that time, the places where we can fill voids will become apparent.  The best ones will likely be voiced to us directly by users/stakeholders. 

At this point, with go/no-go decisions far in the future, I wouldn't look askance at any ideas.  The goal of this thread is for freely brainstorming the largest possible pool of ideas that we can winnow down when they become closer to reality.

**Comment by trystant** [comment]
You're right about that.

**Comment by rlgreen91** [comment]
I'm going to start tackling these in Slack since that's a better place to do this type of brainstorming I think.

**Comment by campgurus** [comment]
makes sense
