### ISSUE TITLE
Complete Cloud9 installation/setup guide

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1052]
Complete the requested changes to the Cloud9 installation/setup guide.  Once done, create a copy in the docs folder and add a link to the README.

**Comment by rlgreen91** [comment]
@trystant is this even a thing anymore?

**Comment by trystant** [comment]
There is an AWS version of this that i use. I can  update these docs to reflect that

**Comment by trystant** [comment]
I've actually already updated the docs to reflect the AWS Cloud9 environment. I can close this.
