### ISSUE TITLE
Make EBWiki pass Ruby Style guide using rubocop

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1054]
Right now EBWiki does not fare well with the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide). This can be fixed using [Rubocop](https://github.com/bbatsov/rubocop).

 This is considered fixed when there are no `Rubocop` errors and rubocop is added to the `rake spec` task.

**Comment by trystant** [comment]
The initial `rubocop` run returned `233 files inspected, 3379 offenses detected`.

Initial work on the `db/seeds.rb` file has resulted in `233 files inspected, 2807 offenses detected`

**Comment by trystant** [comment]
After squashing the migrations with [squasher](https://github.com/jalkoby/squasher), and the current status is `164 files inspected, 1957 offenses detected`

**Comment by trystant** [comment]
Current tally after `rake rubocop_autocorrect` is `160 files inspected, 173 offenses detected`

**Comment by rlgreen91** [comment]
We should integrate Rubocop into our CI tests using the Pronto gem, found here: https://github.com/prontolabs/pronto

**Comment by StlMaris123** [comment]
I could help with some of the issues

**Comment by rlgreen91** [comment]
Actually, we've incorporated this and other checks in CodeClimate, so this can be closed.  If you're looking for something to do @StlMaris123 try #1572.
