### ISSUE TITLE
Create rake task test helper

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1071]
Create a helper to easily test rake tasks.  Follow the example code listed [here](https://www.wetestrails.com/blog/test-rails-rake-tasks-with-rspec).

**Comment by kcutler** [comment]
Hi, I would like to work on this for hacktoberfest. I am setting up the environment locally but I am running into an error. Is there anyone I can direct my question to?

**Comment by rlgreen91** [comment]
@kcutler What error are you running into?  Please post the full stack trace.

**Comment by kcutler** [comment]
Here is [link](https://docs.google.com/document/d/1ElHdacNcaW65DPTEy9Io8nRV8WIKSMVm6-It0tC0mGk/edit?usp=sharing) where I've written up the errors and the steps I've taken before now.

**Comment by rlgreen91** [comment]
@kcutler In the future, please enter any comments and copy paste the full stack trace directly into a comment on Github.  I cannot read anything in the attached picture, so please repost the stack trace. At this point, my best guess is that when you created the user in Postgres, you either did not assign a password to it or used a different one.

We currently are using Postgres 9.4, but as far as I know there aren't any major changes in how authentication is handled.  We can keep that as a last resort if we need to.

**Comment by trystant** [comment]
For some additional information, we have some documentation on [How to share an issue with another developer](https://github.com/EBWiki/EBWiki/wiki/HOWTO:-Share-an-Issue-with-another-Developer).  It may be helpful in sorting out any issues @kcutler may have while working on this issue.

**Comment by rlgreen91** [comment]
Hmm, so that link has disappeared.  While we do need some type of helper/shared context in order to load everything correctly, it's hard to understand creating that separately from the specs themselves for individual tasks.  I'm going to close this and instead open issues about testing our rake tasks.
