### ISSUE TITLE
Content suddenly centered on the page

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1073]
on both show and edit views. see image:
<img width="964" alt="screen shot 2017-10-23 at 7 37 03 am" src="https://user-images.githubusercontent.com/1260659/31887140-2d476e5c-b7c5-11e7-915f-62994a20dd72.png">

**Comment by rlgreen91** [comment]
Hmm, do you remember what were you doing before that?  

I checked just now and the text is aligned properly.  Is it possible you were resizing the window?  If so, it's possible that the styling didn't update correctly as the window size changed.

**Comment by rlgreen91** [comment]
Given that we've never heard about this again, I'm going to close this.
