### ISSUE TITLE
API error: Invalid format. data.person.id is missing and it is required.

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1075]
View details in Rollbar: [https://rollbar.com/trystant/EBWiki/items/800/](https://rollbar.com/trystant/EBWiki/items/800/)

```
API error: Invalid format. data.person.id is missing and it is required.
```

**Comment by rlgreen91** [comment]
Do we know what triggered the error?  Was it development or production?

**Comment by trystant** [comment]
We do not. It hasn't occurred in over 208 days though. I'm good to close this.
