### ISSUE TITLE
Comments on case UI Issues

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#108]
Comments as currently implemented have several issues.
<img width="1280" alt="screenshot 2015-08-22 13 27 39" src="https://cloud.githubusercontent.com/assets/13509/9425146/95c65b86-48d3-11e5-8fa1-61db7e0c6827.png">

My initial issues are as follows:
- Including a link with the comment looks ungainly in its current form. It would be good to have a link shortener automatically make the links shorter.
- Can people enter HTML in comments, or not?
- Should we give people time to be able to modify comments or not?
- The placement of the comments does not lend themselves to promoting long conversations.

Perhaps we should look at implementing a comment system like [LiveFyre](http://web.livefyre.com/comments/) instead of building our own?

**Comment by campgurus** [comment]
Here is the gem for LiveFyre integration:  https://github.com/mashable/livefyre
Disqus is another: https://github.com/sandric/disqus_rails

Not sure we want to outsource this.  We should think about what we want/need from comments. I think our needs are different from most blogs or other sites.

**Comment by rlgreen91** [comment]
Ok, so I'm coming back around to this: I agree with your initial issues @trystant.  I think before we talk about addressing these issues though, we should probably stop to think about what the point of comments should be with regard to cases.   I'll add that to the agenda.

**Comment by trystant** [comment]
I think we need to review how comments have been used and see how best to proceed if it's worth it.

**Comment by rlgreen91** [comment]
Let's come back to this.  We had a discussion in June 2019 on Slack where we all agreed to keep comments but it seems like we still have questions about where and how we want to use them.  

I guess the first question is: do we still want the comments to be under the user image on the side?  Or should they go somewhere else @trystant @campgurus

**Comment by mnyon-grandkru** [comment]
I think that with the current focus on upgrading, it makes sense to have an consensus on what we want to do with this before proceeding. That could be a description here or an A.D.R., but this should be closed now.
