### ISSUE TITLE
Address data type linked to articles exclusively.

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#109]
Currently, EBWiki has the address characteristics as properties of the article. 

<img width="1280" alt="screenshot 2015-08-22 14 49 08" src="https://cloud.githubusercontent.com/assets/13509/9425543/e55c49a4-48e1-11e5-8793-f81ebb80df67.png">
In fact, there are multiple models that could have an address, including Officers and Agencies. There's a [Railscast](http://railscasts.com/episodes/273-geocoder?view=asciicast) about using a separate Location object with polymorphic associations. This is how it should be done in EBWiki.

In particular, this means that the existing cases will need to have the address data migrated out of the "articles" model and into a separate "Address" or "Location" model, which will be associated with a "Case".

**Comment by campgurus** [comment]
Smart idea!

**Comment by rlgreen91** [comment]
Hey, coming back to this:  ok, so now we would be up to three models: cases, agencies, and events.  Do we think it still makes sense to handle this using polymorphism, or would single-table inheritance make more sense?  @trystant @campgurus let me know what you think.

**Comment by trystant** [comment]
@rlgreen91 I always thought that polymorphism was the better solution for addresses, but that's me.

**Comment by rlgreen91** [comment]
@trystant coming back to this again - does it make sense to have the address be a polymorphic model?  Or wouldn't it be better to create an address as a value object and then geocode the model instances that use the address?

**Comment by trystant** [comment]
@rlgreen91 It may not make sense to have a separate address table,  but it may make sense to have the addresses formatted with a library and then have a string representation stored in the db. As is, I don't think that there's a high priority on this.

**Comment by mnyon-grandkru** [comment]
This is a refactoring exercise, and can be closed for now.
