### ISSUE TITLE
Highlight content on the landing page.

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1096]
On the landing page, bold the number in the headline, i.e. "These XXX people..."

Related to Issue #845

**Comment by campgurus** [comment]
here is a screenshot of the current styling of the metric on the home page:

<img width="781" alt="screen shot 2018-01-07 at 7 13 45 am" src="https://user-images.githubusercontent.com/1260659/34649295-66658ebc-f37a-11e7-8358-3ea90c5089ce.png">

**Comment by rlgreen91** [comment]
I think this image is supposed to be in the PR.  I'll give my thoughts there.

**Comment by rlgreen91** [comment]
Now, to complete this issue, you need to change the number to be the orange used throughout the site.  You don't have to make it bold, just change the color.

**Comment by rlgreen91** [comment]
Addressed in #3255
