### ISSUE TITLE
Set up Google Analytics

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1097]
Set up Google Analytics.  Completion of this issue will include: 

- Creating a Google Analytics account for the website
- Inserting the Google Analytics tracking ID within `application.html.erb`

This is related to issue #845

**Comment by campgurus** [comment]
We actually have Google Analytics and a tracking code currently included in application.html.erb.  It is accessible via the blackopswiki1@gmail.com account.  I am trying see how to add change the manager, but I may not have admin access.  

We could start anew with a different account and tracking code. we would lose the data we have gathered so far, which we might decide is not that important.

**Comment by campgurus** [comment]
I am in the process of trying to regain admin access to the analytics account so that I can add users etc.

**Comment by trystant** [comment]
This is the GA account attached to `blackopswiki@gmail.com`? Could we transfer that to `ebwiki@gmail.com`?

**Comment by rlgreen91** [comment]
I say let's recover it if possible.

**Comment by campgurus** [comment]
If I can get admin access, I will transfer to the correct email.

**Comment by trystant** [comment]
@campgurus @rlgreen91 I believe we currently do have access, do we not?

**Comment by rlgreen91** [comment]
I think we do?  That's a question for @campgurus

**Comment by trystant** [comment]
@campgurus you definitely have admin access, and who are all these other people?

![screenshot 2018-05-21 at 09 24 58](https://user-images.githubusercontent.com/13509/40309878-11cb6eb2-5cd9-11e8-8532-61f00908e891.png)

**Comment by trystant** [comment]
I'm trying to change the email (I changed the **blackopswiki** to **ebwiki** name), but Google's saying that `ebwiki@gmail.com` and `ebwiki1@gmail.com` are invalid.  @rlgreen91 @campgurus, which address should I use? 

Also, 
![screenshot 2018-05-21 at 09 30 04](https://user-images.githubusercontent.com/13509/40310055-948fcca8-5cd9-11e8-99fa-fb64182743b2.png)

**Comment by rlgreen91** [comment]
I'm not sure, I don't know that we've ever used a variation of `ebwiki@gmail.com`

**Comment by rlgreen91** [comment]
@campgurus @trystant You know, after all of this, I'm actually wondering - do we really need both Google Analytics and Ahoy?

**Comment by trystant** [comment]
I'm going to close this because we have GA up and running.
