### ISSUE TITLE
Refactor logic in new action conversations controller 

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1112]
In `app/controllers/conversations_controller.rb`, refactor the `new` method.  Specifically, when returning the variable @other_users, only return the id and name of all users other than the current signed-in user.  This will probably end up looking like this:

`@other_users = User.where.not(id: current_user.id).pluck(:id, :name)`

Regardless of the final change, this should also trigger a change to `app/views/conversations/_form.html.erb`.

**Comment by rlgreen91** [comment]
Or feel free to use something like `reject`. Whatever you'd prefer, really.

**Comment by StlMaris123** [comment]
Hello @rlgreen91 I would love to work on this issue

**Comment by rlgreen91** [comment]
Ok, you'll need to assign it to yourself.

**Comment by rlgreen91** [comment]
Merged as part of #1356
