### ISSUE TITLE
Ticker feature bump

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1118]
Bumping this from #246 for when we get to the point of adding features. Our front page list of recently updated cases is an attempt at engagement that aims to give users some sense of what cases have new developments.

However, In addition to breaking down issue 246 into more discrete elements, a ticker could take our "recently updated" list to a higher level by: 

* including some of the substance of the update; and
* providing a UI element that would be present on the case/show pages where most users are

**Comment by rlgreen91** [comment]
To be honest, I'm not sure if I'm a fan of adding this...or news tickers in general.  They just seem so distracting.

**Comment by campgurus** [comment]
closing this
