### ISSUE TITLE
Show page buttons misaligned

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1120]
beneath the photo, there are social share icons and three buttons. the icons look like they have spread out somehow.  likewise, the buttons are now also taking up the full width of the div and pressing against the content sections awkwardly. Screesnshot below:

<img width="375" alt="screen shot 2017-11-28 at 6 08 04 pm" src="https://user-images.githubusercontent.com/1260659/33349347-a7988826-d467-11e7-8acf-4da3d015538b.png">

**Comment by rlgreen91** [comment]
Hmm, this is probably better addressed as an extension of issue #962 - this should all be in an aside element, which should fix the styling (or make it easier for you to do so).

**Comment by ArushiSinghal** [comment]
Hello @rlgreen91 
https://github.com/EBWiki/EBWiki/blob/bb9f489e491f2024d2685a82d29f3486ec83ab05/app/assets/stylesheets/articles.scss#L78-L80
@simransinghal and I tried to fix this issue and found that width defines in this class is overwritten by the width:100%.
The reason is that it is overwritten by the bootstrap class.
So we are thinking of changing the line
https://github.com/EBWiki/EBWiki/blob/bb9f489e491f2024d2685a82d29f3486ec83ab05/app/views/articles/_button_group.html.erb#L1
to 
```<div class = "btn-group btn-group-justified" style="width:calc(100% - 30px)">``` .
Any suggestion from your side is very helpful or should we go ahead with this change.

**Comment by simransinghal** [comment]
Me and @ArushiSinghal will like to propose a solution for this. This issue can be resolved by using "!important".
That is by changing the code to:-
```
.btn-group-justified { 
     width: calc(100% - 30px) !important; 
     margin: 15px 0 15px 15px; 
} 
```
But, as using !important is not a good style. So, we will like to take others opinion before submitting PR.
cc @campgurus @rlgreen91

**Comment by rlgreen91** [comment]
Hmm, I'd rather you not use `!important`.  I mentioned above that I would like for you to update the HTML to contain all of this in an `aside` element.  That might make it easier to style some of this.  

I'm not a huge fan of defining the style in HTML div tags like that. I'd much rather keep it in CSS files.  We're using Bootstrap, so let's dig a bit more into how `.btn-group-justified` works - if you look at the second answer to [this SO question](https://stackoverflow.com/questions/14205125/set-a-button-groups-width-to-100-and-make-buttons-equal-width), you'll see that Bootstrap handles this class based on whether the containing elements are `<a>` or `<button>`.  Following the link to their [documentation](https://getbootstrap.com/docs/3.3/components/#btn-groups), we see that we can add `role=group` to the div tag to help align things properly - it seems to be missing.  Does that make sense?

If you could also get rid of the spaces in `class = .btn-group .btn-group-justified`, that would be great.  And in the future, you don't have to post your solution here in the issue - if you have questions like you did here, that's fine.  But, if you have a good idea of what your solution should be, feel free to just go ahead and submit a PR - you don't have to wait for our approval.
