### ISSUE TITLE
Follower email not received for updated case

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1121]
I am currently following this case: https://ebwiki.org/articles/freddie-gray

The case was updated yesterday, but i did not receive an email update.

Our current tests verify that the mailer view renders appropriately, but we do not currently test that mailers are actually sent.

This looks like a tutorial on how to test that an email was sent: http://vicfriedman.github.io/blog/2013/08/05/how-to-write-rspec-mailer-tests/

It is from 2013, so it may be dated.

**Comment by rlgreen91** [comment]
I do believe that we should update the tests to include a unit test for this.  However, currently we do have some logging to indicate when we send emails out.  Have you checked the logs on production to see if it reached that point at least?  Right now it could be either your email provider or the site that's causing the issue.

**Comment by campgurus** [comment]
i only know how to check logs right away, e.g. `heroku logs -t -a ebwiki`.  how do I check the logs for 3 days ago?

In terms of where the issue is, neither @trystant or I received the update and both of us are followers. My email provider is gmail, so I suspect the problem is with ebwiki.

**Comment by rlgreen91** [comment]
Ah, in that case you would use `grep` to search for logs with a timestamp for that day.  Google will give you a more precise answer on what to run than I will, but it'll be something like `heroku logs ebwiki | grep timestamp` or something like that.

**Comment by trystant** [comment]
@rlgreen91 @campgurus What additional testing do we need for this ticket?  SMTP can fail for reasons outside the scope of this ticket

**Comment by rlgreen91** [comment]
Yeah, I think we can close this.
