### ISSUE TITLE
Change article to case: Update copy on site to use "case"

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1141]
This is a sub task of #825 concerning the plain text copy on the site. This only concerns the copy in the view templates that aren't in the HTML attributes or Ruby code.

**Comment by rlgreen91** [comment]
I feel like this has already been done.

**Comment by trystant** [comment]
There are three places where `article` is still being used...in the update message. I have a commit with info.

**Comment by trystant** [comment]
This has been pushed to production
