### ISSUE TITLE
Convert Article to case in the data model

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1142]
As a subtask of #825, this includes changing all occurrences of `article_*` to `case_*` in the schema. Writing & executing the migrations to make the changes and model methods as needed.

**Comment by rlgreen91** [comment]
Are you planning to split this into two parts, first the migrations and second the code itself?

**Comment by trystant** [comment]
I hadn't planned on doing first the migrations, then the code. I'd actually been planning on doing different constants in the codebase before switching the schema table attributes.

**Comment by rlgreen91** [comment]
What, so something like: `CASE = Article` throughout, then updating the method names, followed by the attributes?  I'm not quite following what you mean.
