### ISSUE TITLE
Change Article to Case: Rename Article model & spec

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1145]
This is a subtask of #825; renaming the models, views and controllers in the codebase.

**Comment by trystant** [comment]
A lot of the work has been done, but there's been a challenge adjusting the staging/production databases. When `8f26c5f` was posted to staging, it resulted in a huge issue on that host. The next step is to copy the staging database over to development and run a series of migrations in order to match the model/controller & spec modifications.

**Comment by rlgreen91** [comment]
Hmm, are you not able to temporarily suspend the automatic push to staging, and then manually update the branch there and run the migrations?

**Comment by trystant** [comment]
I think I need to revamp this from the beginning. This branch is old enough to be really out of sync.

**Comment by trystant** [comment]
I'm running into this issue running a db:migrate on the dev database. 

```
[1] pry(#<InitSchema>)> index_exists? :articles, :slug, name: 'index_articles_on_slug' 
-- index_exists?(:articles, :slug, {:name=>"index_articles_on_slug"})
   -> 0.0027s
=> false
[2] pry(#<InitSchema>)> add_index 'articles', ['slug'], name: 'index_articles_on_slug', unique: true, using: :btree 
-- add_index("articles", ["slug"], {:name=>"index_articles_on_slug", :unique=>true, :using=>:btree})
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "index_articles_on_slug" already exists
: CREATE UNIQUE INDEX  "index_articles_on_slug" ON "articles" USING btree ("slug")
from /usr/local/rvm/gems/ruby-2.4.1@ebwiki/gems/activerecord-4.2.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
```

I am going to drop the db & restart.

**Comment by trystant** [comment]
I've got 61 errors to fix on this go 'round:

```
Finished in 37.93 seconds (files took 7.8 seconds to load)
163 examples, 61 failures
```

**Comment by rlgreen91** [comment]
Now how many failures?

**Comment by trystant** [comment]
From [Travis](https://travis-ci.org/EBWiki/EBWiki/builds/346912840)
```
Finished in 1 minute 14.12 seconds (files took 12.32 seconds to load)
165 examples, 8 failures
```

So, closer.

After the data model work is done, I will need to write some data migration code.

**Comment by trystant** [comment]
@dgoore @rlgreen91 
So, some of the remaining spec failures are related to analytics, which have very few specs over that part of the codebase. The lack of specs means that I'll need to add specs in order to feel comfortable/confident that these changes will have unexpected side effects.

**Comment by trystant** [comment]
Also @rlgreen91; 

I'm trying to resolve this spec failure:
```
 1) DetermineVisitsToCases returns visits to cases
     Failure/Error: expect(cases).to eq([cases, 3])
     
       expected: [[[#<Case id: 1, title: "1Title", created_at: "2018-02-28 08:47:49", updated_at: "2018-02-28 08:47:49...ve_avatar: nil, summary: "A summary of changes", follows_count: 0, default_avatar_url: nil>, 3]], 3]
            got: [[#<Case id: 1, title: "1Title", created_at: "2018-02-28 08:47:49", updated_at: "2018-02-28 08:47:49"...remove_avatar: nil, summary: "A summary of changes", follows_count: 0, default_avatar_url: nil>, 3]]
     
       (compared using ==)
     # ./spec/services/determine_visits_to_cases_spec.rb:12:in `block (2 levels) in <top (required)>'

Finished in 0.58561 seconds (files took 11.98 seconds to load)
1 example, 1 failure
```

I don't know why there's a level of bracketing in the results. Could you advise?

**Comment by trystant** [comment]
Yay! Specs are green which is a step forward.

The next step is to transfer data from the existing article containing database to the case containing database.  This will be in the form of a rake task. 

But wait...whither codeclimate results?

**Comment by trystant** [comment]
I think that it's safe to close this issue at this point. If there are smaller bugs that pop up, they can be reference separately.
