### ISSUE TITLE
The User pages have multiple UI issues

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#116]
@campgurus 
These are visible on the [User](http://ebwiki.org/users/mark) page and the [Update User](http://ebwiki.org/users/mark/edit) page. Substitute your username in order to see the pages.

User Page:
<img width="1280" alt="screenshot 2015-08-23 07 23 11" src="https://cloud.githubusercontent.com/assets/13509/9428007/e1375e32-4967-11e5-8039-b234859c29d6.png">

Update User Page:
<img width="1280" alt="screenshot 2015-08-23 07 17 08" src="https://cloud.githubusercontent.com/assets/13509/9428010/ee8cae5c-4967-11e5-8048-a1cd7a5bcb8a.png">

Issues are as follows:
- [x]  The "Update Profile" page has an "Edit Article" header at the top.
- [x]  If the user has already selected an avatar, that isn't shown on the "Update Profiles" page. Instead I see a dropdown with "No file chosen", which isn't accurate.
- [x]  The link to "Update Profile" says "Update Details". Changing that to "Update Profile" would match the language in the dropdown 
- [x] The cases followed image matches the old look and feel. Each followed case should have the "Orange is the New Black" UI from the home page
- [x] If the user hasn't entered a bio, there is a bit blue empty box with "<Username>'s Bio" on the Profile Page
- [x] On the "Update Profile" page, the "Bio" header is actually text that would be better server on a tooltip, "Write a few words to tell folks who you are and why you are here."
- [x] The checkbox on the profile page does not accurately reflect whether you are subscribed to the newsletter. This is a big enough deal to merit its own issue in addition to these. This is in issue #117

**Comment by campgurus** [comment]
"The cases followed image matches the old look and feel. Each followed case should have the "Orange is the New Black" UI from the home page"

The images in the new look on the index page are larger and can accommodate text within the image.  do we want to make the images on this page bigger as well?

**Comment by trystant** [comment]
I think that it should match wherever displays like this exist on the site.

On Tue, Sep 1, 2015 at 12:35 PM, campgurus <notifications@github.com> wrote:

> "The cases followed image matches the old look and feel. Each followed
> case should have the "Orange is the New Black" UI from the home page"
>
> The images in the new look on the index page are larger and can
> accommodate text within the image. do we want to make the images on this
> page bigger as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BOWiki/BOW/issues/116#issuecomment-136783709>.
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by campgurus** [comment]
Working on these issues, see the ones checked above.  I will go back to the other two I still have, but wanted to post this question I am running into on checking to see if a user is already subscribed to the list, so we can have the user profile accurately reflect the subscription status.

the documentation for the Gibbon gem suggests that the following will retrieve a list of subscribers to a list with id "list_id":

`gibbon.lists(list_id).members.retrieve`

But I am getting a no method error. here is what I do in console:

```` ~/development/blackops$ heroku run rails c -a blackopswiki
Running `rails c` attached to terminal... up, run.9562
Loading production environment (Rails 4.2.3)
irb(main):001:0> gibbon = Gibbon::API.new
=> #<Gibbon::API:0x007f9095b21128 @api_key="3d0b601bd3197356fdc8088cce0a7be9-us11", @api_endpoint=nil, @timeout=15, @throws_exceptions=false, @default_params={:apikey=>"3d0b601bd3197356fdc8088cce0a7be9-us11"}>

````irb(main):012:0>  gibbon.lists(ENV['MAILCHIMP_LIST_ID']).members.class
=> Hash
irb(main):013:0>  gibbon.lists(ENV['MAILCHIMP_LIST_ID']).members.retrieve
NoMethodError: undefined method `retrieve' for #<Hash:0x007f9095efdf30>
	from (irb):13
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:8:in `require'
	from /app/bin/rails:8:in `<main>'
irb(main):014:0> ````

**Comment by trystant** [comment]
Are we running the latest version of Gibbon? That could be a reason.




On Tue, Sep 1, 2015 at 2:00 PM, campgurus <notifications@github.com> wrote:

> Working on these issues, see the ones checked above. I will go back to the
> other two I still have, but wanted to post this question I am running into
> on checking to see if a user is already subscribed to the list, so we can
> have the user profile accurately reflect the subscription status.
>
> the documentation for the Gibbon gem suggests that the following will
> retrieve a list of subscribers to a list with id "list_id":
>
> gibbon.lists(list_id).members.retrieve
>
> But I am getting a no method error. here is what I do in console:
>
> ```~/development/blackops$ heroku run rails c -a blackopswiki
> Runningrails c` attached to terminal... up, run.9562
> Loading production environment (Rails 4.2.3)
> irb(main):001:0> gibbon = Gibbon::API.new
> => #"3d0b601bd3197356fdc8088cce0a7be9-us11"}>
>
> irb(main):012:0> gibbon.lists(ENV['MAILCHIMP_LIST_ID']).members.class
> => Hash
> irb(main):013:0> gibbon.lists(ENV['MAILCHIMP_LIST_ID']).members.retrieve
> NoMethodError: undefined method `retrieve' for #<Hash:0x007f9095efdf30>
> from (irb):13
> from
> /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in
> `start'
> from
> /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in
> `start'
> from
> /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in
> `console'
> from
> /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in
> `run_command!'
> from
> /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in
> `<top (required)>'
> from /app/bin/rails:8:in `require'
> from /app/bin/rails:8:in `<main>'
> irb(main):014:0>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BOWiki/BOW/issues/116#issuecomment-136813161>.
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by campgurus** [comment]
I assume so. I don't think we specify a version.

**Comment by trystant** [comment]
Well, our [Gemfile.lock](https://github.com/BOWiki/BOW/blob/master/Gemfile.lock) has [gibbon](https://github.com/amro/gibbon/releases) at 1.2.0. It looks like there's 1.2.1 and 2.0.0 out. The documentation from the Gibbon [README](https://github.com/amro/gibbon/blob/master/README.markdown) says:

"Gibbon now targets MailChimp API 3.0, which is substantially different from the previous API. Please use Gibbon 1.1.x if you need to use API 2.0."

It looks like 1.2.0 uses the MailChimp 2.0 API and 2.0.0 uses the 3.0 version of the API. I'd either find a way to do that command in 2.0, or upgrade Gibbon and use the 3.0 syntax. The only challenge with that is making sure you find and change the other Gibbon calls in the source code.

That's why you can't find that method, methinks.

**Comment by campgurus** [comment]
makes sense.  I would say we need to figure out what version of MailChimp we are using, but I would think we upgrade everything to the latest version, no?

**Comment by trystant** [comment]
As long as the upgrade doesn't cause problems,  sure.

We should check that though.

**Comment by campgurus** [comment]
OK.  We have upgraded MailCimp and also are able to find subscribers by email address with all fixes housed in the `profile_page_fixes` branch. Now I am thinking of the logistics question figuring out exactly how this user flow should work. For example, right now, a user can sign up for the newsletter in two ways:
* User can check the box on creating or updating the box to edit the :subscribed? attribute
* User can click the front page sign up button to go directly to the MailChimp Form

Regardless of how the user gets on the list, their status (subscribed/pending/not-involved) should be reflected in their profile on the site. Likewise, a subscribed person should be able to unsubscribe from their edit_profile page.

here are the possible scenarios:

1. User subscribes with the check box to sign up and confirms via email -- MC and EBW are in sync
2. User subscribes with the check bos -- does not confirm -- user is "pending" on MC, subscribed on EBW
3. User subscribes via the MC link and confirms via email -- user is "subscribed" on MC, not on EBW
4. User subscribes via the MC link and does not confirm -- user is "pending" on MC nothing on EBW

Scenario number 1 is not a problem.

In the other scenarios, we need for the EBW status to match whatever is on MC. In Scenario 2, what should the user profile show?  My current thinking is that the the subscribed? attribute should remain 'true' in these cases, but we should add a note to let the user know that the confirmation step remains. IN this case, we need to let them know how to regenerate the subscription if they have lost the email.

In Scenario 3, we should just match the EBW status and make user.subscribed = true
In Scenario 4, we should also match the subscribed attribute and treat them the same as Scenario 2

I am thinking out loud here, but let me know if this doesn't make sense.

**Comment by campgurus** [comment]
Having solved the code issues above, I am now working on the logic of synchronizing our db with what is on MC.  Specifically, how do we unsubscribe a user without unsubscribing users who have signed up directly on MC. To review our process, the user model has a boolean attribute which indicates whether he/she has indicated they want to receive the newsletter. so:
* By default, unsubscribed user status in MC is nil
* User checks a box to receive newsletter either during signup or in editing profile
* User is now listed in MC as 'pending'
* User receives email confirmation
* User clicks confirm link in email, can redirect to EBW root or MC settings
* User status in MC is now 'subscribed'

Here is how unsubscribing should work:
* User visits edit profile page
* User unchecks subscription box
* User clicks 'update' button
* If subscribe box is unchecked on update, EBW will unsubscribe the user from the list
* User has status on MC of 'unsubscribed'

This works to sync these lists by matching what is in MC to reflect what we have in the EBW db. That would have worked fine, except for our use of the direct to mailchimp form, which doesn't require a checkbox. So the question is what happens when a user comes to the edit form after signing up on MC directly.  With the description above, a user who signs up via MC will still be listed on EBW as user.subscribed=false.  If the user does not check the box, the user will be unsubscribed upon hitting the 'update' button.

So @user.subscribed must be true for MC subscribers by the time they arrive at the edit page.  A controller action edit may be appropriate. I will try that as a solution.

**Comment by campgurus** [comment]
Ok timeboxing this.  the logic is working for the most part. User can subscribe and unsubscribe via EBW.

Having trouble with the actual MailChimp form which will not seem to accept new users. So we need to check that to confirm it is working when a user signs up directly on MC.

Also seeing 405 error in MailChimp server in Rspec.  Error is not present on local server.

**Comment by campgurus** [comment]
Adding this link to SO conversation on this issue: http://stackoverflow.com/questions/32356804/checking-user-subscription-status-on-a-mailchimp-list-in-rails-4?noredirect=1#comment52649316_32356804

**Comment by campgurus** [comment]
Fixed the 'no file chosen' issue with commit 11a7c1276a3c80d07b2647421fb7b9f957accd27.

Noticed that I never set up user to have an uploaded avatar.  need to fix that now.

**Comment by campgurus** [comment]
the branch with these fixes is profile_page_fixes

**Comment by campgurus** [comment]
I do not know why this issue remains open and unmerged.  All of the items listed in the checkboxes above are fixed as I have confirmed by manual testing.  Looking at past commits, the only thing I see is that they way we check for MailChimp membership could be better, tho it works now.

**Comment by rlgreen91** [comment]
@trystant @campgurus  Can we close this issue?  From what I can tell, this all seems to have been merged a while ago.

**Comment by trystant** [comment]
Yeah, this is done.
