### ISSUE TITLE
Add modals for comments, login

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1219]
Using modals and ajax for these forms will make the ux more friendly/modern and also limit demands on the back end, i think.

I am hesitant to label this a `quick_fix`, but I was able to employ these tools successfully in the fullcalendar branch, so i am thinking it should be possible for me to extend their use to appropriate parts of the app. 

With fullcalendar, I followed the tutorial documentaton, however these seem more generalizable:

https://coderwall.com/p/ej0mhg/open-a-rails-form-with-twitter-bootstrap-modals

**Comment by rlgreen91** [comment]
How exactly will using modals and AJAX be more UX friendly?  Or limit demands on the back-end?  I honestly don't see the point behind changing the existing comment box to be a modal.

I get using a modal for login, since that would hopefully re-render the previous page, just logged in.  I'm just not getting it for the comment box.

**Comment by campgurus** [comment]
I think from a user's perspective, it is cleaner interaction, but that may just be my personal opinion. In terms of back end demands,  if by using AJAX, the entire page doesn't have to reload every time a new comment is added, that would seem to require less calls to the server, no?

**Comment by rlgreen91** [comment]
Oh, I think there was a miscommunication - I mean, why make the comment box be a modal?  I think we have to address the purpose behind comments first, since it seems like we're not sure about that.

**Comment by rlgreen91** [comment]
I still think we need to figure out what the comments are for, and where that fits into the case page as a whole.

**Comment by trystant** [comment]
Agreed, I think that UI/UX for that feature should be part of the
discussion about the viability of comments long term. @campgurus...do
you have screenshots from your fullcalendar branch?

**Comment by campgurus** [comment]
this issue is old. closing.
