### ISSUE TITLE
Add react to Rails

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#123]
Since we've decided to go down the React path, we need to add it to Rails.

**Comment by trystant** [comment]
Here's a [post](http://www.openmindedinnovations.com/blogs/3-ways-to-integrate-ruby-on-rails-react-flux) on some ways to integrate React into the project.

**Comment by campgurus** [comment]
should we close this as vague?  If not, I think we need to include the specific reason we are adding react and what we want to use it for.

**Comment by trystant** [comment]
Yes, definitely close this. There's no explicit reason for React at this
point in time.

On Mon, May 9, 2016 at 5:58 AM, campgurus <notifications@github.com> wrote:

> should we close this as vague? If not, I think we need to include the
> specific reason we are adding react and what we want to use it for.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BOWiki/BOW/issues/123#issuecomment-217823866>
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by rlgreen91** [comment]
Lol, so no one ever actually closed the issue...
