### ISSUE TITLE
Convert Link Model associations to polymorphic

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1234]
right now, link belongs_to article, so if we want to have links associated with eg agencies, or calendar_events we would need to create a separate model like agency_links etc for that purpose.

I think we could DRY up our code by creating a polymorphic relationship such that articles, agencies and calendar_events are all "linkables" associating with the same Links model.

I think we could do the same with the video_links we use for embedded videos, and also with uploaded photos (assuming that it is not affected somehow by carrierwave/s3/etc)

**Comment by rlgreen91** [comment]
I disagree with this approach. When I think of declaring something as polymorphic, I see that thing as being its own domain, of being a set of data and functionality that should be encapsulated as a model and have its own table in the database.  What makes it polymorphic is that we essentially need to use that model in multiple places.

To me, external links don't rise to that level.  What functionality or data is there to encapsulate?  There's nothing about the links that we would want to save - the links don't even make sense outside of the context in which they're used.  A link to a newspaper article only makes sense in the context of a case, really.  There might be some overlap, but I just don't think it's enough to warrant the complexity of a polymorphic model.

I think we'd be better off just having a links attribute containing an array of associated external links. @msnyon what do you think?

**Comment by campgurus** [comment]
Where do we put an article that talks about reforms at the NYPD? It would seem logical to attach it to the Agency.

Where would we put an article about coverage of a past CalendarEvent? 

Not sure why this is not generalizable in the same way that we have commentables and followables...

**Comment by rlgreen91** [comment]
Like I said above, this makes more sense as a attribute.  So, in the `case` table, there's an `external_links` column that takes an array of URLs.  Same for events, agencies, etc.

Could we generalize this?  Sure, but to me it doesn't make sense.  I mean, look at the `link` model - it is literally one line.  There's no data being saved other than the link itself, really.  Now we want to make it polymorphic, increasing the complexity, and continuing to spin up objects every time this is used?  It just doesn't seem worth it to make an object out of this - it would be like making a date model and having it be polymorphic so you could attach it to events and cases.

**Comment by campgurus** [comment]
ok. thanks for the explanation.

**Comment by rlgreen91** [comment]
I'll go ahead and look into how we can get rid of the existing table and add that data to a links column on articles - although that might have to wait for us to finish renaming article as case.

**Comment by campgurus** [comment]
here is something I found on inputting an array field with Simple Form:https://tenforward.consulting/blog/integrating-an-array-column-in-rails-with-simple-form

**Comment by rlgreen91** [comment]
Given that we're go.ing with a different approach to handle links, I will close this
