### ISSUE TITLE
Add classes to links for analytics

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1253]
As I look at the Ahoy data, there are many places where a user can click eg to get to a case, eg from the index page gallery or recently updated list, from the show page nearby cases gallery, or even from a reference with the content sections of another case.

Adding classes to these links is one way that we can see in Ahoy, which links are being clisked on, which in turn helps us determine changes we may want to make. For example, I can tell that people are clicking on the links in the gallery photos because they are classed as "info2". Obviously we can make class names more descriptive.

If there is a better way to get this information, I am open to it.

**Comment by rlgreen91** [comment]
I might be misunderstanding this - how does that clarify the data that is already collected on each visit?

While I'm all for having more semantic HTML, there's definitely some changes I want to make in terms of the design of site, particularly in terms of organization and clarity.  I'm wondering if adding more data now will make it more complicated to update that HTML and understand older data at a later date.

**Comment by campgurus** [comment]
here is an example:

this is a visit: https://ebwiki.org/admin/visit/361d3c1b-51f9-48eb-8638-7016cfa30d5b

it has attributes, like start_time, user, browser, device_type etc.  It also has_many :events.

Events are essentially views and clicks (i think we can add custom events as well).

Here is an example of an event: https://ebwiki.org/admin/ahoy~event/052f3f5e-fbdc-4be0-a98c-9f833cee91d1

The event has attributes like time, type, user, visit_id, and then a properties hash (which we still have not figured out how to parse programmatically -- see issue #93 ). The properties hash in a Click event includes what page they were on and the class or id assigned to the link they clicked.

So by classifying the links, we can distinguish when a user is clicking to an article from the recent articles list vs the index gallery or the nearby cases gallery for a specific case.

**Comment by rlgreen91** [comment]
Can we just take a moment to acknowledge that those links should be slightly unsettling?

Anyways, my concern was more along the lines of what happens if we start out tracking say, search result clicks using `class="search_results"` but then later we want to change it, say for example, to distinguish between API and site usage, like `class="web_search_results".  Does that cause a problem later on?

I have to admit - Issue #93 worries me.  Like Mark, that issue has me questioning if Ahoy is worth the trouble at all.  Let's talk more about that question later.

**Comment by campgurus** [comment]
Ahoy::Events is a model, so I think if we in the past had labeled a class "a", and wanted to change all of them to class "b" we could probably do a rake task to make that change programmatically.

As to #93 I still like ahoy, if we can figure out the event.properties hash. If we use our own analytics solution, we don't have to share all of our data with Google or whoever we outsource that function to, who might later be compelled to reveal our data in a way that is not helpful to us.

**Comment by rlgreen91** [comment]
Ok.  We can add going through and figuring out classes as a to do item.

**Comment by trystant** [comment]
We have this data we've collected. How to view/evaluate it?

**Comment by trystant** [comment]
I'm also in favor of prioritizing creating tests for any analytics code. I'm reluctant to do any work without having more automated tests in order to help with modifications.

**Comment by rlgreen91** [comment]
Of course.  I have some leads on how we can use this proposed data better, but it's fairly down the list at this point.

**Comment by campgurus** [comment]
Not sure where we are on Ahoy. I am very much in favor of moving beyond Google Analytics to get a better view of how best to engage our users and I like the idea of not having to send our data out to a service to be parsed, but not sure the extra effort is worth it, vs what we could potentially get from Mixpanel, etc

**Comment by campgurus** [comment]
I also think the choice of what service is secondary to having a working analytic page to view it on.

**Comment by rlgreen91** [comment]
Yes, @trystant removed the analytics code in 2019 as we were just having too many issues with Ahoy.  In November, Mark noted a general roadmap here: https://ebwiki.slack.com/archives/C04JHAM8V/p1574434349032700.

I will make a record of that in Todoist + issues here.  This issue can be closed.
