### ISSUE TITLE
Replace current captcha with Google Recaptcha

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#126]
The current captcha solution, [gotcha](https://github.com/trystant/gotcha) is decent, but the Recaptcha interface would be better. Also, the reverse string captcha is more difficult than some banks, so the string should be either shortened or removed.

**Comment by campgurus** [comment]
Attempted to fix this.  For some reason, no matter what I enter, I get "Invalid Captcha" in  notice at the top of the screen.  I actually changed that messsage so I am not sure where it is still coming from. Yes, I restarted the local server. :)

**Comment by campgurus** [comment]
Code for this is in the recaptcha branch

**Comment by rlgreen91** [comment]
Whatever happened to this?  I can't seem to find this branch or a PR.

**Comment by campgurus** [comment]
Not sure. I never got it to work, so the branch may have been deleted.

**Comment by rlgreen91** [comment]
Alright, well I guess this is closed then.

**Comment by campgurus** [comment]
Reopening this for the moment if we want to do this.  Was able to add recaptcha "I am not a robot" button to confirm human users at signup at password reset within about 10 minutes.

Here are the relevant links: 

https://github.com/billhimmelsbach/recaptcha-rails
https://github.com/plataformatec/devise/wiki/how-to:-use-recaptcha-with-devise

**Comment by rlgreen91** [comment]
@trystant are we able to proceed with this?  If so, please add the Hacktoberfest label back to the issue.

**Comment by rlgreen91** [comment]
@trystant has addressed this.
