### ISSUE TITLE
Enable HSTS in site

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1268]
Security wise, we want to enable strict transport security to prevent man-in-the-middle attacks and protocol downgrade attacks.  ([See here for more info](https://blog.theodo.fr/2017/12/improve-website-security-5-minutes-http-headers/))

To do so, we need to set `config.force_ssl` to `true` in `config/environments/production.rb` and `config/environments/staging.rb` - this will prevent most protocol downgrade attacks.  Additionally, we should satisfy the requirements to be included on the HSTS preload list as described [here](https://hstspreload.org/) to prevent the remaining percentage of protocol downgrade attacks.

Simple use of HTTPS via our existing certificate should take care of the man-in-the-middle attacks.

**Comment by trystant** [comment]
So here are current settings on staging & production as a result of configuring [Cloudflare](https://cloudflare.com) settings.
Staging:
![screenshot 2018-05-31 at 23 32 50](https://user-images.githubusercontent.com/13509/40819809-1434ce0a-652b-11e8-87cd-a0cb1f3be564.png)
Production:
![screenshot 2018-05-31 at 23 34 27](https://user-images.githubusercontent.com/13509/40819836-3707c36a-652b-11e8-86b4-4ad832e66b1c.png)

Only thing left is to check against the link up above for potential gotchas.

**Comment by rlgreen91** [comment]
Nice.  So it seems like we can close this then?  I still plan to do a bit more reading in terms of beefing up security.

**Comment by trystant** [comment]
It is in terms of HSTS being enabled. We can open tickets for other headers
we need to enable in the future

**Comment by rlgreen91** [comment]
@trystant why did we decide to disable `config.force_ssl`?

**Comment by trystant** [comment]
Because Cloudflare handles that aspect

**Comment by rlgreen91** [comment]
Can we add a comment in the environment files noting that Cloudflare handles the SSL configuration?  I keep forgetting.

**Comment by rlgreen91** [comment]
Note: all this issue requires is adding a comment in the environment files that Cloudflare handles the SSL configuration and so to leave that setting disabled.

**Comment by rlgreen91** [comment]
Addressed in #3381
