### ISSUE TITLE
Add content on how to use EBWiki (1 of 3)

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#130]
This is not so much technical as editorial. But it is important to the usability of the app and clarifying what EBW does.  This is the start of a working list for content pieces we need to add:
- How to Add a New Case
- How to Edit an Existing Case
- How to Follow a Case
- How to sign up for the newsletter

**Comment by rlgreen91** [comment]
This issue should now be - add a new view under `static_pages` that is intended to be a guide to contributing to the wiki.  Just put coming soon as the content, and **do not** add any links to the page elsewhere in the code.
