### ISSUE TITLE
Need to clarify EBWiki branding

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#132]
from feedback: what does the "EB" stand for? The abbreviated name is memorable; I found myself wondering what it stood for though -- maybe make that more prominent somewhere on the home page? it doesn't even appear on the About page, FWIW

**Comment by campgurus** [comment]
A slogan/tagline may solve this issue.

**Comment by rlgreen91** [comment]
At this point, on the about page, start the first paragraph off with "End Bias Wiki (EBWiki)" to establish what the name means.

**Comment by rlgreen91** [comment]
Addressed in #3438
