### ISSUE TITLE
Is this the best way to do an enum?

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1332]
https://github.com/EBWiki/EBWiki/blob/b9e60d5e7d9f76171e155ab683eac52922d1c0f4/app/models/agency.rb#L5-L14

Especially considering that [ActiveRecord enums](https://www.justinweiss.com/articles/creating-easy-readable-attributes-with-activerecord-enums/) exist?

What are your thoughts, @rlgreen91 ?

**Comment by rlgreen91** [comment]
Ok, so I did a bit of digging into this.  I do like ActiveRecord enums as outlined in the article you linked.  I also am interested in pairing them with PostGreSQL enums, as outlined [here](https://www.sitepoint.com/enumerated-types-with-activerecord-and-postgresql/).  Additionally, using the combo of ActiveRecord/PostGreSQL enums will allow us to drop the enumerated-type gem.

I say let's go for it.  Before I start outlining a milestone with issues, can we confirm what exactly the types will be?  Should they be capitalized?  In alphabetical order?

**Comment by rlgreen91** [comment]
Ok, I'll create a set of issues and a project around this for people to work on.

**Comment by rlgreen91** [comment]
Given that we are in the midst of doing this via other issues, I will close this issue.
