### ISSUE TITLE
Add docs for setting up a local development environment.

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1335]
Currently, the docs for setting up a local development environment are hidden in the wiki.  Create a Markdown document within `docs/` that will contain the instructions found in the wiki document.  Add screenshots where appropriate, and link the section headers so that users can jump to the appropriate section.  Finally, add a link to the document in the README.

**Comment by Paarmita** [comment]
@rlgreen91 I wanted to work on this issue. Can I update the docs?

**Comment by rlgreen91** [comment]
Sure, feel free to assign the issue to yourself.
