### ISSUE TITLE
Change jurisdiction enum to jurisdiction_type

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1343]
**Note: This is issue 1 of 7, and the requested changes must be merged before you can move to the next one in the project.**

Run a migration that changes the `jurisdiction` column in the `agency` table to `jurisdiction_type`.  Then, change the name of the class within the `agency` model to match the new name.

**Comment by rlgreen91** [comment]
This address part of the change discussed in #1332

**Comment by StlMaris123** [comment]
@rlgreen91, @trystant, will the `jurisdiction_type` be of type `integer`?

**Comment by rlgreen91** [comment]
No, for right now it should be string, I believe.  I would like at the gem documentation to see how they save it, but it's probably string. Still, we're just changing the column name, not the data itself.
