### ISSUE TITLE
Remove the enumerated_type gem (7 of 7)

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1349]
**Note: This is issue 7 of 7, and all of the preceding issues in this project must be closed before you can begin this one.**

Remove the `enumerated_type` gem.

**Comment by rlgreen91** [comment]
This address part of the change discussed in #1332

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , I will work on this and all the issues related to the gem. Is it okay to proceed?

**Comment by rlgreen91** [comment]
Yes, just be sure to check the project this issue is in, since all of the issues have to be completed in a specific order.

**Comment by rlgreen91** [comment]
Addressed in #2963
