### ISSUE TITLE
There should be documentation about the development tools used and ways to access them

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#135]
Right now in order to use EBWiki, there are a series of external services, including:
[Rollbar](https://rollbar.com/trystant/BOW/) (login required)
[Code Climate](https://codeclimate.com/github/BOWiki/BOW)
[TravisCI](https://travis-ci.org/BOWiki/BOW)

These should be outlined in a DEVELOPMENT.md file in the repo at the least, if not also in the BOWiki

**Comment by Paarmita** [comment]
@trystant Can I write them in DEVELOPMENT.md file.

**Comment by rlgreen91** [comment]
@trystant is this still something that needs to be done?

**Comment by trystant** [comment]
I think wecan close this for now.
