### ISSUE TITLE
Remove "Precompiled Assets" section from development.md

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1350]
Remove the "Precompiled Assets" section from `development.md`.

**Comment by rlgreen91** [comment]
You can also include `[ci skip]` in your PR title somewhere so that it doesn't run Travis - we don't really need to run the tests for this.

**Comment by Paarmita** [comment]
@rlgreen91 I would like to correct this up?

**Comment by rlgreen91** [comment]
@Paarmita That's fine - remember, you don't have to wait for me to approve.  Just go ahead and assign the issue to yourself.

**Comment by Paarmita** [comment]
@rlgreen91 this issue has been solved and pull request has been merged.
![screenshot](https://user-images.githubusercontent.com/26546816/39080825-bf1f7f2e-4553-11e8-8faa-9d8172c1b87c.png)
