### ISSUE TITLE
Case Images not showing

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1412]
This is what it looks like now:

<img width="911" alt="screen shot 2018-03-30 at 6 46 19 am" src="https://user-images.githubusercontent.com/1260659/38135442-17558b5e-33e6-11e8-82b4-29cdb406b99b.png">

**Comment by campgurus** [comment]
Images are not showing on staging either.

**Comment by campgurus** [comment]
I think I have found the source of the issue.  to display the image, we reference the uploaded image via the s3 folder with a url like: "uploads/case/avatar/3326/large_avatar_bijan_ghaisar.jpg" which corresponds to the folder that has been created with the new model name "uploads/case"

This works fine for new uploads. However, all previous images are stored in the folder named "uploads/article", so these old images are not being found. So we can either transfer all the old images from the article folder to the case folder, or somehow get the older cases to refer to the article folder until/unless they are updated with a new image.

**Comment by campgurus** [comment]
this command worked for the majority of images on my local, but not all:
`s3cmd sync s3://blackopswiki-dev/uploads/article/avatar s3://blackopswiki-dev/uploads/case/avatar` i have not tried it yet on staging.

the site is basically unusable, esp the index page at this point.

**Comment by trystant** [comment]
`s3cmd mv s3://blackopswiki-dev/uploads/article s3://blackopswiki-dev/uploads/case` resolved this. It took  a bit under 2 hours to resolve.
