### ISSUE TITLE
List of things to A/B Test using split gem

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#142]
We have the split gem in place in the split branch.  In the context of getting users to do the things we want them to view, follow, edit, sign up for the newsletter, etc.  Let's keep a list of things to A/B test:
- does moving the follow and share buttons above the pic raise engagement?
- the color of the newsletter sign up button
- placement of nearby_cases on show pages

Add yours!

**Comment by trystant** [comment]
is there an applicable list to test?

**Comment by rlgreen91** [comment]
I think we can go ahead and close this.  There are a number of general UI improvements that can be made now.  I'm not comfortable with our current baseline to compare against UI changes - let's raise the baseline first.

**Comment by trystant** [comment]
Agreed on that.
