### ISSUE TITLE
keyword search returns incorrect results

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1432]
to replicate this enter "linus phillip" in the header search box.

This search retrieves one case.  However, it does not retrieve the correct case which does exist on the site: https://ebwiki.org/cases/linus-f-phillip

This will be an issue for editors adding new cases, who may not see an existing case and create duplicates of cases we already have.

**Comment by campgurus** [comment]
here is another example where a duplicate case was created and only one case shows in search results for: "anthony jacob weber"

**Comment by rlgreen91** [comment]
Hmm, did you happen to have the logs open when you ran the search?

**Comment by trystant** [comment]
Linus Phillip Search

![screenshot 2018-05-20 at 09 55 10](https://user-images.githubusercontent.com/13509/40279642-ea98ddf4-5c13-11e8-8a3d-5ede69ee4ced.png)

Anthony Jacob Weber shows two cases:
![screenshot 2018-05-20 at 09 56 05](https://user-images.githubusercontent.com/13509/40279646-1439da32-5c14-11e8-9adf-558ec8d69473.png)
