### ISSUE TITLE
Add 301 permanent redirect for /articles --> /cases

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1437]
Since we made the change from `articles` to `cases`, traffic to the site has dropped off sharply:
<img width="656" alt="screen shot 2018-04-05 at 10 39 53 am" src="https://user-images.githubusercontent.com/1260659/38373218-b65a52a2-38be-11e8-9b99-716ea9f4570b.png">

This is likely due to Google search results still pointing to the old urls.  We could solve this issue (seems like good practice generally) by setting up permanent redirects from /articles to /cases.

here is one suggested solution:
https://stackoverflow.com/questions/25293107/how-to-make-resources-redirect-to-another-controller-in-rails

and one more:
http://guides.rubyonrails.org/routing.html#redirection

**Comment by campgurus** [comment]
The first solution pointed to delivers the correct page but does not change the url so eg it creates the route for articles/john-smith which has the identical content to cases/john-smith

The concern is that Google will punish us for having duplicate content.

The second solution creates this routing:
`articles_redirect_path | GET | /articles(.:format) | redirect(301, /cases)`

but does not display the page returning the error No route matches [GET] "/articles/shaaliver-douse"

**Comment by campgurus** [comment]
Bumping this issue traffic is not recovering at this point. see the past two weeks since the url change:

<img width="691" alt="screen shot 2018-04-18 at 8 08 51 am" src="https://user-images.githubusercontent.com/1260659/38931073-06fd2ab0-42e0-11e8-869a-372b87204c94.png">

What is the right solution?

**Comment by trystant** [comment]
A couple of methods have been tried. This includes:
`[get '/old/path', to: redirect('/new/path', status: 301)](https://stackoverflow.com/questions/19138743/how-to-redirect-with-a-301-or-302-in-the-routes-rb)`
`[match 'articles', to: 'cases'](http://guides.rubyonrails.org/v4.2/routing.html#redirection)`

There's no one stop solution, and the explicit routes may need to be written for every resource action.

**Comment by trystant** [comment]
This is now in production. @campgurus let's keep track of the visits and see what the impact is or will be.

**Comment by trystant** [comment]
While the traffic hasn't changed, the redirects are now in play. We can close this ticket for now and see how the traffic is over time.
