### ISSUE TITLE
Search button misaligned 

### ISSUE THREAD

**Issue by StlMaris123** [EBWiki/EBWiki#1439]
The search button on the home page is misaligned as shown on the screen shot below.
![screenshot from 2018-04-05 20-09-19](https://user-images.githubusercontent.com/13062617/38380732-53019338-390d-11e8-963c-1af1d818bb7e.png)

**Comment by rlgreen91** [comment]
Hey @StlMaris123 thanks for catching this! This is covered in Issue #946, so I'll close this for now.

**Comment by rlgreen91** [comment]
Why did I close this?

**Comment by trystant** [comment]
This was fixed by #997
