### ISSUE TITLE
Create category locale file

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1440]
Within config/locales, create a file views/categories/en.yml that contains a list of categories namespaced under categories and en. It should look a bit like this:

```
en:
  catgories:
    choking: 'Choking'
    shooting: 'Shooting'

The key for each category should be the same as those currently in the database. The corresponding string value should be properly capitalized. The key value pairs should be listed in alphabetical order.

**Comment by Paarmita** [comment]
@rlgreen91 How can I find the categories to be listed in this?

**Comment by rlgreen91** [comment]
It should be listed in the seeds file.  If not, you could just see what the values are on the actual website and list them there.

**Comment by StlMaris123** [comment]
Hi @Paarmita , are you still working on this issue?

**Comment by rlgreen91** [comment]
I'm going to close this because we should really rename this model to cause of death or something more descriptive first.
