### ISSUE TITLE
Improve performance of query for case versions

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1443]
Improve the performance of the query for versions of a case.  Currently, the cases controller has a method `history` that runs the following query to retrieve the different versions:

```
@case_history = @this_case.try(:versions).sort_by(&:created_at).reverse
```

Replace that with the following statement:

```
@case_history = @this_case.try(:versions).sort_by { |version| -version.created_at }
```

Also include a comment explaining that adding the `-` essentially performs the reverse sorting at the database level, rather than pulling all of the data back within the Rails application and performing a reverse there.

**Comment by StlMaris123** [comment]
@rlgreen91 , on the first part of the issue is it okay to use the safe navigator, then we now have `@this_case&.versions` in place of `@this_case.try(:versions)`

**Comment by rlgreen91** [comment]
Eh, I would just stick with the `try` method.  In all honesty, this is actually code that we should fix at a deeper level - we should have some null object that can be returned and still allow this to function correctly without a try or safe navigator.
