### ISSUE TITLE
Create fixture file for categories

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1444]
Create a fixtures file categories.yml containing each category. Just copy, more or less, the info within db/seeds.rb.

**Comment by rachaelkiteme** [comment]
Hello @rlgreen91 the categories are not listed anywhere in db/seeds.rb neither are they in the website.

**Comment by rlgreen91** [comment]
They should be in the website at the least - it's the categories we use for cause of death when adding a new case.

**Comment by rachaelkiteme** [comment]
Wow thank you very much.

Regards
Rachael
