### ISSUE TITLE
Send email when comments are made on a case

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1447]
When someone comments on a case, we should be sending an email to the followers of that case as well as anyone else who has previously commented on that case.

**Comment by rlgreen91** [comment]
I mentioned this in Slack, but let's stop and take a step back and think about our email strategy.

**Comment by trystant** [comment]
@rlgreen91 We can outline an overall strategy in English before putting it in code. I feel that we do need to keep the users' preferences in mind, so every mail action only occurs if there is explicit permission granted.  Any other thoughts on sending email, or is there a better thread to discuss this?

**Comment by rlgreen91** [comment]
We also need to include our marketing strategy - there was quite a bit of stuff that lead to emails there too.  I think the best place to hammer that out might be Trello - Slack is too ephemeral, and that's not really what Github is for.

**Comment by rlgreen91** [comment]
Sounds great.  I'll start that this weekend.

**Comment by rlgreen91** [comment]
@campgurus @trystant we can discuss this more in Slack, but is this something we still want to do?  I'm leaning towards no.

**Comment by trystant** [comment]
I would lean closer to "not right now" than "No".

**Comment by campgurus** [comment]
closing this. I think @trystant's concern re preferences should be addressed before we do this. With Sendgrid, we can easily set up Unsubscribe preferences that allow users to opt out of specific types of email messages. That way the people who want these updates get them and others d o not.  Separately, I think we should consider some kind of chron, that sends an email once/day, vs on demand which might e better for conserving server resources and also not sending a bunch of emails to a user at once.
