### ISSUE TITLE
Duplicate comments being posted

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1449]
Not sure why this is happening and I have not been able to replicate but I have seen this a couple times recently:
<img width="304" alt="screen shot 2018-04-06 at 9 46 07 pm" src="https://user-images.githubusercontent.com/1260659/38449980-1e96cfb4-39e4-11e8-8ceb-327add780318.png">

I don't think an error is being thrown, but wanted to make sure this issue was on our radar.

**Comment by rlgreen91** [comment]
Yeah, so I just tested this on the Saheed Vasall case - it's entirely possible to hit the submit button twice before the page refreshes.  The site is behaving correctly - that's human error at this point.  There's not really much we can do about that, so I say let's close this.

**Comment by trystant** [comment]
This can be resolved by disabling the button upon the click event. We should apply that to all submit buttons on the site.
