### ISSUE TITLE
 arguments passed to url_for can't be handled

### ISSUE THREAD

**Issue by StlMaris123** [EBWiki/EBWiki#1475]
Full error message is `arguments passed to url_for can't be handled. Please require routes or provide your own implementation (ArgumentError)`.
This occurs when I run the tests.

It has been captured on `/EBWiki/app/helpers/user_notifier_helper.rb:7:in <module:UserNotifierHelper>`

**Comment by trystant** [comment]
@StlMaris123 Is this a duplicate of #1471

**Comment by rlgreen91** [comment]
@StlMaris123 are you sure you're on the latest version of the codebase?  I just ran the tests locally and didn't get that error - and it hasn't shown up in CI when we've been making PRs.  Mark can you recreate this?
