### ISSUE TITLE
Update rails-html-sanitizer gem

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1477]
Update the `rails-html-sanitizer` gem.  Be sure to verify that:

- [x] All tests still pass
- [x] You can destroy and recreate the database successfully
- [x] The site still works correctly

**Comment by trystant** [comment]
@rlgreen91 The destroy & recreate is done through `rake`?

**Comment by rlgreen91** [comment]
Yes, just `rake db:drop db:create db:migrate`

**Comment by trystant** [comment]
I've run the other two tests.

**Comment by rlgreen91** [comment]
Addressed in #1492
