### ISSUE TITLE
Material for presentation

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#148]
Hi @campgurus 

So in terms of slide 7 on this presentation, we can discuss Grant Writing as well as exposure to the non profit sector so that we know whom to ask the right questions, and to which organizations we should submit grants.

We can discuss reach when ready, how the NAACP can use its network to raise awareness about EBWiki. We can also discuss whether there are specific members of the NAACP who might find this particularly useful (people involved with protest, people following cases from a legal perspective).

In terms of marketing assistance, we'd need to put together a marketing plan in order to determine the assistance that we would need. I have no experience with putting together a marketing plan. We should find an expert and consult with them on this.

I think that the biggest item left is the development plan & budget.

Let me know if this helps or not.

**Comment by rlgreen91** [comment]
While useful, this doesn't really need to be an open issue.
