### ISSUE TITLE
Upgrade elasticsearch to 6.x

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1534]
We're currently using a very old version of Elasticsearch on Searchbox in production (1.7.6)
![annotated_elasticsearch_version](https://user-images.githubusercontent.com/13509/40127462-671b9084-58fd-11e8-9141-aa85906f6fa2.png)

We should upgrade Searchbox to the latest version of 6.2.4. One change we need to make in order to keep the existing search working is to change the `Case.search "query"` query to `Case.search "query", fields: ["*"]`

**Comment by trystant** [comment]
I've opened a customer service request to searchbox about upgrading because there's no easy way to do this in heroku.

**Comment by rlgreen91** [comment]
Dear God, 1.7.6?  By the way, have we ever looked at the elasticsearch-rails gems?

**Comment by trystant** [comment]
We haven't. `seachkick` provided what we needed at the time.

Also, considering that `elasticsearch-rails` hasn't been updated in 6 months and `searchkick` was updated two days ago, I feel like we're okay sticking with `searchkick`

Separately, dropping & readding should upgrade Elasticsearch to 6x.

**Comment by trystant** [comment]
Looks like we're up to 6.4 in production
![screenshot 2018-05-20 at 01 54 29](https://user-images.githubusercontent.com/13509/40276171-c909faa8-5bd0-11e8-85b1-c57db43116be.png)
