### ISSUE TITLE
Versions table not showing up in admin and History tabs are all empty

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#1553]
Case history tabs are all showing empty.  Here is the tab for Freddie Gray:

<img width="756" alt="screen shot 2018-05-20 at 5 10 56 am" src="https://user-images.githubusercontent.com/1260659/40277393-75b0094e-5bec-11e8-96d8-74f967645a87.png">

Checking on the console, seems to reveal that the Versions table has been disappeared. I am hesitant to add or edit cases with no record available of the changes made.

**Comment by trystant** [comment]
I'll take a look at this. I don't know when versions went by the wayside; I had made a view change.  Taking a look.

**Comment by trystant** [comment]
The versions table is still in the database. We're using a really older version of `paper_trail`.  The history page had been returning an error for a couple of weeks, and I believe that we can resolve this fairly quickly.

**Comment by campgurus** [comment]
bumping this.  It is difficult to update cases when the editor cannot easily see whether the update has already been made.

**Comment by campgurus** [comment]
bumping this again.

**Comment by rlgreen91** [comment]
This has been addressed.
