### ISSUE TITLE
Create a page for prompting further actions

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1573]
Create a static page titled "Get Involved" with the subtitle "How to Make Your Voice Heard".  The page should have the following sections:
* Signing up for the newsletter
* Following us on social media
* Following cases

Just adding the titles right now is fine, as we wait for details on the copy.

**Comment by k-stewart** [comment]
I'll give this a go.

**Comment by rlgreen91** [comment]
Addressed in #3436
