### ISSUE TITLE
Add "How You Can Help EBWiki" page

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1575]
Add a static page titled "How You Can Help EBWiki".  This page should contain the following sections:
* Adding Content to the Wiki
* Working on the Website
* Spreading the Word about EBWiki
* Making a Donation
* Other Ideas, Skills, and Resources

You can leave them blank for right now as we work on the copy and corresponding pages.

**Comment by k-stewart** [comment]
I'd like to take this one, while i'm in the static controller.

**Comment by rlgreen91** [comment]
Addressed in #3437
