### ISSUE TITLE
Add project setup steps for development environment

### ISSUE THREAD

**Issue by bmwenda** [EBWiki/EBWiki#1594]
#### The Issue
I'm interested in contributing to this project, so I cloned and tried to set up on my local environment. The problem is that the README does not provide steps on how to set up locally. Luckily, I have some experience in setting up rails projects, so I knew what to do. For a beginner, this could have proved to be challenging though.

On top of that, I ran into this error while running migrations:
`ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key`

I figured out that there are some environment keys that should be set for migrations to run, that is AWS_ACCESS_KEY_ID, AWS_SECRET_KEY_ID and S3_BUCKET. Also, some tests fail because some other keys are not set.

#### Proposal
We could add a section on the readme that details how to get the project up and running locally, as well define the environment keys that require to be set. One thing in my mind is to add a sample `.env` file.

I'd like to hear your views on this

**Comment by bmwenda** [comment]
Found the detailed instructions [here](https://github.com/EBWiki/EBWiki/blob/master/docs/SETUP_LOCALLY.md). Sorry for the false alarm

**Comment by rlgreen91** [comment]
No worries.  If you have any other suggestions, let us know.  We're always trying to improve the docs.
