### ISSUE TITLE
rake geocode:all fails to update silently

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1614]
https://github.com/EBWiki/EBWiki/blob/e4c9099e6bd7d7577ddd92b5cc21f913e5a992e7/lib/tasks/geocode_data.rake#L14-L18

The `model.save` on line 16 fails if there are case models without a summary. Somehow 16 cases were created without summaries and those cases were resulting in multiple 500 errors on the site.

Adding a comment to the summary field fixed the problem, and updating the task to add the summary & testing it with a spec will resolve this issue.

**Comment by rlgreen91** [comment]
To be clear, this issue involves adding code within the `find_each` loop that will add a summary with the text 'Geocoded cases for map display'.

**Comment by rlgreen91** [comment]
Addressed in #3219
