### ISSUE TITLE
Moving staging database from Heroku

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1616]
This is a sub issue of #363 and already in progress. 

For a synopsis on what's happened so far:
I've created an RDS instance on AWS. This is a micro instance on the AWS free tier. It's currently powering the staging instance. The individual case page loads up in under 3 seconds, but there are also images that are returning 404s, so that is a factor as well.

The last two items related to task include:
*  Getting Ruby to work with SOCKS5 in order to improve security on the connection between RDS and Heroku.  I'm using [Fixie Socks](https://devcenter.heroku.com/articles/fixie-socks) on the staging instance, but Ruby + SOCKS5 + AcitveRecord do not seem to go together (more on that in https://github.com/trystant/dev-error-messages/issues/30).  
* Document the process & steps involved.

**Comment by rlgreen91** [comment]
@trystant what's the status on this?

**Comment by trystant** [comment]
We've moved this back to Heroku for the time being.
