### ISSUE TITLE
Map data for jurisdiction values to jurisdiction_type enum

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1621]
So, we need to account for the change from using `Jurisdiction` to `JurisdictionType` in the agency code by mapping the data correctly.  To do that, make the following changes:
* in `app/views/agencies/_form.html.erb`, change the collection for the jurisdiction input to be `Agency::JurisdictionType.map(&:name)`
* in both the `create` and `update` methods within `app/controllers/agencies_controller.rb`:
  -  pass along the `params` to `Agency.create` or `Agency.update` without the jurisdiction value - you can use `except` for the hash object for this
  - set `@agency.jurisdiction_type` to `params[:jurisdiction]`
  - then save the new version of the agency
* in `app/views/agencies/show.html.erb`, change the conditional for checking if the jurisdiction is present  to `if agency.jurisdiction_type.present?` and change the value displayed to `agency.jurisdiction_type.capitalize`

We also need some specs to cover this - good tests would have caught this before.  Let's add a feature spec for a user creating an agency. This is roughly how it should work:
* create a user and login as them - you can look at other feature specs to see how to do that
* go to the create agency form using the path - you can look at other feature specs to see how to do that in general
* enter values into the form and submit
* expect the page to update based on whether the submission was successful or not (for example, you would expect to go back to the home page with a notice that it was successfully created or to stay on the form and flash an error).

It would be best to test that it behaves correctly if the submission is successful and if it's not.  You can look at https://robots.thoughtbot.com/rspec-integration-tests-with-capybara as a good intro.  We already have capybara installed in the app.  In general, searching some variation of "features tests with rspec and capybara" should turn up some good resources.

This particular issue needs to be completed before any of the others since the functionality is technically broken.  I'll stick a note on your other PR as well about this.

**Comment by rachaelkiteme** [comment]
Okay @rlgreen91 will work on it. Thank you
