### ISSUE TITLE
Retire endbias-certificate-manager

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1640]
It looks like Heroku SSL has been updated to the point where the endbias-certificate-manager is no longer needed. I would like to follow the instructions of the [Automated Certificate Manager](https://devcenter.heroku.com/articles/automated-certificate-management) to upgrade the SSL process and save us some $$ and infrastructure.

**Comment by trystant** [comment]
This is a related to #363.

**Comment by trystant** [comment]
@campgurus let me know when you can transfer the certificate manager.

**Comment by rlgreen91** [comment]
Nice.  It's great to see that it now covers custom domains as well.  Shame it doesn't cover wildcard domains as well.

**Comment by trystant** [comment]
This service is now gone.
