### ISSUE TITLE
Add Pundit Gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1648]
Add the latest version of the pundit gem to the project.  Be sure to pin the major minor number in the Gemfile (e.g., if the version is 1.5.2, use `gem pundit, ~> v1.5`)

**Comment by StlMaris123** [comment]
HI @rlgreen91 can we update this to `version 1.1`? `version 2.0` is beta version

**Comment by rlgreen91** [comment]
You can put the most up-to-date stable version, we don't currently have this gem installed.

**Comment by rlgreen91** [comment]
@StlMaris123 Actually, 2.0 was released today so you can update to that when you're ready.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , I don't think we are using pundit in the Gemfile. Also authorization is done in files in the policies folder which we do not have

**Comment by rlgreen91** [comment]
@StlMaris123 Don't miss this one when doing gem updates.
