### ISSUE TITLE
Make links polymorphic (3 of 9)

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1655]
Note: This issue is 3 of 9 that need to be completed in a particular order for a feature.  Each issue should be closed and the corresponding PR merged before the next issue is begun.

This issue corresponds to adjusting the schema and model to make `Links` polymorphic.  Create and run a migration with the following methods:

```
def up
  rename_column :links, :case_id, :linkable_id
  add_column :links, :linkable_type, :string
  Links.reset_column_information
  Links.update_all(:linkable_type => "Case")
  add_index :links, [:linkable_id, :linkable_type]
end

def down
  remove_index :links, [:linkable_id, :linkable_type]
  rename_column :links, :linkable_id, :case_id
  remove_column :links, :linkable_type
  add_foreign_key "links", "cases"
end
```

Additionally, update the `Link` model to have the relation `belongs_to :linkable, polymorphic: true` and the `Case` model to have the relation `has_many :links, as: :linkable`.

**Comment by rlgreen91** [comment]
@rachaelkiteme Please note that I have edited the migration text above.

**Comment by rachaelkiteme** [comment]
noted
