### ISSUE TITLE
Update the pg gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1664]
Update the `pg` gem to the highest version possible given that the system employs Ruby 2.4.1, Rails 4.2.10, and PostGres 9.4.  Be sure to pin the major and minor version in the Gemfile (e.g., if a gem my_gem is at 1.5.2, the Gemfile should read `gem my_gem, ~> 1.5`).

**Comment by StlMaris123** [comment]
Hi @rlgreen91 could this issue wait? the latest pg version is 1.0 but rails does not support the version yet

**Comment by rlgreen91** [comment]
That's fine, this will serve as a record and reminder to check again later.

**Comment by rlgreen91** [comment]
This can now be updated to the latest version of `pg` available.

**Comment by rlgreen91** [comment]
Addressed in #3218
