### ISSUE TITLE
Update sass-rails gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1665]
Update the `sass-rails` gem to the highest version possible given that the system employs Ruby 2.4.1, Rails 4.2.10, and PostGres 9.4.  Be sure to pin the major and minor version in the Gemfile (e.g., if a gem my_gem is at 1.5.2, the Gemfile should read `gem my_gem, ~> 1.5`).

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , @trystant , gem 'sass-rails', '~> 5.0' is still the highest version. 6.0 is still in beta

**Comment by rlgreen91** [comment]
Thanks for the update!  I'll just leave this open as a record of proof

**Comment by rlgreen91** [comment]
That's fine, we'll go ahead and close this.
