### ISSUE TITLE
Create service object to process new users (1 of 3)

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1674]
Note: This issue is 1 of 3 for the given topic, and must be followed in the order listed.  The preceding issues must be completed and merged before continuing to the next issue.

Create a service object that replicates the functionality in `UserObserver`.  That is, given a user object, the service object should add the user to Mailchimp and send the welcome email.

**Comment by rlgreen91** [comment]
This is the article I read when I was introduced to the concept a couple of years ago - https://brewhouse.io/blog/2014/04/30/gourmet-service-objects.html.  It holds up pretty well I think.  There's really just a few things you want your service objects to do: 
* follow the Single Responsibility Principle (even if that responsibility is just coordinating other service objects); 
* be as functional as possible, in that you provide objects as inputs and do some operation without altering the objects - if you're altering the objects, then you're essentially dealing with business logic*
* have a single point of entry - if you look in our services folder, we have a Service concern that basically maps a class method `call` with the supplied arguments to an instance method that initializes the service object and then invokes an instance method `call` with the supplied arguments.  Each of the service objects we have now includes `Service` and defines an instance method `call`, and yours should too.

If you want to look into this more, try searching for "operations," "commands," and "interactors" since those are other terms for this type of design pattern.

*Yeah, I probably shouldn't say business logic since that's a term applied to both models and service objects.  Really, what it comes down to is the idea that a model represents your data, and whether/how it responds to CRUD operations in the database, while a service object represents what your application does with the data.

**Comment by StlMaris123** [comment]
First thing on my list tomorrow!!
