### ISSUE TITLE
This document needs a "Code of Conduct" document

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#168]
This follows the CODE_OF_CONDUCT documentation listed on the [contirbutor covenant](http://contributor-covenant.org/) site.

**Comment by trystant** [comment]
I can add a basic one to the site, and we should think about how this ties in with what we're doing and how to expand that as a result.

**Comment by rlgreen91** [comment]
I can't find an actual PR associated with this - makes me suspect that this was directly merged into master.  Anyways, closing as this was resolved in a prior commit.
