### ISSUE TITLE
Copy on case show page is center justified

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#1716]
After the latest release, the copy on the cases is center justified; it should be left justified.

**Comment by trystant** [comment]
![screenshot 2018-07-05 at 18 33 04](https://user-images.githubusercontent.com/13509/42351264-08302bd2-8082-11e8-96fd-8ffce9d58c29.png)

**Comment by trystant** [comment]
This is a formatting issue & not replicated.

**Comment by rlgreen91** [comment]
I know you closed this @trystant but let's ask - do we want to enforce formatting text on saving?
