### ISSUE TITLE
Update Devise gem to 3.5.10 (1 of 7)

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1728]
Note: This issue is 1 of 7 for the given topic, and must be followed in the order listed. The preceding issues must be completed and merged before continuing to the next issue.

Update the devise gem to version 3.5.10 - specify that version in the Gemfile.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , why don't update to `4.4`?

**Comment by rlgreen91** [comment]
Because there's been a breaking change - if you look at the changelog and the list of issues, you'll see that we have to make changes to account for the new major version of the gem.  Since this is a gem involved with our critical functionality for user accounts, we're taking it slow.
