### ISSUE TITLE
User avatar upload is not enabled

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#174]
Right now we are only usig gravatar images. Need to add avatar uploader to user.rb and make sure if a file is present, it takes priority over gravatar.

**Comment by campgurus** [comment]
This is not working.  Here is what I have done so far:

* Added avatar:string attribute to user model.
* Mounted the Uploader to user.rb
* Adjusted strong parameters in Users_controller
* Used updated form field for uploading.

No errors are thrown, but @user.avatar remains nil after uploading a file and updating user.

**Comment by campgurus** [comment]
File uploads are now working with one caveat.  The file uploader browser defaults to c:/fakepath which doesn't exist and must be manually overwritten with the correct path to make the upload work. 
<img width="327" alt="screen shot 2015-09-06 at 7 20 01 am" src="https://cloud.githubusercontent.com/assets/1260659/9704092/c60e6974-5467-11e5-80a8-b51261f90605.png">

Incidentally, the old form works without this happening.

In order to hide "no file chosen", I changed this:
`<%= f.file_field :avatar %> 

to this:
``` 
<h4>Upload a new photo</h4>
    <%= f.file_field :avatar, :id => "lefile" %>
  <div class="input-append">
    <input id="photoCover" class="input-large" type="text">
    <a class="btn" onclick="$('input[id=lefile]').click();">Browse</a>
  </div>
```
The form uses javascript to hide the "no file chosen" language and replaces it with  a new button. Unfortunately, we now get this fakepath side effect.

**Comment by trystant** [comment]
The code associated with this ticket is in the profile_page_fixes branch

**Comment by campgurus** [comment]
This issue has been fixe and should be cloe dwith issues #116
