### ISSUE TITLE
List requirements needed to call an issue "Finished"

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#179]
There needs to be a common definition of what "Done" means so that we can close a ticket successfully.

I've put together a first draft at the [wiki](https://github.com/BOWiki/BOW/wiki/Definition-of-%22Finished%22-Ticket) and in [DEVELOPMENT.md](https://github.com/BOWiki/BOW/blob/master/docs/DEVELOPMENT.md)

**Comment by rlgreen91** [comment]
Merged.
