### ISSUE TITLE
Update rspec-rails gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1793]
Update the rspec-rails gem to the highest version possible given that the system employs Ruby 2.4.1, Rails 4.2.10, and PostGres 9.4. Be sure to pin the major and minor version in the Gemfile (e.g., if a gem my_gem is at 1.5.2, the Gemfile should read gem my_gem, ~> 1.5).

**Comment by trystant** [comment]
According to the `Gemfile.lock`, we're at 3.7.2 now:

https://github.com/EBWiki/EBWiki/blob/2a1daa0ee0da7c4d14732ad5d0ed54a3daeb3ce4/Gemfile.lock#L571

I think we can close this for now.

@rlgreen91 ?

**Comment by rlgreen91** [comment]
I definitely thought we were at 3.0 for some reason.  Sure, sounds good.
