### ISSUE TITLE
Change mailer specs (1 of 4)

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1796]
Note: This issue is 1 of 4 for the given topic, and must be followed in the order listed. The preceding issues must be completed and merged before continuing to the next issue.

Right now, our mailer specs are in a bit of a weird state because they are attempting to be both unit and functional tests.  This set of issues will fix that by adding both types of tests, adding previews for the mailers, and removing an unused gem along the way.

To start with, let's make our current mailer specs unit tests.  First, write all of the tests within the same top level block for `UserNotifier`.  Then, remove any before and after hooks that are currently present and add the following ones:

```
before(:each) do
    ActionMailer::Base.perform_deliveries = true
    ActionMailer::Base.deliveries = []
  end
```

```
after(:each) do
  ActionMailer::Base.deliveries.clear
end
```

Then, within the actual tests, rather than using `mock_model`, just create the records using FactoryBot.  The actual test assertions themselves should work as currently written.  

Also, add the same tests for `admin_notifier`.

Finally, in the actual `user_notifier`, you don't have to use instance variables in any of the methods.  Change it to just use the variables listed in the arguments.

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , the issue is that this_case is not being versioned , so in send_followers_email.html.erb line 3, `<p>Case editor <%= User.find(@this_case.versions.last.whodunnit).name`, whodunnit is nil

**Comment by rlgreen91** [comment]
So, it is being versioned - the gem we use, Paper Trail, tracks who stopped a record from looking the way it did before.  So, the newly created case still looks that way, so there is no version yet.  It's kinda weird - the Paper Trail readme does a better job of explaining that, I'd look there.

So, it is possible that updating the case at the beginning of the spec could get you past this.  I'm not sure, so I'll look into it as well, but feel free to give it a try.
