### ISSUE TITLE
Update fog gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#1857]
Update the fog gem to the highest version possible given that the system employs Ruby 2.4.1, Rails 4.2.10, and PostGres 9.4. Be sure to pin the major and minor version in the Gemfile (e.g., if a gem my_gem is at 1.5.2, the Gemfile should read gem my_gem, ~> 1.5).

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , what else is pending in this issue?

**Comment by rlgreen91** [comment]
Did you actually make a PR for this?  I can't find one.

**Comment by StlMaris123** [comment]
Yes, https://github.com/EBWiki/EBWiki/commit/981dc3a3cc1ebacfd5d3bc93f1de58f3402fd6a7

**Comment by rlgreen91** [comment]
You pushed the commit, yes, but I don't think you actually opened a PR for it.
