### ISSUE TITLE
Allow anonymous editing

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#190]
This is an idea for discussion at this point, but I recently saw that Wikipedia allows non-logged in users to edit their articles. The stick is that their IP address will be credited with their edits.

The carrot is that by logging in they can be "more anonymous" with credit going to their assigned user and have a more customized experience.  Removing the login requirement may remove a hurdle to would-be editors. here is a link to Wikipedia's pitch for logins: 

https://en.wikipedia.org/wiki/Wikipedia:Why_create_an_account%3F

**Comment by trystant** [comment]
I think that this can be closed. IP address based login as anonymous is a non-starter.
