### ISSUE TITLE
Add jquery to toggle form for remove/change avatar

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#196]
if a user checks the box to remove the avatar, the option to add a new image should be removed from the page.

**Comment by rlgreen91** [comment]
I don't know that we have to use jquery, we might be able to get away with plain javascript.

**Comment by rlgreen91** [comment]
Actually, I'm not following - if a user checks to remove the avatar, wouldn't we want the option to add a new image to be present?

A screenshot would be helpful here.

**Comment by campgurus** [comment]
Honestly not sure what I was thinking on this one.  Closing this.
