### ISSUE TITLE
Team Needs

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#197]
This is one issue where we can keep track of skills or roles that would be helpful to fill for EBWiki
- iOS/Android developer (for an eventual mobile app)
- Back End Ruby Dev(s) (we can always use more of these)
- Front End html/css/js devs
- UX designers
- Graphic Design
- Social Media Manager
- SEO

**Comment by rlgreen91** [comment]
While useful, this doesn't really need to be an open issue.  Closed.
