### ISSUE TITLE
Remove state_objects method for application controller

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2095]
Remove the `state_objects` method from the application controller.

**Comment by rohan-techfreak** [comment]
But  the result from state_objects methods in being used in header.html.erb..
Do it still need to be removed?

**Comment by rlgreen91** [comment]
Hi @rohan-techfreak, sorry I missed your original message. 

At this point, given how the search bar is designed, we still need this and it should be closed.
