### ISSUE TITLE
Avatar should be added to subject

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#210]
Currently, the case photo is mounted on the article model.  It probably makes more sense to have the photo mounted on the Subjects model, as with other attributes of victims.  It will help in cses where there is more than one victim

**Comment by trystant** [comment]
Actually, the model should probably be polymorphous.

Officers can have photos, subjects can have photos, agencies (when fleshed
out) can have photos.

I'd look up polymorphous associations and implement those.

Address goes in the same category.

Thanks,
Mark

On Wed, Sep 9, 2015 at 5:11 AM, campgurus <notifications@github.com> wrote:

> Currently, the case photo is mounted on the article model. It probably
> makes more sense to have the photo mounted on the Subjects model, as with
> other attributes of victims. It will help in cses whee there are more than
> one victim
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BOWiki/BOW/issues/210>.
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by campgurus** [comment]
right, imageables.

**Comment by trystant** [comment]
CA
---------- Forwarded message ----------
From: "Support - Livecoding.tv" <support@livecoding.tv>
Date: Sep 11, 2015 5:53 PM
Subject: Watch Now! "Rails site search" (Ruby) by dogweather
To: <mark@grandkru.com>
Cc:

<http://email.mg.livecoding.tv/c/eJxVzDkOwyAQQNHTmBLNDItDQZEm92A3srEjQnz-0Eb6zWt-tElkqVm1BKjAIBIqIuI4LbhSWutFQiv8qHcKV6xn4eNmmyUt1WrQPEB4Ag_Gi5DSKrNDI73I7LDbGO_PIp4LvWZ_g2nWbXN9n_fS3Rn3_uXhaj8qqSps>
Sign
up for free
<http://email.mg.livecoding.tv/c/eJxVjUsKxCAQRE8Tl2K30ZCFi9nMPdpvJIkOxuT84ywHCorHgypvgoyzZtmgACVWAASFiBwGS66U1nqaxZn4kZ_gqs8l8f6wzURlV7BgCaOAQN7PQVuSFNUCcV0kO8zW--ea5GvC98jfwGByrt6lXz9VUy6jWTMntX0cpkbF7-3mrp5fBsQyMw>



Hi trystant, Watch now dogweather on Livecoding.tv!


Join stream
<http://email.mg.livecoding.tv/c/eJxVzTsOwyAURNHVQImABzgUFGmyD_4gGxNh4mw_tJGmOc3cYCIkoXA1nDJJNWOcSc45YctApFRKIUFbJke9o--hnpnMGxeTKASxebBUpwdoLUIE6p3V4FJKbsOHKXO-LwRPxF9rfwfLoedvtLPEsYCHaXbsK5WHPcM-PsT39gPPETAr>




You can stop notification e-mail alerts on your dashboard.
<http://email.mg.livecoding.tv/c/eJxVjrsOwyAUQ78mjIhHgGRg6NL_ILyCkkAFt5H6970dK9mSjwfLwUaZZk2KFYwrtnIuuBJCUI4sqVJa62lmV6ZnuaNvodRM4Sa73Qxzi_cmGZmC08vqnY8LejWJ6biR0-4ArzHJxySeqL8BZOifAa4CxhEBsB8Ya4OSindQWv0x6fZy_cAPubsajv6mvl1fWmc6Rg>

Read this blog article on how the channel and category notification works.
<http://email.mg.livecoding.tv/c/eJxdjkkOwyAMRU8TdkFghoYFi256DwIkQWWICM35624rWc_6Xx5-sFFsUpNkgXHFDOfAFQBQjlpQpbTWk2Rlpznd0beQ6k7HTQ67LJs3Yg1BPQzIAMIthrngQDK9eh9ItscY5ySeE7yw1tz-jqD5e4qNaQTniBzHNV-jnYgeXZlrG2lL3o3U6nydrhRcxkHSbXH9jdn27mp49w_1rXwBCFE_sQ>

[image: RSS Feed]
<http://email.mg.livecoding.tv/c/eJxFjTsOwyAQRE8DJTILS-yCIlLkewALtuUPFiH29UOqSNPM0-gN2aiSNnyx0EnsBilBIgAI2boSiMYYprt9EttyxZBpOSZRLz5bklorpIQ-Yq8HRz3pHkN6SBiS8Z5vdq71fDP1ZDC23PctkgvR57yKkPeG_s56MTWWmJh6zRsvdndlbb9TcQet5fPbfwFDwjRk>
[image:
Twitter]
<http://email.mg.livecoding.tv/c/eJxFjTsOwyAQRE8DJWKXBdkFRZrcw-FnZGNHhDjXz6aKNM2TZt5En0wmJ6tHDVbPAAgWERUwG2Wtc06QbkXt9UrhjPUoalxy9WT0bCYKOgfCFDJNlAFjdPRIjsdy9-sYz5cwN4F3zvjUMVJX4WxMfx3bum9L3_in9OWIW3__Sl8QWS7m>
[image:
Livecoding.tv blog]
<http://email.mg.livecoding.tv/c/eJxdzDkOwyAQQNHTQIlgWGIKijS-B2MWI4OJEPH5Qx3pN795wUWZlKHFAReaWyFAaABgYr1kWhtjiOIts1qeePRQ7szmQ08XkrK4CaUsoEwvvxlI1hvUGHiIiLS6c84PkW8C-wpr_0eGa35ci8_D3-EaX3b09gOjFCwk>

Livecoding.tv (LiveEdu, Inc.)
<http://email.mg.livecoding.tv/c/eJxVzDkOwyAQQNHTmBLNDItDQZEm92A3srEjQnz-0Eb6zWt-tElkqVm1BKjAIBIqIuI4LbhSWutFQiv8qHcKV6xn4eNmmyUt1WrQPEB4Ag_Gi5DSKrNDI73I7LDbGO_PIp4LvWZ_g2nWbXN9n_fS3Rn3_uXhaj8qqSps>
100 North Whisman Road, Mountain View, CA 94043
<http://email.mg.livecoding.tv/c/eJxVjcEKwyAQRL9Gj7K7uooHD730PzSJiSQmxZp8f70WBoYHj5k5LDobK0sgQAaPSMhEpHCwVszWWmGgruoozzJdczlX1R-5Dd8h5wkoWZMB_ILsUgLvNETO0ckjbL1_vkK_BL1H_gYGx3TdfbRsoca2j5e1xXPe262mq_4AifctFA>

**Comment by rlgreen91** [comment]
@trystant @campgurus did we decide not to handle pictures this way, or does it still need to be implemented?

**Comment by trystant** [comment]
I don't think we came to a decision on this.  Right now, cases and organizations have an avatar; I think that subjects should be able to have avatars as well.  I've changed the subject to reflect that.

**Comment by rlgreen91** [comment]
Hmm, I think we want both - cases can have photos that aren't related to the subject.  A photo of the subject vs a photo of the scene, if you will.  I think it goes back to what I said about having images for cases and agencies.

**Comment by rlgreen91** [comment]
So, I think this issue and comments were created pre-ActiveStorage.  Given that, I would say that this is no longer applicable - we are planning to have the ability to add photos for cases, agencies, etc but since it's through ActiveStorage the discussion around avatars will no longer apply.  Going to close this one - when we get to ActiveStorage we can create new issues to talk about that work.
