### ISSUE TITLE
Fix strong parameters in messages controller

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2116]
In the messages controller, use strong parameters in a uniform way.  Use `message_params[:recipients]`, and when calling the message params for body and subject, access them without `message` first - as `message_params[:body]` and `message_params[:subject]`.

Add a new file `messages_features_spec.rb`, and add a feature spec for sending a message to another user.

**Comment by gpks** [comment]
I would like to take that!
