### ISSUE TITLE
Unable to add agency to new case

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#2184]
I was able to add it via the Edit action.

In the new form I got this error:
<img width="834" alt="screen shot 2018-08-24 at 9 24 43 pm" src="https://user-images.githubusercontent.com/1260659/44613659-92ad1980-a7e4-11e8-8703-0f874765f1fd.png">

**Comment by rlgreen91** [comment]
Can you reproduce this @campgurus?  Does this happen with other agencies, or just this one? Can you provide more detail about the case you were adding?  It could be that this particularly agency is now invalid somehow.

**Comment by rlgreen91** [comment]
I definitely still need more info on this.
