### ISSUE TITLE
Add Sumome to ebwiki.org

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#226]
Following traffic1m instructions

**Comment by trystant** [comment]
It was an Appsumo [package](https://sumo.com/). useful for analytics & site maintenance. Those tools still could be useful

**Comment by trystant** [comment]
At this point not much, out of all the SEO & marketing tools we've put into place, we've got very little traction out of them. This came out a company that promoted practices to get a site to 1 million users.

I am not opposed to spending time on Marketing, but just as we can't do scattershot development & see what sticks, we can't do scattershot marketing either. Let's close this for now.
