### ISSUE TITLE
Prioritize M/F/T under Genders list

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#2269]
Here is the current Gender dropdow in the cases/_form:

<img width="207" alt="screen shot 2018-08-28 at 6 41 36 am" src="https://user-images.githubusercontent.com/1260659/44718401-eee69680-aa8d-11e8-9664-40205cd55563.png">

To avoid unnecessary confusion, can we go back to having Male, Female and Trans (which will encompass the vast majority of cases in the db) as the top options for choosing gender of victims?

**Comment by rlgreen91** [comment]
We're going to move this model over to an enum in a couple of weeks, so I'm closing this issue.
