### ISSUE TITLE
Create a guest object

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2275]
Create a file `app/null_objects/guest.rb`, and in it create a class `NullObjects::Guest` that includes a method `name`.  The `name` method should return 'Guest'.

**Comment by Marijunjnja** [comment]
I would like to work on this. To clarify, the directory null_objects does not currently exist, so it would need to be created?

**Comment by Atul9** [comment]
@rlgreen91 I have opened up a PR for this #2342
