### ISSUE TITLE
Black/Hispanic

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#229]
So far, we have basically distinguished between black and hispanic on the basis of surnames. However, maybe we should specify black hispanic vs white hispanic somehow, since race/color may be more probative than language when it comes to these cases.

**Comment by trystant** [comment]
If a person is Hispanic and white, are they not considered a person of Color for EBWiki?

**Comment by campgurus** [comment]
Right now they are, since we are just using surnames, but what do you think?

**Comment by trystant** [comment]
I think that for now we should keep it to hispanic, and roll this into an ethniciries do-over.
