### ISSUE TITLE
ahoy duplicate key error on local

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#23]
in the log:

PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "ahoy_events_pkey"
DETAIL:  Key (id)=(deac5650-58c5-43a3-85e9-4794474a1ddf) already exists.
: INSERT INTO "ahoy_events" ("id", "visit_id", "user_id", "name", "properties", "time") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "ahoy_events_pkey"
DETAIL:  Key (id)=(79443230-08a5-45cc-a42d-5ede3ba30f9c) already exists.
: INSERT INTO "ahoy_events" ("id", "visit_id", "user_id", "name", "properties", "time") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"

**Comment by campgurus** [comment]
Need to replicate this issue.

**Comment by trystant** [comment]
This hasn't been an issue for a long time.
