### ISSUE TITLE
Remove presence check from show action

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2376]
In the cases controller, remove the conditional `@comment.present?` and `@subjects.present?` in the `show` action.  We assign that variable to a new instance of `Comment` above, so it's guaranteed to be present.  We also have a presence requirement for subjects and cases, so that's guaranteed to be present as well.

**Comment by Atul9** [comment]
@rlgreen91 I have opened up a PR for this #2400
