### ISSUE TITLE
Create dev S3 bucket

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2385]
Let's see if there's a way to create a public S3 bucket and a corresponding IAM user and policy that only allows access to that specific bucket.  We could then have the credentials in the .env file, and that would reduce one of the requirements for installation locally.

**Comment by trystant** [comment]
We generally want to avoid credentials in the codebase, but could create an
IAM user with very strict permissions.

**Comment by rlgreen91** [comment]
I know but this would remove a hurdle during setup.

**Comment by trystant** [comment]
I hear you and am thinking of best case scenario path to proceed upon.

**Comment by rlgreen91** [comment]
Hi L.P.,

Unfortunately, I can no longer see this message on the issue.  However, if
you look at our set up guidelines, it explains what you need to do to avoid
these errors.

Regards,

Rachel

**Comment by leosoaivan** [comment]
My apologies, the issue was premature. I deleted my question after finding the setup guidelines, which I had missed the first time :). Thank you for checking in, though.

**Comment by trystant** [comment]
I've been thinking this through and I don't think the default bucket is a feasible solution.  I can't think of a safe way to implement that. I think that time would be better spent working toward the container builds for developers.
