### ISSUE TITLE
Create a rake task to set the values of comments in versions table

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2406]
Create a rake task that will search the versions table, grab all records for which the `comment` column is `nil`, and set the value to an empty string.  There's a rake task to add a blurb field to cases that you can use as a model of what to do here.

**Comment by asarbu** [comment]
I can work on this :)

**Comment by yifeiwu** [comment]
Why not make this a migration to set the db default? That way you won't need to rerun the rake task.

**Comment by rlgreen91** [comment]
@yifeiwu sorry, just now seeing your comment.  The issue is that because the table already exists, setting the default will only be applied to rows added after the migration is run, not before.  So we still need a way to update the existing records with the default.
