### ISSUE TITLE
Move the "get newsletter" button to the header

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2407]
Remove the "get newsletter" button from the homepage and add the link to the header.  Move "Add a New Case" to the left closer to the search bar and then put "Get Newsletter" in between that and the drop down.

**Comment by juanmanuelramallo** [comment]
I'd like to take this

**Comment by rlgreen91** [comment]
@juanmanuelramallo that's fine.

**Comment by RickArora** [comment]
Can you show me a picture of exactly what you would like and then assign it to me?

**Comment by rlgreen91** [comment]
Hi @RickArora, unfortunately, we don't have a picture - you just need to move the button between the "Add a New Case" text and the dropdown menu on the right

**Comment by carloslazo** [comment]
I'll take this on. Assigned to myself.
