### ISSUE TITLE
Return an empty array if there are no nearby cases

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2428]
In the case model, change the `nearby_cases` method to return either the result of the query or an empty array.  Additionally, there is no reason to use `try` for the sorting, just state that the order should be by distance.

**Comment by rlgreen91** [comment]
Actually, we don't even need to do that - just make the method calls normal, rather than invoking them using `try`.  So, altogether something like `case.nearby.order`

**Comment by rlgreen91** [comment]
I see.  So, in this case, do what I set above - either try to get the nearby cases and order them, or return an empty array.

**Comment by ozmar-11** [comment]
I would like to take this one, just a question, you would like to get a simple Array or a Case.none?
