### ISSUE TITLE
Add database constraint for unique names for agencies

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2445]
Add a database constraint to the agencies table that names must be unique

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , isn't the uniqueness validation enough?

**Comment by rlgreen91** [comment]
Not always. [This article](https://robots.thoughtbot.com/the-perils-of-uniqueness-validations) does a good job of explaining how you can end up with two people sending "unique" data that actually violates the validations we have.  It's better to have the database constraint back this up.

**Comment by ztmeyer** [comment]
If no one's working on this I can pitch in

**Comment by rlgreen91** [comment]
@ztmeyer If you do take this issue, then please be sure to assign it to yourself.  That's how we expect people to verify whether an issue is taken.
