### ISSUE TITLE
Add database constraint for cases and cities

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2446]
Add a database constraint that requires the city column for cases to not be nil.

**Comment by Paarmita** [comment]
@rlgreen91 I want to take this up. So I need to add a constraint for cases that it should not be nil and requires city column?

**Comment by rlgreen91** [comment]
@Paarmita Yes, that's what you'd need to do.  If you decide to work on this, please assign the issue to yourself so others won't work on this as well.

**Comment by asarbu** [comment]
@rlgreen91 is somebody working on this ? If not I can start working right now. Please assign me to the issue if needed.
