### ISSUE TITLE
Add database constraint between cases and subjects

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2454]
Add a migration that removes the foreign key between cases and subjects, and then re-adds the foreign key with the option `on_delete: :cascade`.  Then, in the case model, remove the option `dependent: :destroy` from the subjects association

**Comment by asarbu** [comment]
@rlgreen91 I added a MR for this issue.

I couldn't find any existing foreign key for the relation you mentioned, therefore I didn't have to remove anything. In case I missed it let me know and I'll update the PR.

**Comment by rlgreen91** [comment]
That's bizarre.  Either way this was good to go.
