### ISSUE TITLE
Set up meta tag generation

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2459]
Set up the structure of meta tag generation based on this article: https://www.lewagon.com/blog/setup-meta-tags-rails.

Follow all of the steps until adding code to the views.  In your .env file, set the host variable equal to localhost.

**Comment by rlgreen91** [comment]
Either one of you can take it, I would just prefer for it to be done by Wednesday.

**Comment by campgurus** [comment]
Checking in on the status of this. I want to start posting case links to Twitter soon, which will help for SEO.
