### ISSUE TITLE
Automate use of metadata for Case.links urls

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#2487]
There are a couple gems that will perform this function and eliminate the need to add a second field for each link.  This one appears to be updated recently: https://github.com/jaimeiniesta/metainspector

**Comment by rlgreen91** [comment]
I don't know that we should go this route.  We're already working on allowing users to insert the title used on the webpage, albeit via Javascript before the form is submitted.  However, by doing so, we allow the user to change the title if they wish - doing it using this gem would remove that option.  I'm not a fan of decreasing user choice and adding an unnecessary dependency in this case.

**Comment by campgurus** [comment]
Ok. I think editors having options is good. I just want the default title to populate without any effort by the editor unless they choose to change it.

**Comment by rlgreen91** [comment]
Given that there is already an issue aimed at this I will close this one.
