### ISSUE TITLE
Implement Accelerated Mobile Pages (AMP)

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#2488]
Google's Accelerated Mobile Pages may speed up our page load times significantly and as a result decrease our bounce rate further. Google also apparently favors these pages in search results. All three of these will improve our SEO and could potentially increase traffic to the site substantially.

Here is an example of how to implement this in RoR:

https://andycroll.com/ruby/amp-project-pages-ruby-on-rails/

**Comment by rlgreen91** [comment]
As I mentioned in the Slack, I'm pretty against this.   I'll post the article I linked to [here](https://medium.com/@danbuben/why-amp-is-bad-for-your-site-and-for-the-web-e4d060a4ff31), but chief among my concerns is that the user is never actually routed to our site, but instead consumes our content while never leaving Google.
