### ISSUE TITLE
Set Summary to nil in cases#edit action

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#2490]
<img width="1262" alt="screen shot 2018-10-11 at 4 18 55 am" src="https://user-images.githubusercontent.com/1260659/46790409-db754f00-cd0c-11e8-98de-acf75db4fbc3.png">

This line should not have been removed from the controller. As a result, the summary field is filled in when the editor starts and the editor does not have to affirmatively add a summary to the new version, so we could end up with many versions with the same summary. Please put this back.

**Comment by StlMaris123** [comment]
Hi @campgurus , I had removed it because I had added a database constraint preventing summary from being null. When i return that line i get ` PG::NotNullViolation: ERROR:  null value in column "summary" violates not-null constraint`. Should i remove that constraint. I was trying to look around for means to hold the constraint only one create but not update but could not find any.

**Comment by rlgreen91** [comment]
No, this is the change you should make @StlMaris123 - in the form itself, change the line to say:

```
<%= f.input :summary, as: :text, value: nil %>
```

**Comment by campgurus** [comment]
This solution is not working.

**Comment by campgurus** [comment]
The following works to clear the form, but messes up the size of the text area which does not seem to change size based onthe row and col inputs:

`<%= f.text_area :summary, :input_html => { 'rows' => 5, 'cols' => 100 }, value: nil  %>`

**Comment by campgurus** [comment]
this works:

`<%= f.input :summary, :input_html => { :value => nil }, value: nil  %>`

**Comment by StlMaris123** [comment]
@rlgreen91 , should we remove the not null constraint for summary in cases from the db?

**Comment by rlgreen91** [comment]
No, the constraint still needs to be in the database.  We just need to update the form.

**Comment by StlMaris123** [comment]
I will re-look at this

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , @campgurus , can we close this issue since its already implemented?
