### ISSUE TITLE
Update analytics route

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2492]
In `routes.rb`, update the analytics route to be the following:

```
get '/analytics', to: "analytics#index"
```

You may need to update the corresponding tests.

**Comment by tudorpavel** [comment]
@rlgreen91 PR submitted. I'm guessing aws secrets for travis can't be fetched on a forked repo build.

Happy Hacktoberfest!

**Comment by rlgreen91** [comment]
Yes, they can't.  We usually ask people to let us know if they want to be added as collaborators if we can't catch them via PR.  Thanks for your contribution!
