### ISSUE TITLE
Use env variable for sitemap route

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2494]
Add an env variable that maps `EBWIKI_SITEMAP_URL` to 'http://bow-sitemaps.s3.amazonaws.com/sitemaps/sitemap.xml.gz'.  Then, in the routes file, replace that URL in the sitemap line with `ENV.fetch(EBWIKI_SITEMAP_URL)`.  Finally, update the set up docs to include this new environment variable.

**Comment by juanmanuelramallo** [comment]
I'd like to take this

**Comment by carloslazo** [comment]
I think this should be added in the SETUP_LOCALLY.md or at least mention to check the .env.example file. I can do it if needed.
