### ISSUE TITLE
Install paper_trail association gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2550]
Add and install the `paper_trail-association_tracking` gem based on the instructions here: https://github.com/westonganger/paper_trail-association_tracking#install.

Please add a comment in the Gemfile that this gem is needed for paper_trail to track changes done via rails_admin views.

**Comment by jessecalton** [comment]
Submitted PR here: https://github.com/EBWiki/EBWiki/pull/2573

**Comment by Aguardientico** [comment]
Submitted [PR](https://github.com/EBWiki/EBWiki/pull/2643) Travis needs AWS credentials to be able to run
