### ISSUE TITLE
Run migration to confirm user email adresses

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2631]
Add and run the following migration to add confirmation details to the user model:

```
class AddConfirmableToDevise < ActiveRecord::Migration
  def change
    add_column :users, :confirmation_token, :string
    add_column :users, :confirmed_at, :datetime
    add_column :users, :confirmation_sent_at, :datetime
    add_index :users, :confirmation_token, unique: true
  end
end
```

**Comment by ArthurNovaes** [comment]
@rlgreen91 It's only create and run this migration? And create PR after?

**Comment by BGRicker** [comment]
I mentioned in the PR, but the migration looks a bit different as referenced from the official Devise guides: https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users

**Comment by rlgreen91** [comment]
Yes, I know it looks different, that's on purpose.  And yes, just create and run this migration, although it looks like you've been beaten to the punch.  We have some more Hacktoberfest tickets open, so feel free to take a look at those as well.  Thanks for your contribution!

**Comment by BGRicker** [comment]
updated the PR to reflect the exact migration! Thanks for the note on it needing to be the exact migration

**Comment by StlMaris123** [comment]
Hi @rlgreen91 , am not seeing any pr referencing this issue. Has it been solved yet?

**Comment by BGRicker** [comment]
Hi @StlMaris123, the issue was referenced here back in October on PR #2636, not maybe I messed up and missed a step to close the issue

**Comment by rlgreen91** [comment]
Sorry, meant to close this earlier.
