### ISSUE TITLE
Delete unused methods from application controller

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#2639]
In the application controller, delete the methods `mailbox` and `conversations`.

**Comment by Anne97** [comment]
Can I take this up?

**Comment by rlgreen91** [comment]
Sure

**Comment by Anne97** [comment]
Hi, I have been facing issues while pushing. 
`ERROR: Permission to EBWiki/EBWiki.git denied to Anne97.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.`
I checked for SSH keys and even added a new one. Could you please help me with this if it's a known issue?

**Comment by geektimus** [comment]
Hi Anne, You need to create a fork of this repo and then push your changes to the fork, then you can create a PR to the original repo.
You are getting this permission denied because you don't have _push permissions_ on this repo.

**Comment by Anne97** [comment]
Thanks a lot! I'll try that now

**Comment by rlgreen91** [comment]
Ah, the PR we merged was #2658
