### ISSUE TITLE
Rubocop returns offenses

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#2679]
`rubocop -a` returns:

`180 files inspected, 117 offenses detected, 2 offenses corrected`

We should:
- [ ] Get this down to 0 offenses
- [ ] Maintain those lack of offenses

**Comment by trystant** [comment]
Got this down to `1174 files inspected, 101 offenses detected`

**Comment by trystant** [comment]
Got this down to `173 files inspected, 88 offenses detected`

**Comment by trystant** [comment]
Removed a few more offenses `173 files inspected, 84 offenses detected` . Some of the remaining offenses may require some significant refactoring. I will likely create new tickets for those.

**Comment by StlMaris123** [comment]
Cool. Waiting for the tickets

**Comment by trystant** [comment]
Here's a status update`184 files inspected, 92 offenses detected`

**Comment by rlgreen91** [comment]
TBH, I would much rather split this up into issues that tackle this in parts. So, for example, having an issue to address Rubocop errors by domain (case, agency, etc) or by layer.  That makes it easier to track in terms of completion and then we can have people work on this for Hacktoberfest.  Thoughts @trystant ?

**Comment by trystant** [comment]
@rlgreen91 This makes sense. It also leaves room to discuss why these changes need to be made, or in some cases, why they do **not** need to be made.
