### ISSUE TITLE
case form subject fields partial not pulling in ethnicities

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#2721]
I don't see @ethnicities defined in the controller, so maybe that is it, but that doesn't appear to be a recent change. 

In the meantime, the form expects direct entry of ethnicity_id in the form of an integer. screen shot below.
<img width="857" alt="screen shot 2018-12-07 at 7 05 50 am" src="https://user-images.githubusercontent.com/1260659/49647120-6f9f2200-f9ef-11e8-97c7-e335523c7950.png">

**Comment by trystant** [comment]
Also, this refactoring may also not prevent the regression on the variables that happens from time to time.

**Comment by trystant** [comment]
This has been fixed.
