### ISSUE TITLE
Add shortcut icons to index page

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#295]
Icons should signify whether a case involves mental illness, unarmed victims, whether we have a video embed etc. Icons should link to results pages that return only the articles with those characteristics. 

Initially, I am thinking we would superimpose these icons on top of the large images on the index page, however, if the number of icons becomes unworkable, we may have to increase the white space beteen the images and use that space for icons.

**Comment by rlgreen91** [comment]
@campgurus @trystant can we confirm here that we don't want to do this?

**Comment by campgurus** [comment]
I still think it is a good idea to have some quick info about the case up front. eg, i think a user should know if there is a video attached to a case without having to click through to the page.

**Comment by trystant** [comment]
I'm not sure how those icons would work with our current UI.  Until we can get a mockup of how this would look, I'm inclined to close this ticket.
