### ISSUE TITLE
Date filter on case create requires today's date

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#3089]
Somehow, when creating a case the date filter is required to be the present date. 
![Screenshot 2019-07-13 at 21 53 33](https://user-images.githubusercontent.com/13509/61179518-f8e78a00-a5b8-11e9-9af1-18a0362a347b.png)

This is keeping people from creating cases.

**Comment by rlgreen91** [comment]
Note that this doesn't require today's date - I have had success adding cases that occurred outside of 2019.

**Comment by trystant** [comment]
@rlgreen91 Which date parameters did work for you? It would be helpful to narrow down what is happening.

**Comment by rlgreen91** [comment]
@trystant I was able to submit a case yesterday with a date of 1/26/2016 I believe.  Somewhere around the end of January/beginning of February of 2016 for sure.

**Comment by campgurus** [comment]
this error is so crazy. I tried to add a photo to the latest case this
morning and got a slightly different error wrt date attribute.

Something like,  "Date must be in the past. .."

**Comment by rlgreen91** [comment]
Fixed in #3132
