### ISSUE TITLE
unable to update image: $ is not defined error in console

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#3195]
When trying to edit a case's image by clicking on the "BROWSE" button, no dialog box appears and a "$ is not defined" message appears on the console, indicating that jQuery hasn't been loaded.
![Screenshot 2019-09-25 at 03 23 11](https://user-images.githubusercontent.com/13509/65578544-f81d8d80-df43-11e9-9f0b-63f167ee379d.png)

**Comment by rlgreen91** [comment]
Possible fix: https://stackoverflow.com/questions/29327004/uncaught-referenceerror-is-not-defined-rails

**Comment by rlgreen91** [comment]
Are you working on this @trystant?  If so, please self-assign

**Comment by rlgreen91** [comment]
Technically this was addressed in #3353
