### ISSUE TITLE
move error, flash, mailer & static content to locale files

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#3196]
There's a fair amount of static content that could/should be within locale files and referenced in code. It'll reduce the amount of content in code.

**Comment by rlgreen91** [comment]
@trystant can you expand on this more?  I would like to include this as part of Hacktoberfest but we'll need to be explicit on what would allow this issue to be marked as complete.

**Comment by trystant** [comment]
Sure. The messages we display in the flash upon success and error are constants in code. One of the reasons Rubocop complains about lines being too long in files like  user_notifier.rb is due to a practice of moving  text to a locale file. I will post a commit with an example shortly

**Comment by trystant** [comment]
I created a new specific issue #3204 and connected it to #2679 in the comments for that issue.  We can close this issue. I'm inclined to make this a milestone, since it will take multiple tickets to finish this. Thoughts @rlgreen91 ?

**Comment by rlgreen91** [comment]
We can, that'll ultimately be up to you.
