### ISSUE TITLE
Create password confirmation mailer

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3202]
In `UserNotifier`, create a method `send_confirmation_email` that, when triggered, will use the existing mailer in `app/views/devise/confirmations/new.html.erb`.  Additionally, add some copy in that mailer - something along the lines of "Thanks for signing up for EBWiki, click here to confirm your account."

**Comment by sudhir512kj** [comment]
@rlgreen91 I would like to work on it.

**Comment by rlgreen91** [comment]
Addressed in #3210
