### ISSUE TITLE
Travis builds failing for non organization users

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#3221]
As a result, people aren't able to see their results on Travis. I think that encrypting variables may help.

**Comment by rlgreen91** [comment]
Sounds like a good option to me.  For some reason, Travis won't create org-level environment variables like Code Climate has, despite a very detailed issue in their repo asking them to.

**Comment by trystant** [comment]
I tried this but it wasn't successful. I think that a better solution is to just invite the user to the organization.
