### ISSUE TITLE
Use Devise confirmation mailer

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3293]
Remove the confirmation email action and template from UserNotifier.  Add a file `spec/mailers/devise/confirmation_spec.rb` and model the spec after the example included in this: [Ruby Thursday guide](https://rubythursday.com/system/episodes/pdfs/000/000/069/original/Ruby_Snack_30_Testing_Devise_Mailers.pdf?1464299925).  Add a mailer preview by following this guide: [mailer preview](https://ionrails.com/2014/12/21/using-actionmailerpreview-with-devise-mailers-in-rails-4-1/)

**Comment by k-stewart** [comment]
Hi team, I'd like to take a crack at this.

**Comment by k-stewart** [comment]
Looks like the model is UserMailer, not UserNotifier, does that sound right?  I see references to UserNotifier in the docs, but its methods are defined in app/mailers/user_mailer.rb.

**Comment by k-stewart** [comment]
Ah, i see, it was changed in a157d8ec64379bc0b57b37f0df71d9e1a0e47eba.  I can update the docs while i'm in here.

**Comment by k-stewart** [comment]
Hmm, it looks like the docs [used to have the accurate model name](https://github.com/EBWiki/EBWiki/commit/72af37e08575a18c7a304352979e316b40689cd2),  and that was undone.  I'll leave it alone, then.

**Comment by rlgreen91** [comment]
Addressed in #3371
