### ISSUE TITLE
Create a remove_admin_email action

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3311]
In `AdminMailer`, create a new action and view called `remove_admin_email` that will notify recipients that the corresponding user is no longer an admin.  Then update the `SendAdminEmail` service object to call `send_admin_email` if a user's admin attribute is changed.

**Comment by carloslazo** [comment]
I can take this on. I assigned it to myself.

**Comment by rlgreen91** [comment]
Addressed in #3372
