### ISSUE TITLE
Create location value object

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3313]
Create an object `Location` that is a value object like `DateRange` (located in `app/models`).  The `Location` object should take in a required parameter state and optional parameters street location, city, and zipcode.  The street location should encompass house number, street name and type, apartment number, and direction (e.g., 124 West Avenue Suite #350 NW would be the street location).

The object should also define a `to_s` method that returns the concatenated parameters in order as well as a `==` method which returns true if all of the parameters have the same value in both objects.

**Comment by sathia27** [comment]
@rlgreen91 I would like to pick this up.
