### ISSUE TITLE
Add location object to Agency and Organization models

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3389]
Add the location object to the `agency` and `organization` models.  You can use the date range and address examples in [this guide](https://revs.runtime-revolution.com/value-objects-in-ruby-on-rails-9df64bc8db34) as examples of how the model code should look.

**Comment by jm96441n** [comment]
Does this still need to be addressed? I'm interested in contributing and thought this looked like a good issue to start on

**Comment by rlgreen91** [comment]
Hi @jm96441n - sorry for the delayed response!  Yes, feel free to pick it up if you'd like.

**Comment by Xeitor** [comment]
Hello, can I work on this issue?

**Comment by danielvdao** [comment]
Hi @rlgreen91, I think I may have tried a pass at this. Please let me know if it's not relevant anymore: https://github.com/EBWiki/EBWiki/pull/3973. I looked at this a week or two ago and this was one of the first open issues I saw. Turns out there's more now 🙂 .

**Comment by rlgreen91** [comment]
Thanks @danielvdao - I took a look just now.

**Comment by rlgreen91** [comment]
Merged
