### ISSUE TITLE
Add button/link to articles/index on show pages

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#341]
Most visitors to EBW land on a case show page.  There is no logical way to get to the main index page from there.

We should add a button link for that purpose.

**Comment by rlgreen91** [comment]
Do you mean a button other than the logo?  And no, it shouldn't be a link.

**Comment by campgurus** [comment]
I meant a button in addition to the logo. To me, it might not be clear to a new user that the logo links to the front page.

**Comment by rlgreen91** [comment]
That is actually a standard UX pattern for web apps - for most users, it's going to be second nature that clicking the logo takes you to the landing page.  The only people it won't be for are the small segment that is new to the internet in general.  We could do some A/B testing for having a button in addition to the logo, but I don't expect it to increase clicks.

**Comment by rlgreen91** [comment]
I'm going to go ahead and close this, since there's not really an action to take.
