### ISSUE TITLE
Install Twitter and VCR gems

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3417]
Install the Twitter and VCR gems.  The VCR gem should be in the `:test` group, but the Twitter gem should not.  Be sure to specify the major and minor version.

**Comment by PacoLuna1** [comment]
@rlgreen91 can I try it?

**Comment by rlgreen91** [comment]
Sure.  There's not really a request system in place - first PR wins.

**Comment by theparselmouth** [comment]
I have made the required changes in gemfile and gemfile.lock but the travis CI build fails due to missing AWS auth params. Is this an error on my end ?

**Comment by PacoLuna1** [comment]
I didn't have that problem here is my pull request #3422

**Comment by theparselmouth** [comment]
PacoLuna1, the Travis CI build failed for you too. If you check out the details for why it failed, it says the same thing for you as well I believe. Could you check ?

**Comment by PacoLuna1** [comment]
yes, so sad :(

**Comment by theparselmouth** [comment]
Yeah i guess it is something they need to fix

**Comment by rlgreen91** [comment]
Sorry @PacoLuna1, it looks like @theparselmouth just beat you to it.  The issue with Travis is due to how it handles environment variables for PRs submitted from forks - it's not something any of us can change.  I believe Mark is inviting everyone to the organization so, if you join, you'll be able to submit a PR from a branch within the repo and avoid that issue with Travis.

Thanks to both of you for working on this.  If you're still interested, we still have more issues labelled Hacktoberfest
