### ISSUE TITLE
Change back button on edit form for cases and agencies

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3429]
Currently, when editing a case, the form includes a "back to home" button that redirects the user to the homepage.  This should be changed to a "back" button that redirects the user back to the case page.

A similar "back" button should be added to the edit view of the agency model.

**Comment by yesi-aracawa** [comment]
Hi, I'd like to work on this!, can I try?

**Comment by rlgreen91** [comment]
Hi @yesi-aracawa - I'm sorry I missed your comment!  Issues tend to be first come first serve in terms of submitting a PR.  If you're interesting in participating for Hacktoberfest, we do still have other issues under that label.

**Comment by rlgreen91** [comment]
Addressed in #3464
