### ISSUE TITLE
Removing unneeded files from codebase

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#3430]
There are a number of files that are in the distro but aren't needed. These include:
* `coffeelint.json`, which is used to evaluate CoffeeScript, which we don't use.
* `README.rdoc`, which is empty.
* `.byebug_history` which is also empty
* `.floorc` - Floobits config
* `.floorc.json` Ibid
* Vagrantfile. We're off Vagrant and on Docker

**Comment by rlgreen91** [comment]
Addressed in #3432
