### ISSUE TITLE
Upon Unsuccessful Sign Up/ In I should get an error messge

### ISSUE THREAD

**Issue by StlMaris123** [EBWiki/EBWiki#3469]
I created an account and then tried to Log In. On both attempts I was redirected to the home page without any error message or an update on what is going on.

**Comment by trystant** [comment]
This is happening due to an AuthenticityToken error. We do need to add better error messaging for what is occurring. This is a side effect of moving up to Rails 5.

**Comment by trystant** [comment]
This has been fixed
![Screenshot 2020-06-16 at 08 28 46](https://user-images.githubusercontent.com/13509/84774249-8989cf80-afab-11ea-9561-800437a2f132.png)
