### ISSUE TITLE
Make name the initially focused field on user signup

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#3489]
The current home page focuses on the email field when it loads.  It should focus on the "Name" field instead.
![Screenshot 2019-11-10 at 20 50 21](https://user-images.githubusercontent.com/13509/68555457-e0b73880-03fb-11ea-9a04-b74348d400a0.png)

**Comment by trystant** [comment]
I'm going to make this a PR and open it for review.

**Comment by rlgreen91** [comment]
@trystant Can you give that page some love in terms of styling as well?  Align the checkbox, then add spacing between the last four elements.

**Comment by MohamedAsan** [comment]
I am willing to take this up! Kindly assign to me

**Comment by MohamedAsan** [comment]
Have removed the login related links at the bottom as well
<img width="838" alt="Screenshot 2020-10-02 at 8 25 53 PM" src="https://user-images.githubusercontent.com/29650842/94937656-7dd7ff80-04ed-11eb-9265-291e0f6abe58.png">
