### ISSUE TITLE
Use devise routing to allow autocomplete actions after required logins

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#353]
We can learn from the authentication method in #183. In that instance devise automatically redireted admin users to split after they were prompted to login.

We can presumably do the same for following.  Currently, I believe we lose followers when they have to start the following process over after creating a new user as required.

**Comment by campgurus** [comment]
examples:

https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update

**Comment by rlgreen91** [comment]
I'm going to close this as we'll need several issues to cover making these changes for the different controllers.
