### ISSUE TITLE
Fix admin dropdown on homepage

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#3559]
When using the nav bar to dropdown on the homepage of EBWiki
![Screenshot 2020-02-11 at 00 13 34](https://user-images.githubusercontent.com/13509/74213479-62bb3580-4c67-11ea-86fc-328425040dd9.png)

The background should be opaque on the full size, just as it does on mobile.

**Comment by trystant** [comment]
It looks like this is occurring for ipad and wider layouts. I'm investigating the difference in CSS, looking for the property or set of properties that is contributing to this header problem.

**Comment by rlgreen91** [comment]
This has been addressed in PR #3628
