### ISSUE TITLE
no method error when trying to create a new article

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#36]
I get 

undefined method `order' for nil:NilClass

def nearby_cases
        self.nearbys(50).order("distance")
    end

trace:

app/models/article.rb:42:in `nearby_cases'
app/controllers/articles_controller.rb:41:in`show'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in`process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in`block in process_action'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in`call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in`call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in`_run_callbacks'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in`run_callbacks'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in`process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in`block in instrument'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in`instrument'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in`process_action'
.bundle/gems/ruby/2.2.0/gems/searchkick-0.8.7/lib/searchkick/logging.rb:107:in `process_action'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in`process_action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in`process'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in`dispatch'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in`call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in`serve'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in`each'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in`call'
.bundle/gems/ruby/2.2.0/gems/rack-pjax-0.8.0/lib/rack/pjax.rb:12:in `call'
.bundle/gems/ruby/2.2.0/gems/oink-0.10.1/lib/oink/middleware.rb:17:in`call'
.bundle/gems/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
.bundle/gems/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in`catch'
.bundle/gems/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.0/lib/rack/etag.rb:24:in`call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.0/lib/rack/conditionalget.rb:25:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.0/lib/rack/head.rb:13:in`call'
.bundle/gems/ruby/2.2.0/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27:in`call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in`context'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in`call'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/query_cache.rb:36:in `call'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in`call'
.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:378:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in`_run_callbacks'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in`run_callbacks'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:73:in`call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in`call'
.bundle/gems/ruby/2.2.0/gems/web-console-2.1.2/lib/web_console/middleware.rb:37:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
.bundle/gems/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
.bundle/gems/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in`block in call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in`tagged'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
.bundle/gems/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in`call'
.bundle/gems/ruby/2.2.0/gems/ahoy_matey-1.1.1/lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
.bundle/gems/ruby/2.2.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in`call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in`call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.0/lib/rack/lock.rb:17:in `call'
.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in`call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
.bundle/gems/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in`call'
.bundle/gems/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
.bundle/gems/ruby/2.2.0/gems/rack-1.6.0/lib/rack/content_length.rb:15:in`call'
.bundle/gems/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:507:in `handle_request'
.bundle/gems/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:375:in`process_client'
.bundle/gems/ruby/2.2.0/gems/puma-2.11.2/lib/puma/server.rb:262:in `block in run'
.bundle/gems/ruby/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in`call'
.bundle/gems/ruby/2.2.0/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
Request

Parameters:

{"id"=>"another"}

**Comment by campgurus** [comment]
this happens on failed geolocation.  need graceful check of geocoder result before leaving the edit form.

**Comment by rlgreen91** [comment]
We're pretty well aware of this, so we'll close this now.
