### ISSUE TITLE
Moving from Heroku

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#363]
Based upon a number of issues that we have had as a result of the limitation of the Heroku platform, it makes sense to move to Digital Ocean and/or Linode.

We currently pay $16 for two instances with 512MB RAM. For four dollars more we could have two Linodes with twice the memory, which would help with the slowness that occurs sometimes.

Combine that with #362, #125, #57 and we have some growing pains.

**Comment by campgurus** [comment]
Makes sense.  In the short term, do we need to upgrade Elasticsearch?

**Comment by campgurus** [comment]
As discussed with @trystant, thinking about the tradeoff between Heroku's convenience and the need for a longer term solution. Here is a list of the commands I use with Heroku (most used to least):
* git push heroku master (appreciate being able to use git for deployment)
* heroku logs -t -a
* heroku log -a (similar to git log on local)
* heroku run (rake)
* heroku config
* heroku pg:pull
* heroku pg:push
* heroku ps:scale web=1

**Comment by trystant** [comment]
I'm revisiting this and outlining smaller steps.  I'm using a $100 Digital Ocean credit to set up a bespoke Elasticsearch service and have ebwiki-staging use it.

**Comment by trystant** [comment]
Simpler to setup, especially the firewall.  Also, it's a step towards platform independence for EBWiki. We can save ourselves some $$ being off Heroku. 

Got an ES droplet serving my AWS Cloud9 instance. So far, so good.

**Comment by trystant** [comment]
So, as of today, [staging.ewiki.org](https://staging.ebwiki.org) is running on an AWS RDS instance. This does result in some changes:
* `heroku pg:*` commands no longer work for `ebwiki-staging` since 
* There is no longer a Heroku database attached to the `ebwiki-staging` Heroku app.
* One can use the Heroku Postgres import & export using `pg_dump` and `pg_restore`

**Comment by trystant** [comment]
We've since moved this back to Heroku. The price "savings" turned out not to be worth it. We should think about multi-cloud strategies, but this ticket isn't pertinent now.
