### ISSUE TITLE
Add "drowning" to causes of death

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#3637]
There have been recent reports of people killed by drowning. As a result, we should add "drowning" to causes of death.

**Comment by trystant** [comment]
In order to add a cause of death, we need to:
* Add a migration entering a row into causes of death model
* Add the cause to the `Case` model
* Add a line to the case html form

I want to add more specific documentation about this moving forward.

**Comment by rlgreen91** [comment]
Done
