### ISSUE TITLE
"Follow" button font does not match other buttons

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#3643]
screenshot:
<img width="382" alt="Screen Shot 2020-08-27 at 6 46 11 AM" src="https://user-images.githubusercontent.com/1260659/91433752-c2f37c80-e831-11ea-9c28-2f2ba4e88bb7.png">

**Comment by rlgreen91** [comment]
Let's expand on this: all buttons on the case show view should not have an outline and should follow sentence style capitalization [as explained here](https://uxmovement.com/buttons/5-rules-for-choosing-the-right-words-on-button-labels/).  This should apply regardless of the user's login status.

**Comment by trystant** [comment]
@rlgreen91 I agree with this message. So, black outline-be-gone?

**Comment by rlgreen91** [comment]
@trystant Yes, that is the plan.  Also going to add some other issues about verifying this style in other places.

**Comment by MohamedAsan** [comment]
I am willing to take this up! Kindly assign to me

**Comment by shahkv95** [comment]
@campgurus Can I work on this issue?
Thank you!

**Comment by rlgreen91** [comment]
@shahkv95 Sorry, but someone else has already submitted a PR for this issue.  We do have other issues focusing on UI changes if you're interested.
