### ISSUE TITLE
Editing user profile

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3676]
Here's a list of changes that need to be made regarding a user editing their profile:

- In the user form, make these changes:
    - change the message on line 4 to say "prohibited your profile from being saved"
    - add some spacing between the photo and name fields.
    - change the message for the subscribe box to say "Click here to receive our newsletter!"
    - change the buttons to say "Update profile" and "Cancel"
    - align the right edge of the buttons with the right edge of the inputs
- after submitting the form, the user should be redirected to the updated profile
- On the user profile page, display an orange button that says "Edit profile" in the top right.  This button should only be visible if the current logged in user is viewing their own profile and should take them to the form.

**Comment by claracodes** [comment]
Hi, I would like to help with this issue!
