### ISSUE TITLE
Display cause of death on case show view

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3681]
Update the case show view to display the `cause_of_death_name` attribute as "Cause of death: [value]".  This should be below the list of agencies, with the same font size.  You'll want to display the values in the locale file instead of the actual enum, similar to how we do the dropdown field in the case form.

**Comment by 93lykevin** [comment]
Hi @rlgreen91, can I take this? It will be my first contribution if merged

**Comment by rlgreen91** [comment]
Hi @93lykevin sure thing!  Let me know if you run into any issues
