### ISSUE TITLE
Update simplecov gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3692]
Update the simplecov gem to 0.19

**Comment by anuragaryan** [comment]
Hi, can I work on this? 🙇

**Comment by rahmatullah5** [comment]
Hi, good day sir @rlgreen91.
can I work on this issue and could you grant me access to create a pull request? I already have completed the code.

**Comment by rlgreen91** [comment]
@anuragaryan @rahmatullah5 Hi, thanks for commenting!  Unfortunately someone has already beaten you to the punch for this one.  Please note that we do have other quick fix issues like this one, so feel free to grab one of those and submit a PR.
