### ISSUE TITLE
Update factory bot rails gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3697]
Update the factory bot rails gem to 6.1

**Comment by the-spectator** [comment]
@rlgreen91 can I claim the issue?

**Comment by rlgreen91** [comment]
Merged in #3700

**Comment by rlgreen91** [comment]
Sorry @the-spectator, someone has already submitted a PR for this.  We do have other quick fix issues like this - feel free to grab one and submit a PR.

**Comment by the-spectator** [comment]
No worries 😊 Have a nice day!
