### ISSUE TITLE
fix TravisCI

### ISSUE THREAD

**Issue by epfeen** [EBWiki/EBWiki#3699]
`Database 'travis_ci_test' already exists
DEPRECATION WARNING: ActiveRecord::Base.raise_in_transactional_callbacks= is deprecated, has no effect and will be removed without replacement. (called from <top (required)> at /home/travis/build/EBWiki/EBWiki/config/environment.rb:8)
rake aborted!
ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key`

Please add env variables for ci.

**Comment by trystant** [comment]
@epfeen Thanks for checking out EBWiki in general. The best way to resolve this [ArgumentError issue](https://github.com/EBWiki/EBWiki/issues/891) is outlined in [Common EBWiki Development Errors](https://github.com/EBWiki/EBWiki/wiki/Common-EBWiki-development-errors). In a nutshell, create an [Amazon S3](https://aws.amazon.com/s3/) bucket that you can access, then enter the credentials for that bucket in the aws_* environmental variables on your local system. Once that's done, you can do the same for your Travis build. Please let us know if you have any questions. Thanks.
