### ISSUE TITLE
Small screen view images are small with a lot of white space

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#37]
should have a single column of images that user can see one at a timw, filling up the phone screen.

**Comment by trystant** [comment]
@campgurus can you confirm that this is done?

**Comment by rlgreen91** [comment]
@campgurus @trystant what is the context behind this issue?  Where should this single column of images be?  On the home page?

**Comment by trystant** [comment]
I think that this is saying that the homepage should have one large image as opposed to the small images put together.  

It's in line with general mobile strategies, but what does that look like? We don't know.

**Comment by rlgreen91** [comment]
Ok.  So I'll add that as a to-do for things to ask Dre about.  Otherwise, I'll go ahead and close this now.
