### ISSUE TITLE
How to handle cases with multiple subjects

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#370]
e.g. http://ebwiki.org/articles/kisha-michael-and-marquintan-sandlin where two people were killed as a during the same incident. We have at least three of these so far.

Our current set up favors cases with one subject. So it might make sense to have separate articles for each victim, which makes urls easier, etc. This is the route taken by The Guardian (http://www.theguardian.com/us-news/ng-interactive/2015/jun/01/the-counted-police-killings-us-database).

The issue with this approach is that it requires duplication of links and updates.  e.g. if one of the cases gets updated, chances are that the sister case will need the same update creating duplicate work for someone.  The Guardian doesn't have this issue, since they don't do much updating of cases beyond the initial report.

**Comment by trystant** [comment]
I don't think that we need to duplicate links or any other case related
material, as long as the subjects are properly linked to the case.

**Comment by campgurus** [comment]
do you mean create an associative table, like ArticleLinks s.t. articles has_many :links through article_links?  That could solve the problem but 2 things:
* we will need to somehow make it easy for editors to associate links with multiple articles, could require a whole new form
* we need to go back to all of the old links and retroactively create the entries in the associative table.

or do you mean instead of the main model being articles (w/ articles/show and articles/index being the main views) we instead have subjects be the main object with the front page gallery referencing the list of subjects?

**Comment by mnyon-grandkru** [comment]
If I'm not mistaken, we've punted on multiple subjects for the time being. Thankfully, we haven't had a need for this.
