### ISSUE TITLE
Update faker gem to 2.0

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3715]
Update the faker gem to 2.0.  You will most likely need to consult [the changelog here](https://github.com/faker-ruby/faker/tree/v2.0) to fix any failed tests due to breaking changes.

**Comment by audiodude** [comment]
Can I take this one?

**Comment by audiodude** [comment]
Hmm, I'm having trouble running the tests. I don't want to use the "legacy", everything-on-your-host-machine dev setup. But when I run `rake` in the docker container I get lots of:

```
An error occurred while loading ./spec/services/sort_collection_ordinally_spec.rb.
Failure/Error: require File.expand_path('../config/environment', __dir__)

RuntimeError:
  Action dashboard already exists. Please change its custom key.
# /usr/local/bundle/gems/rails_admin-1.3.0/lib/rails_admin/config/actions.rb:99:in `add_action_custom_key'
...
...
...
Finished in 0.00031 seconds (files took 21.96 seconds to load)
0 examples, 0 failures, 49 errors occurred outside of examples
```

**Comment by rlgreen91** [comment]
Thanks for letting us know @audiodude.  I'm tagging @managedkaos as he was the one behind the Docker setup - hopefully he has some insight into what's happening.  In addition, what happens when you run `rspec spec/` within the docker container?  Or are you running into issues setting up the databases with rake?

**Comment by audiodude** [comment]
Running `rspec spec/` gives almost identical looking results. I have the docker container running and can get to the localhost version of the site just fine so I *think* the databases are set up?

**Comment by managedkaos** [comment]
hi @audiodude!  I am seeing some of the same issues with `rake` and `bundle` inside the container.  know that I'm looking into it 👍

**Comment by managedkaos** [comment]
@audiodude i've been able to get `rspec` running after sourcing the environment for the container.  basically, after you connect to the container, run:
```
source dev_provisions/environment.sh
```
this would be run from the root directory: `/usr/src/ebwiki`.

**Comment by audiodude** [comment]
Yes that works for me, thanks!

**Comment by rlgreen91** [comment]
Awesome!  Can one of you update the documentation noting this please?

**Comment by managedkaos** [comment]
I wil get to the docs, either with a make target that handles this case of a description of the workaround.
