### ISSUE TITLE
Update rspec-rails gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3723]
Update the rspec-rails gem to 4.0

**Comment by rahmatullah5** [comment]
Hi @rlgreen91, I will do this task.

**Comment by rlgreen91** [comment]
Hi @rahmatullah5 - sorry I just saw your comment!  Unfortunately someone else submitted a PR for this, so I'll be closing this issue.  To answer your questions, I did make sure we aren't upgrading to a version that no longer works with other gems.

**Comment by rlgreen91** [comment]
Merged in #3801
