### ISSUE TITLE
Migrate to new database_cleaner gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3746]
[Follow the instructions listed here](https://github.com/DatabaseCleaner/database_cleaner#gem-setup) to migrate from the `database_cleaner` gem to `database_cleaner-active_record` gem.  That gem should be set to version 1.8.

**Comment by Atul9** [comment]
@rlgreen91 I would like to take this up.

**Comment by Atul9** [comment]
Hi @rlgreen91 I have opened up a PR at https://github.com/EBWiki/EBWiki/pull/3750/, please check
