### ISSUE TITLE
articles/index gallery pagination links when bottom row incomplete

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#376]
Pagination links should be beneath the bottom row, even if the row is not full. Currently pagination links sit to the right of the last photo in the middle of the row.
<img width="887" alt="screen shot 2016-03-01 at 6 04 54 am" src="https://cloud.githubusercontent.com/assets/1260659/13425302/e0136580-df73-11e5-89c1-e7a6784272e5.png">

**Comment by trystant** [comment]
We shouldn't have incomplete rows.

I've noticed those occurring on the "cases nearby" section, however.

<img width="894" alt="screenshot 2016-03-01 06 43 55" src="https://cloud.githubusercontent.com/assets/13509/13426052/07879078-df79-11e5-8f66-1ca6926592d6.png">

**Comment by campgurus** [comment]
well we have a specific number of cases per row. so if we have 6 cases per row for a full row, and the total number is not evenly divisible by 6, that remainder results in an incomplete row. Not sure there is anything to be done about that.

In my case, the shortage was found when I did a search on the index page which yielded an odd number of results.

**Comment by trystant** [comment]
The solution would be to modify the size of the images or the spacing so
that overall, the row space is filled.

Since we got rid of the padding in between images, the solution would be to
increase the image sizes.

There's a mathematical formula that can confirm the sizes needed in each
case.


On Tue, Mar 1, 2016 at 6:47 AM, campgurus <notifications@github.com> wrote:

> well we have a specific number of cases per row. so if we have 6 cases per
> row for a full row, and the total number is not evenly divisible by 6, that
> remainder results in an incomplete row. Not sure there is anything to be
> done about that.
>
> In my case, the shortage was found when I did a search on the index page
> which yielded an odd number of results.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BOWiki/BOW/issues/376#issuecomment-190685268>.
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by trystant** [comment]
A simpler solution would be to make sure that the number of articles is divisible by the number of articles per page. We'd have to adjust this based upon different agent sizes (phones, tablets)

**Comment by rlgreen91** [comment]
So, just to chime in, this is not a problem I have ever seen on the first page, or the search page.  This is however, a problem I have seen on a page for an individual article. However when we do a redesign, that section will be the first thing to be changed on that page, and will most likely its current form will be scrapped altogether.  Given this, I will be closing this issue.
