### ISSUE TITLE
Changes to the login page

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3762]
Update the login page as follows:

- Make the email field the initial focus on page load
- Add a link for instructions on how to unlock an account
- Add some spacing between the last set of elements underneath the login button

**Comment by MohamedAsan** [comment]
@rlgreen91 Email field is already focused on page load. Checked it in [ebwiki.org](https://ebwiki.org/users/sign_in)
Spacing should look good after deploying #3739 

<img width="902" alt="Screenshot 2020-10-06 at 11 22 02 AM" src="https://user-images.githubusercontent.com/29650842/95163774-363fc500-07c6-11eb-90a4-ffedf8be420d.png">

**Comment by rlgreen91** [comment]
Ok @MohamedAsan, but can you add the additional links I mentioned?

**Comment by MohamedAsan** [comment]
I tried to debug this in my local setup and found that the link is not displayed as the condition `devise_mapping.lockable?` returns `false`
This is because in `User` model, `devise` is not configured to be `lockable` 

```
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
```

I don't have much idea about it. Would be great if someone else can pick this up 🙂

**Comment by rlgreen91** [comment]
Oh, I could have sworn we had that enabled, haha.  Must be confusing this with a work project.  In that case, yeah, this is taken care of by your other changes, thanks!  Feel free to grab another UI issue if you'd like.
