### ISSUE TITLE
Change fog gem to fog-aws gem

### ISSUE THREAD

**Issue by helderhp** [EBWiki/EBWiki#3789]
Change fog gem to fog-aws gem

fog gem -> 2.2.0 - June 18, 2019
fog-aws gem -> 3.6.7 - August 26, 2020

Notice after update fog gem

```
Thank you for installing fog!

IMPORTANT NOTICE:
If there's a metagem available for your cloud provider, e.g. `fog-aws`, you should be using it instead of requiring the full fog collection to avoid unnecessary dependencies.

'fog' should be required explicitly only if the provider you use doesn't yet have a metagem available.
```

**Comment by rlgreen91** [comment]
Let's add a bit of clarity - so, to complete this issue, I'd recommend doing this:

- Completely remove the fog gem and any associated files and/or code that specifically reference the gem. (save any config settings to notepad or something)
- Add fog-aws to the Gemfile and run bundle install
- Configure carrierwave to use fog-aws as outlined [here](https://github.com/carrierwaveuploader/carrierwave#using-amazon-s3) 
- Configure Rspec to use Fog mocks (the old config code in rails_helper.rb will probably still work as is)
- Verify specs pass locally, at least the ones dealing with uploading photos
- Verify you can upload a pic for a case locally
