### ISSUE TITLE
Remove rails 12factor gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3790]
Remove the rails 12factor gem

**Comment by Dnguye92** [comment]
@rlgreen91 can i grab this one?

**Comment by debashis-biswal** [comment]
@rlgreen91 rails_12factor gem has been removed. https://github.com/EBWiki/EBWiki/pull/3798

**Comment by rlgreen91** [comment]
@Dnguye92 Sorry I missed your comment!  We do have other issues focused on gem upgrades, so please feel free to grab one of those!
