### ISSUE TITLE
Update carrierwave-imageoptimizer gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3795]
Update the carrierwave-imageoptimizer gem

**Comment by akashgupta05** [comment]
i'd like to pick up this issue

**Comment by rlgreen91** [comment]
Hi @akashgupta05 - are you still interested in tackling this issue?  I'm going to assign this to myself since I have time to do it now, but if you're interested in upgrading some gems, please feel free to assign yourself to some of the other issues.
