### ISSUE TITLE
Upgrade rails_admin gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3796]
Upgrade the rails_admin gem

**Comment by fabiosoaresv** [comment]
@rlgreen91 I was looking for issues to work on for Hacktoberfest and I would to pick this up if possible. Thanks!

**Comment by rlgreen91** [comment]
@fabiosoaresv Sorry, but someone else submitted a PR for this!  If you'd like to work on another issue, we do have others for upgrading gems.  Please feel free to assign it to yourself and submit a PR - no need to wait for me!
