### ISSUE TITLE
Error happens when run rspec 

### ISSUE THREAD

**Issue by edimossilva** [EBWiki/EBWiki#3803]
**Describe the bug**
Error when running rspec 

**To Reproduce**
1) Follow docker setup 
2) Connect to the container 
3) run `rspec`
4) see error `RuntimeError:
  Action dashboard already exists. Please change its custom key.`

**Expected behavior**
1) Follow docker setup 
2) Connect to the container 
3) run `rspec`
4) I see all green :)

**Image**
![image](https://user-images.githubusercontent.com/6463001/95657389-fc9bf080-0b1c-11eb-922c-51ad4efc7424.png)

**Comment by managedkaos** [comment]
@edimossilva you need to source the environment script before running rspec or use the `rspec` make target.

- source environment script:  `docker exec ebwiki bash -c 'source dev_provisions/environment.sh && rspec spec/'`

- rspec make target: `make rspec`
