### ISSUE TITLE
Rubocop isn't pushing changes to the branch

### ISSUE THREAD

**Issue by managedkaos** [EBWiki/EBWiki#3887]
**Describe the bug**
When rubocop runs in CI and updates files, it tries to commit them back to the current branch.  

Presently this operation fails with the following:

```
0s
Run modified=$(git status | grep modified | wc -l)
[detached HEAD 57b9574] Committing files modified by rubocop
 3 files changed, 3 insertions(+), 3 deletions(-)
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Process completed with exit code 128.
```

**To Reproduce**
1. Create a branch, add some bad code that rubocop would try to fix automatically, then submit a PR
2. Check the output of the Rubocop action

**Expected behavior**
The changes made by rubocop should be added to the branch along with the commit  message "Committing files modified by rubocop"

**Screenshots**
1. https://github.com/EBWiki/EBWiki/runs/1700557179?check_suite_focus=true
2. https://prnt.sc/xm20ke

**Desktop (please complete the following information):**
- N/A

**Smartphone (please complete the following information):**
- N/A

**Additional context**
- N/A

**Comment by managedkaos** [comment]
[Context and expression syntax for GitHub Actions
](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context)

There are plenty of crazy ways to get the head ref (aka source branch) but the details in the link above provide built in ways to do it.  Particularly:

Property|Type | Description
-- | -- | --
github.head_ref | string | The head_ref or source branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is a pull_request.

**Comment by managedkaos** [comment]
Also include the pull request details in the commit message:
```
git commit -m "Committing files modified by the workflow $(GITHUB_ISSUE)";
```
[Webhook events and payloads
](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#pull_request)

**Comment by mockdeep** [comment]
@managedkaos I was wondering why we're auto-fixing in CI. Personally, I've found that rubocop auto-fix results can sometimes be surprising, so I'd rather handle those sorts of things locally. What if we made it so that rubocop failed the build instead? That's worked well for me in the projects I've worked on, and seems to be pretty common across the ruby community.

**Comment by managedkaos** [comment]
@mockdeep i could go either way.  from an automation view, i'd appreciate it if the tool made the changes for me and then I was able to review them vs having to find the changes and then making them myself.  but I also understand that bots left unchecked can do weird things. :D 

@rlgreen91 @trystant any thoughts?

**Comment by rlgreen91** [comment]
I'd rather have it fail.  Rubocop is very opinionated, sometimes very strongly about the weirdest details, and trying to do that type of autocorrection in CI is going to be annoying.

**Comment by trystant** [comment]
Plus one on failure for Rubocop.

On February 5, 2021, Github Notifications <notifications@github.com>
wrote:
> I'd rather have it fail. Rubocop is very opinionated, sometimes very

> strongly about the weirdest details, and trying to do that type of
> autocorrection in CI is going to be annoying.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/EBWiki/EBWiki/issues/3887#issuecomment-773813920>,

or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAADJRJWIMKIZVVEYRWDC7LS5ODGRANCNFSM4WR6KBEA>.

**Comment by mnyon-grandkru** [comment]
I should clarify that I'm in favor of having the build fail for now (making that change in a separate issue) while working on autofix

**Comment by managedkaos** [comment]
closing this one for now.
