### ISSUE TITLE
Idea: switch to Postgres search

### ISSUE THREAD

**Issue by mockdeep** [EBWiki/EBWiki#3896]
PostgreSQL has pretty rich built in search facilities, so we could eliminate a dependency on Elastic Search by relying on that instead. We've been using it where I work for several years and it's been pretty much zero maintenance. We have a table with >12 million records that we can search in an instant. More on the benefits [here](https://stackoverflow.com/questions/58812324/postgresqlfull-text-search-vs-elasticsearch), but one big one I want to point out is that it makes the dev setup process less complicated.

**Comment by mnyon-grandkru** [comment]
@mockdeep I believe that @rlgreen91's had similar thoughts for some time. Consdering our current & future use cases, it would simplify the infrastructure.

**Comment by mockdeep** [comment]
Great! It seems like there are other priorities in the short term, but I've got a decent amount of experience setting it up in a scalable way, so I'll be happy to work on it or provide assistance when the time comes.

**Comment by rlgreen91** [comment]
It's something I've brought up before not just as a nice-to-have but also something we might need to have later on.  But it's just not a high priority right now.  I have it on our list/roadmap so I'll close this for now.
