### ISSUE TITLE
Update rubocop gem

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3947]
Update the rubocop gem to 0.75.  Note that you will need to update the corresponding channel listed in `.codeclimate-yml` to `rubocop-0-75`.

There's a pretty good chance that after the upgrade, running rubocop locally will reveal some fixes it wants to see.  If the changes are small and straightforward, feel free to go ahead and do them.  If you think something warrants a separate issue or more discussion, then just make a comment in your PR.

**Comment by danielvdao** [comment]
Hey @rlgreen91 I think this PR should do it: https://github.com/EBWiki/EBWiki/pull/3979. That said, I think we're already on 0.93, I added some notes in the PR description.

**Comment by danielvdao** [comment]
Follow-up to close this one all the way: https://github.com/EBWiki/EBWiki/pull/3981 🎉
