### ISSUE TITLE
Remove analytics routes

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3958]
We no longer have an analytics controller, so remove any routes pointed to that controller.

**Comment by danielvdao** [comment]
I believe https://github.com/EBWiki/EBWiki/pull/3976 should address this. Though I am wondering if we should also remove the view code?

**Comment by rlgreen91** [comment]
Hey @danielvdao - yes, you can go ahead and remove that code as well, thanks

**Comment by danielvdao** [comment]
@rlgreen91 Sounds good. I think https://github.com/EBWiki/EBWiki/pull/3976 should be ready for review then!

**Comment by rlgreen91** [comment]
Thanks!  Merged
