### ISSUE TITLE
Gender and Race dropdowns default to first values in edit form

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#3963]
When editing a case, the gender and race/ethnicity dropdown fields show the first value as the selected item.  Instead, these fields should show the actual value saved to the case as the selected item.

To reproduce:

- Create a case with a subject and choose "female" as the gender selection and "Asian" as the race/ethnicity selection.
- Navigate to the edit view of the case
- View the dropdowns for the gender and race/ethnicity selections.  They will default to the first option but should instead show the options you selected above.

**Comment by yez** [comment]
I'd like to fix this if still available.
