### ISSUE TITLE
Add a scroll bar to Recently Updated List

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#400]
I am frustrated when I see that more than 10 cases have been updated today but I can't get to them. Maybe we should add a scroll bar include more cases on this list.

My concern is that normal html5 scroll bars are ugly and sometimes difficult to see. So we will need some style work. this gem could help: https://github.com/twoweb/scrollbar-rails

**Comment by rlgreen91** [comment]
Eh, I don't like the idea of a scroll bar for a single section on a page that is not marked with borders. If you're talking about the recent updates section on the landing page, I think it would be useful to have a link at the bottom to navigate to a page with all of the cases added or updated that day.  If you're talking about a different section, please state that here.

**Comment by campgurus** [comment]
@rlgreen91 hadn't even thought of the link to all updated cases.  Seems so obvious now that you said it.  Totally agree.
