### ISSUE TITLE
mimemagic-0.3.x licensing issue

### ISSUE THREAD

**Issue by mnyon-grandkru** [EBWiki/EBWiki#4001]
**Describe the bug**
As described [elsewhere](https://github.com/rails/rails/issues/41750), the removal of this gem has raised some issues throughout Rails as other Ruby projects.

**Expected behavior**
We would expect to not have errors building EBWiki.

**Screenshots**
Some CI builds and [deploys](https://dashboard.heroku.com/apps/ebwiki-staging/activity/builds/39505a58-0362-402b-861a-7bd999a3d021) have failed due to this version of the [mimemagic](https://github.com/mimemagicrb/mimemagic) gem.
I think that a fix for this involves instituting one of the [fixes](https://twitter.com/robbyrussell/status/1375252142743687169) outlined here to the last build that went to production.

**Comment by rlgreen91** [comment]
Addressed in #4002
