### ISSUE TITLE
EBWiki Upgrade: Rails 5.1 -> Rails 5.2

### ISSUE THREAD

**Issue by mnyon-grandkru** [EBWiki/EBWiki#4037]
# Upgrade rails from 5.1 to 5.2

## Reason for upgrade
We want to have a supported version of Rails on this system, based on the [upgrade docs](https://guides.rubyonrails.org/v5.2/upgrading_ruby_on_rails.html#upgrading-from-rails-5-1-to-rails-5-2)

Checklist:
- [x] Add [Bootsnap](https://guides.rubyonrails.org/v5.2/upgrading_ruby_on_rails.html#bootsnap) gem.
- [x] Run [RailsBump](https://railsbump.org/lockfiles/new) on the EBWiki Gemfile.lock.
- [ ] Confirm whether there's an action needed in [upgrading cookies](https://guides.rubyonrails.org/v5.2/upgrading_ruby_on_rails.html#expiry-in-signed-or-encrypted-cookie-is-now-embedded-in-the-cookies-values).
- [x] Review additional Ruby upgrade articles/guides.
  - [ ] - https://guides.rubyonrails.org/v5.2/upgrading_ruby_on_rails.html#expiry-in-signed-or-encrypted-cookie-is-now-embedded-in-the-cookies-values
  - [ ] https://www.fastruby.io/blog/rails/upgrades/upgrade-rails-from-5-1-to-5-2.html

**Comment by rlgreen91** [comment]
@mnyon-grandkru let me know if you need any help, especially if it's something that can be done in parallel.

**Comment by mnyon-grandkru** [comment]
I worked on the Github Action failure today. @rlgreen91's `sudo apt-get update` fixed errors on one stage, but the newest

**Comment by rlgreen91** [comment]
What's the error now?

**Comment by mnyon-grandkru** [comment]
This is the error in the [CI build](https://github.com/EBWiki/EBWiki/runs/3331195722?check_suite_focus=true) on the 5.2 branch. 
```

Run cp config/database.ci.yml config/database.yml
  cp config/database.ci.yml config/database.yml
  bundle exec bin/rails db:create
  bundle exec bin/rails db:structure:load
  shell: /usr/bin/bash -e {0}
  env:
    RAILS_ENV: test
bundler: failed to load command: bin/rails (bin/rails)
Bundler::GemNotFound: Could not find rake-13.0.3 in any of the sources
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:91:in `block in materialize'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `map!'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `materialize'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/definition.rb:237:in `specs_for'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/definition.rb:226:in `requested_specs'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:108:in `block in definition_method'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:20:in `setup'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler.rb:107:in `setup'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/setup.rb:20:in `<top (required)>'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  ```

**Comment by rlgreen91** [comment]
@mnyon-grandkru Doing some more digging and came across this: https://github.com/rubygems/rubygems/issues/4269
We're not deploying to Heroku, but the case of building an image on Ubuntu when the dev work was done on Windows or Mac still fits.

**Comment by mnyon-grandkru** [comment]
We currently have to resolve outstanding spec errors in order to finish this upgrade.  There are 154 specs to resolve, but 107 of them are instances of two issues:
1. Could not find mapping for user object
```
101) Agencies GET /agencies/:id/edit when authenticated will return the agency form
       Failure/Error: sign_in user

       RuntimeError:
         Could not find a valid mapping for #<User id: 64, email: "person57@example.com", created_at: "2021-09-22 05:48:34", updated_at: "2021-09-22 05:48:34", admin: false, latitude: nil, longitude: nil, name: "Dedra Sanford", description: nil, state_id: nil, state: nil, city: nil, facebook_url: nil, twitter_url: nil, linkedin: nil, slug: "dedra-sanford", subscribed: nil, analyst: false>
       # ./spec/requests/agencies_spec.rb:69:in `block (4 levels) in <top (required)>'
```
2.  Validation failed: Case must exist, Gender must exist, Ethnicity must exist
```
111) Case validity should not accept dates in the future
       Failure/Error: f.subjects { [create(:subject, case_id: f.id, gender_id: 1, ethnicity_id: 1)] }

       ActiveRecord::RecordInvalid:
         Validation failed: Case must exist, Gender must exist, Ethnicity must exist
       # ./spec/factories/cases.rb:11:in `block (3 levels) in <top (required)>'
       # ./spec/models/case_spec.rb:26:in `block (3 levels) in <top (required)>'
```

The second can be resolved by updating the factory used in the spec. I'm not sure about the first. Resolving those two issues are essential.

**Comment by rlgreen91** [comment]
@mnyon-grandkru We can close this right?

**Comment by mnyon-grandkru** [comment]
Yes, we can close this. Sorry for the slow response.
