### ISSUE TITLE
Display character counter for blurb section of case form

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#4040]
We currently use the blurb attribute on cases to store the text displayed on pins in map views of the cases.  Because of this, we limit blurbs to 500 characters.  In the new and edit case forms, add a UI element to warn users when they have 100 characters or less. Twitter's character limit element would be a good idea to emulate.

**Comment by MohamedAsan** [comment]
I would like to work on this issue. Kindly assign it to me

**Comment by rlgreen91** [comment]
Hi @MohamedAsan, thanks for picking this up!  I've invited you to join the repo and assigned this issue to you. Please let me know if you have any other questions.

**Comment by MohamedAsan** [comment]
@rlgreen91 Raised a PR already #4059. Kindly check
