### ISSUE TITLE
Create a rollout history model and table

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#4063]
Create a new model called `RolloutHistory`.  This model should include:
- rollout_name => a string
- change_date => date
- change_description => text
- author_name => a string

In the model, all of the attributes should be required. The `:sanitize` helper should be used on the `change_description` and `author_name` attributes.

**Comment by m8051** [comment]
Hi @rlgreen91 I think I could help with this one, may I? Thanks
