### ISSUE TITLE
Rename `cause_of_death_name` to `cause_of_death`

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#4067]
Throughout the codebase, rename anything named `cause_of_death_name` to `cause_of_death`.  This should include at least renaming an enum and a column in the `Case` model and table respectively.

**Comment by TechieNK** [comment]
@rlgreen91 Can I work it under hacktoberfest'21?

**Comment by mairagee524** [comment]
I can take this on if you still need help!
