### ISSUE TITLE
Squash Migrations

### ISSUE THREAD

**Issue by mnyon-grandkru** [EBWiki/EBWiki#4101]
Let's turn all those migrations in `db/migrate` to one file.

**Comment by mnyon-grandkru** [comment]
After discussions with @rlgreen91, we're going to have a file up to the point where the first enum is added, one for the enum, then another for the next round of changes up to another enum, then a file for that enum.

**Comment by mnyon-grandkru** [comment]
I'm using activerecord_enum in order to create a migration has all the tables and elements represented, including cases and agencies. This allows for one file to create all the syntax. I have two failures running `bundle exec rake` on the branch, and I also need to compare the schema in progress to the structure.sql instead. @rlgreen91 would it make more sense to have an updated `structure.sql` as a deliverable? I think that my next step would be to create an updated `structure.sql` and then show I can create the databases and run rake successfully.

**Comment by mnyon-grandkru** [comment]
@rlgreen91 NVM on the `structure.sql` question. I'm going to review the rest of the failures (there are 41) to see what needs to be adjusted about the database created.

**Comment by rlgreen91** [comment]
Addressed in PR #4125
