### ISSUE TITLE
Allow Document uploads

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#426]
Editors should have the ability to upload documents relating to cases.  public records like police reports, court documents as well as leaked investigation reports would help to fill in the raw materials for people who want to dig deeper.  I am not sure how to do this.  We can use Carrierwave to upload documents the same way we upload images, so I imagine documents are pretty much the same. 

Ths is long term due to large amt of work required including the likely need for some (admittedly not foolproof) safeguards for the anonymity of leakers.

this from SO may be helpful: http://stackoverflow.com/questions/20600494/rails-and-carrierwave-images-can-be-uploaded-but-pdfs-cant or this: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Do-conditional-processing

**Comment by campgurus** [comment]
Another SO comment suggests creating a new uploader. For files, I think we need to create a new model to house the uploads and then have a many to many relationship between the Documents model (which has the document uploads) and Articles, s/t Article has_many Documents thrugh CaseDocuments.

That way we can use a single uploaded document in multiple articles. Again dealing witht he case that a single document references multiple cases.

**Comment by trystant** [comment]
First, I’d switch to Paperclip from carrierwave. The learning curve can be obnoxious with carrierwave.
Second, I'd start with the simplest file upload example that would work in development, and then figure out how to switch from a simple file upload to a File upload to S3.

**Comment by rlgreen91** [comment]
This issue was resolved with PR #802
