### ISSUE TITLE
Recently updated list rows widen for certain times

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#442]
double digits in the hours column pushes the row wider from the normal single line format. Doesn't look great.  Screenshot below:
<img width="335" alt="screen shot 2016-03-23 at 12 45 45 pm" src="https://cloud.githubusercontent.com/assets/1260659/13993159/84e2bd9e-f0f5-11e5-99fa-31dc766487af.png">

**Comment by trystant** [comment]
What is the desired solution here? Do you want the row to not widen regardless by making the font smaller, or having information expand upon a rollover?

**Comment by rlgreen91** [comment]
A solution is defined in #964, so I will close this issue.
