### ISSUE TITLE
Twitter Hashtag feed

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#491]
Recognizing we discussed this a while back, I wanted to memorialize it as an issue for a potential feature. Specifically my thought is that as we continue to build the tool that provides people with a one stop place for finding out about these cases, it might be a good thing to include content from Twitter based on appropriate hashtags.

For the schema, articles will has_many :hashtags.

and on the articles/show action, tweets = [last 10 tweets containing article.hashtags]

in articles#index, tweets = [last 10 tweets containing any of our saved hashtags]

So for example, on the  Akai Gurley page we could follow #AkaiGurley and include those updates.

I think this could augment or potentially replace our current comments section on the article page..

documentation for the gem that makes this relatively easy ishere: https://github.com/sferik/twitter

specifically, the call would just be something like: `client.search("#ruby -rt", lang: "ja").first.text`

**Comment by trystant** [comment]
BTW, this isn't a high priority in my book, but if this is what you're focusing on, so be it.

**Comment by campgurus** [comment]
i know. you hate this, but i wanted to see what it would look like
i pushed to staging but i still need to set the env vars in travis.

**Comment by campgurus** [comment]
Ok this is essentially done and working. User can enter multiple hashtags, tweets are retrieved and ordered by created_at. While admitting the possibility for malicious behavior, the feature works pretty well.  I think we would do well to replace comments (also subject to malicious content) with the twitter content based on hashtags. A couple items remain IMO:

* Implement caching to avoid bumping up against the Twitter API limits
* minor styling fixes, such as figuring out how many tweets to display, whether to add scrolling, etc

**Comment by trystant** [comment]
I wouldn't call it done because there's no solution for Rate limiting and error handling from Twitter. There's also two specs for all of this. There's a bit of a ways to go, I'm afraid.

**Comment by campgurus** [comment]
I believe that vs caching or throttling both of which would result in latency, the best approach is public streaming: https://dev.twitter.com/streaming/overview to follow topics.  The connection remains open so rate limits do not apply.  However, approval is required so we will have to apply for access.  In process now.

**Comment by trystant** [comment]
So we cannot just apply the sample app in this tutorial and push it live. Primarily due to the recommendations we'll have to follow if we want to get access to the Streaming API. Mainly:

"the Twitter Streaming docs recommend decoupling the collection & processing of tweets, i.e. saving tweets to disk and processing them from a messaging queue such as ZeroMQ, RabbitMQ, etc)."

So, how comfortable are you implementing the sample from that tutorial?

**Comment by campgurus** [comment]
A couple more minor todos on this: 
* display hashtags
* change "recent Tweets" to something better

To the previous comment, I am comfortable with none of implementation, but the more i think about this feature, the more useful i think it will be in informing potential users about what is happening in these cases and also keeping our editorial constituency engaged.

**Comment by campgurus** [comment]
update: I just submitted our request to Twitter to be considered for streaming access. I did not go through [the tutorial for setting up user streams](http://alexehrnschwender.com/2015/01/live-streaming-ruby-using-threads-sses-build-real-time-twitter-client/) (linked above) since it is well beyond my technical understanding, and completely unrelated to how we want to use Twitter. (we are not streaming dat based on users). I included a link to this page on staging: http://staging.ebwiki.org/articles/freddie-gray to illustrate how we plan to use their content.

Hopefully, we will be approved soon.  If we are not approved, I think we should just use the REST client we are currently working with on staging and add some kind of throttling or error rescues to manage the API limits.

**Comment by campgurus** [comment]
Quick update on this.  It seems we are able to check the rate limit status to see how many calls we have left before hitting the api.

the full json hash is retrieved with:

`$client.get('/1.1/application/rate_limit_status.json')`

to parse the hash for e.g. the number of calls available, remaining and the time to reset, use this:

`$client.get('/1.1/application/rate_limit_status.json')[:resources][:search]` which will yield something like:

```>> $client.get('/1.1/application/rate_limit_status.json')[:resources][:search]
(irb):26:in `irb_binding': [DEPRECATION] Twitter::REST::Client#get is deprecated. Use Twitter::REST::Request#perform instead.
=> {:"/search/tweets"=>{:limit=>180, :remaining=>179, :reset=>1462634694}}
>>```

If we can check our remaining calls before hitting the api, we can guarantee that we don't generate the TooManyRequests error and also ensure that we don't get blacklisted by Twitter.

**Comment by campgurus** [comment]
So revised potential to dos, I am thinking about for this feature (still trying to figure out what is required:

* add code to check rate limit status before hitting the Twitter api
* add code to use delayed_job to check Twitter asynchronously, if we are over the limit
* create a table to house retrieved tweets and serve tweets to the page from the db instead of a live call (we probably would purge these at some point regularly)
* gracefully handle 429 too_many_requests api response (is this necessary if using the db?)
* gracefully handle other failed api calls (eg if twitter api is down)
* add rspec to test (of course!)

**Comment by rlgreen91** [comment]
Yeah, so I have lots of feelings about this:
 - First, I'm assuming that the hashtags are a field that editors can add and update, right?  We shouldn't be doing it ourselves.
- 10 hashtags is too many.  Honestly, 5 is should be enough.  Thinking about cases that have blown up in  public, people usually settle on 1 or 2.
- Definitely not a fan of this replacing the comments section.  Like what's been said before, we need to handle rate limiting, which Twitter can be weird about, and error handling, especially when Twitter goes through outages.
- I realize this issue is from 2016, but we cannot rely on Twitter due to "fake news."  We have seen the outright lies passed as truths, bots, and Russia-linked accounts that are plaguing all of the major social media sites.  As a wiki that allows the public to contribute, we have to be especially careful that what we're posting is factual, and Twitter is too wild at times for it to be our sole source.
- Following on that, I disagree with making Twitter our sole source of comments because it locks people out.  We're a wiki - we want as much factual information about our topic to be available to as many people as possible.  Having a section limited to one service and its users does the opposite of that, regardless of that one service.
- Do we really want to implement and maintain RabbitMQ?
- Where are we actually on this?  Did we ever hear back from Twitter?  Do we even still want to do this?

**Comment by campgurus** [comment]
I built a version of this that worked and I thought it was kind of cool to include those conversations and to automate new content on the case pages s.t. a visitor to a case page can see everything about that case in one place.  I think Google alerts might be able to provide a similar function on the case pages. I think the goal is to have EBWiki's case pages serve as a one stop for all information about a particular case. Twitter was just one source.

To answer your questions, Editors would create the hashtags. Twitter would not replace Comments from Users, I was just thinking about layout.

In terms of fake news, I obviously don't want us to propogate it, but I also don't feel qualified to be the one who judges what is fake and what is real. So I don't want potentially to throw the baby out with the bath water. Instead, I would generally lean towards posting information and letting the crowds decide.  

All that said, I am sensitive to your critiques above too. Especially with what we now know of bots posting with the sole purpose of manipulating people, I would agree that we want to think more about these issues before implementing this.

**Comment by rlgreen91** [comment]
I think this could be a great addition to the comments section, but in that case I'd rather see an "in the news" section that incorporated real-time data from a multitude of sources, not just Twitter.

**Comment by trystant** [comment]
I've been against using social media as a main source for multiple reasons, even before the most recent election cycle and Twitter/Facebook's impact on both the election and/or general discourse.

When we put a survey out, adding that information was not a high priority.

Finally, I feel that publishers that take this very stance:

> In terms of fake news, I obviously don't want us to propogate it, but I also don't feel qualified to be the one who judges what is fake and what is real. So I don't want potentially to throw the baby out with the bath water. Instead, I would generally lean towards posting information and letting the crowds decide.

The logical conclusion of policies like these are found in Youtube comments. I really don't think that is where we want to be/go.

**Comment by trystant** [comment]
@rlgreen91 @campgurus I think we can close this one for now, no?

**Comment by rlgreen91** [comment]
Honestly, I think we can close this.  I'd rather us push content to Twitter rather than the other way around at this point.
