### ISSUE TITLE
CORS error prevents fonts from showing up in live admin

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#540]
The admin sections on staging and production do not show the fonts intended due to a CORS issue with the resources.

Expected icons:
<img width="1440" alt="screenshot 2016-05-11 20 15 33" src="https://cloud.githubusercontent.com/assets/13509/15200477/4e7f5a0a-17b5-11e6-9493-1d20fd3eeedf.png">

Admin in production:
<img width="1440" alt="screenshot 2016-05-11 20 17 46" src="https://cloud.githubusercontent.com/assets/13509/15200494/72b50640-17b5-11e6-8a58-758580116f74.png">

Javascript Console error message:

```
Font from origin 'https://d39r1dufm4jbqr.cloudfront.net' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://ebwiki.org' is therefore not allowed access.
```

**Comment by rlgreen91** [comment]
It doesn't for some reason - are you looking into this?

**Comment by trystant** [comment]
I took a look to see how feasible it would be. This would be after #1268 since they both affect middleware.

**Comment by trystant** [comment]
So `rack-cors` isn't the solution needed here. It looks like the CloudFront policy needs to be modified. @campgurus, if you can provide the credentials to the Cloudfront CDN, I can make policy changes. 

Thanks

**Comment by trystant** [comment]
So while there's a lot of info about using S3 as a source for CloudFront & setting up [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), but not so much about how to set the origins when using a non-S3 source.  I have set the:
```
Origin:
Access-Control-Allow-Origin: 
```

headers but only the `Origin` header is coming through.

**Comment by trystant** [comment]
This has since been fixed.
