### ISSUE TITLE
Default Image Caption not appearing in some cases

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#549]
I am not sure what is happening here.  An initial look shows these cases seem to funcion normally.  User can click thru to the show page, etc. screenshot below:

<img width="920" alt="screen shot 2016-05-16 at 6 35 00 am" src="https://cloud.githubusercontent.com/assets/1260659/15287415/a4cb3dd8-1b30-11e6-838d-2406c7120f02.png">

**Comment by trystant** [comment]
I don't think that this has appeared in a long time.
