### ISSUE TITLE
Add meta description to appear in search results

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#557]
In search results in Google, though or page titles are custom as we have defined them,  our descriptive texts appear to be drawn directly from the page. We should give a description meant to give a user more info about what we do and thus more reason to click through.  I will add a Screven shot to this shortly.

**Comment by rlgreen91** [comment]
@campgurus @trystant is this still something we need to be concerned about?  Or can I close this?

**Comment by trystant** [comment]
I think we can. The description does appear according to a couple of analyzers that I reviewed.
