### ISSUE TITLE
Site returns 500 page when Elasticsearch isn't available

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#57]
On Production, this error appears when Bonsai isn't available. We need to make the app more robust so that it doesn't return an error page when the Elasticsearch feature isn't available. Preferably, an error message would appear around the search

```
2015-07-21T03:44:17.604570+00:00 heroku[router]: at=info method=GET path="/articles?utf8=%E2%9C%93&state_id=&query=Freddie&commit=Search" host=blackopswiki.herokuapp.com request_id=779de562-b7a3-4434-bbcd-78643f56d693 fwd="173.213.248.208" dyno=web.1 connect=1ms service=284ms status=500 bytes=909
2015-07-21T03:44:17.601602+00:00 app[web.1]:
2015-07-21T03:44:17.601607+00:00 app[web.1]: Searchkick::MissingIndexError (Index missing - run Article.reindex):
2015-07-21T03:44:17.601609+00:00 app[web.1]:   app/controllers/articles_controller.rb:16:in `index'
2015-07-21T03:44:17.601611+00:00 app[web.1]:
2015-07-21T03:44:17.601612+00:00 app[web.1]:
2015-07-21T03:44:18.371081+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=blackopswiki.herokuapp.com request_id=340d21d6-8afc-4d63-9880-60b711995d3d fwd="173.213.248.208" dyno=web.1 connect=2ms service=4ms status=200 bytes=271
```

Elasticsearch error message:

```
Elasticsearch::Transport::Transport::Errors::ServiceUnavailable: [503] {"error":"Cluster is currently read-only for maintenance. Please try again in one minute.","status":503}
    from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'
    from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:224:in `perform_request'
    from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
    from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/client.rb:115:in `perform_request'
    from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
    from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/actions/indices/create.rb:77:in `create'
    from /app/vendor/bundle/ruby/2.2.0/gems/searchkick-0.8.7/lib/searchkick/index.rb:11:in `create'
    from /app/vendor/bundle/ruby/2.2.0/gems/searchkick-0.8.7/lib/searchkick/index.rb:132:in `create_index'
    from /app/vendor/bundle/ruby/2.2.0/gems/searchkick-0.8.7/lib/searchkick/index.rb:153:in `reindex_scope'
    from /app/vendor/bundle/ruby/2.2.0/gems/searchkick-0.8.7/lib/searchkick/model.rb:47:in `reindex'
    from (irb):1
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:8:in `require'
    from bin/rails:8:in `<main>'irb(main):002:0> quit
```

**Comment by campgurus** [comment]
i just added a new case and did not get the elasticsearch error

but i stil get an error in console on reindexing:
!    Request timed out
~/development/blackops$ heroku run rails c -a blackopswiki                                         *[twitter] 
Running `rails c` attached to terminal... up, run.7745
Loading production environment (Rails 4.2.1)
irb(main):001:0> Article.reindex
Elasticsearch::Transport::Transport::Errors::ServiceUnavailable: [503] {"error":"Cluster is currently read-only for maintenance. Please try again in one minute.","status":503}
	from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'
	from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:224:in `perform_request'
	from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
	from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/client.rb:115:in `perform_request'
	from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
	from /app/vendor/bundle/ruby/2.2.0/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/actions/indices/create.rb:77:in `create'
	from /app/vendor/bundle/ruby/2.2.0/gems/searchkick-0.8.7/lib/searchkick/index.rb:11:in `create'
	from /app/vendor/bundle/ruby/2.2.0/gems/searchkick-0.8.7/lib/searchkick/index.rb:132:in `create_index'
	from /app/vendor/bundle/ruby/2.2.0/gems/searchkick-0.8.7/lib/searchkick/index.rb:153:in `reindex_scope'
	from /app/vendor/bundle/ruby/2.2.0/gems/searchkick-0.8.7/lib/searchkick/model.rb:47:in `reindex'
	from (irb):1
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:8:in `require'
	from /app/bin/rails:8:in `<main>'irb(main):002:0>

**Comment by trystant** [comment]
Response from [Heroku](https://help.heroku.com/tickets/252421)

Hello,

Just wanted to let you know that I have the Bonsai Elasticsearch team looking into this for you. Updates to follow.

Thanks,
Heroku Staff

**Comment by trystant** [comment]
so it looks like Elasticsearch as we've implemented it is using too many resources on the system. From Heroku:

````
When Bonsai is added to an app, a cluster is created and associated to that app. If a Heroku user 
has two apps and adds Bonsai to each one, then two clusters are created, and the resources of one 
are not counted against the resources of another. In this case, it was a single cluster with about 
300 shards. The indices all looked like this:

states_test_20150720171343710
states_test_20150720100714920
articles_test_20150720111936959
articles_test_20150720100526077 ... and so on.
It looks like the application was being pretty aggressive with rotating indices. My guess is that it would 
frequently create a new index, update an alias, then keep the old index rather than delete it. When we were paged for a performance regression on one of our public clusters, all of these indices stood out as a
red flag. Removing them improved performance markedly.

The notice about the closed indices went out Mon, Jul 20, 2015 at 5:47 PM UTC; it had a list of all of the closed indices, which was pretty long. It may have ended up in the spam folder as a result.

Situations like this typically aren't intentional but they can cause widespread problems if not addressed
quickly. We're in the process of deploying better limit enforcement on our public clusters to prevent these
kinds of things from happening in the future. Just a heads up in case you start seeing ShardLimit 
exceptions.

Hope that helps. If you have any other questions or concerns, please let me know. Thanks,

Rob
````

So check to see whether you got an email from Heroku.

**Comment by campgurus** [comment]
I think this is referencing the email that I forwarded earlier.

So do we need to periodically remove indices?

**Comment by trystant** [comment]
Nope, different email. This one has to do with those bonsai instances specifically, and yes, we should remove indexes if they're no longer being used. It's worth reviewing when/how we reindex and what impact that makes. We ended up way over quota.

**Comment by trystant** [comment]
I think so since the service is no longer there.
