### ISSUE TITLE
Allow editors to send update to Twitter when case is updated

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#581]
Currently, we update our Twitter feed manually when we have a significant update to a case which is by definition a duplication of effort. I think we could add some automation to the process by allowing editors to post to Twitter directly from the edit form.

Here is a potential process:
1. Editor adds information to a case
2. Editor fills in the summary field
3. Editor checks the box to post the summary to Twitter
4. EBWiki reformats tweet to include appropriate hashtags etc

I recognize the potential for abuse of this feature to EBWiki's detriment, so maybe there needs to be a step 5 -- EBWiki Admin approves tweet.  But that gets us back toward the manual process we were trying to avoid.

**Comment by rlgreen91** [comment]
I'm not sure why we need to approve tweets.  It seems that we would just make the tweet for them to post, and they can either post it or not.

**Comment by campgurus** [comment]
The initial thought was that these tweets would be posted from the EBWiki account.  If that is the case, we open ourselves to having vandals manipulate the change summary field to produce a counterproductive tweet that we EBWiki sends to all of our followers. So that is where the thought of approving tweets emanated from.

I guess the answer is to either let the user cut and paste, or access their account via EBWiki to post from the user's Twitter account.  I think this may require implementing Twitter logins on EBWiki.

**Comment by rlgreen91** [comment]
I think it would be best to make the tweet for them to post.  You're right, in that we would need to allow people to connect their Twitter (and other social media) accounts to the site.

For stuff coming directly from the official account, I think it might be better to keep it more general, y posting that a case was updated, with a link to the case, or that X number of cases were updated.  Things like that, rather than relying on a summary field.

**Comment by trystant** [comment]
I don't think we want mass posting from an EBWiki account. I think a feature that allowed them to promote the case but from their own account would have more merit and would help spread the word of the site & what it's doing.  One does not need to use Twitter login to implement that; a [tweet button](https://dev.twitter.com/web/tweet-button) will do.

**Comment by rlgreen91** [comment]
Ah, that's what I was thinking off - you're right in that we don't need to do authorization, instead they do.  But I like the idea.  I would like to expand this to also include options for Facebook and Instagram.

**Comment by campgurus** [comment]
I am fully on board with users posting from their own accounts.  Much better idea, including that it broadens our reach beyond our own followers. We currently use share buttons on the case/show view, right below the case photo.  I imagine we could do something similar wrt the case update messages.

**Comment by mnyon-grandkru** [comment]
We've got Twitter, LinkedIn & Tumblr. I think we can close this ticket.
