### ISSUE TITLE
Install New Relic to monitor performance

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#593]
here is the link to instructions. Will help us see server performance and identify resource hogs.

**Comment by rlgreen91** [comment]
@campgurus @trystant Didn't we end up doing this?

**Comment by mnyon-grandkru** [comment]
We did install it, and here's the proof 
![image](https://user-images.githubusercontent.com/5750239/234741800-4795d279-1f0c-4f4d-b9e3-4e783bb73024.png)
