### ISSUE TITLE
Enable Sendgrid to track email opens and clicks

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#594]
Right now, our Heroku add-on for Sendgrid is not set up to track email clicks or opens. It would also be nice to have these stats for internal use or even for the public analytics dashboard from #145. There are a couple gems that look like they will be helpful. in this regard.

**Comment by campgurus** [comment]
Good news, bad news.  The good news is that clacks are being tracked by SendGrid.  The bad news? No one's clicking. We will see if that changes with the recent change to the update email (#590) helps that at all. We should also discount emails sent to us and the editor sending the update.

**Comment by trystant** [comment]
this can be closed
