### ISSUE TITLE
Need to re-confirm and add more rspec to verify that a summary is required 

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#606]
This case update seems to have been effected with no summary comment somehow. See image below:
<img width="833" alt="screen shot 2016-06-10 at 11 18 58 am" src="https://cloud.githubusercontent.com/assets/1260659/15969280/5d2b9564-2efd-11e6-9e02-f5709f4ae3e2.png">

Within the app interface, the last entry on the history page is from 3 months ago and no new version has been recorded that would correspond to this update.

While this is a mystery right now, I don't think this is urgent unless editors begin to use it as a loophole to avoid summaries when updating but I am still not sure this is what happened in this case.  we should figure it out.

**Comment by trystant** [comment]
I have not been able to replicate this issue.
