### ISSUE TITLE
for #145 list articles in order of # of follows

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#608]
Here is one solution: http://stackoverflow.com/questions/8696005/rails-3-activerecord-order-by-count-on-association but I am not sure it gets us all the way there, since ours is a polymorphic association.

Here is an example of sorting on a polymorphic association count: http://stackoverflow.com/questions/18166997/sort-posts-by-their-comment-counts-then-created-at-date-in-rails.

Not sure if that is the best way or if there is some other way to do it.

**Comment by campgurus** [comment]
this is on production.

**Comment by trystant** [comment]
In the [index.html.erb](https://github.com/BOWiki/BOW/blob/master/app/views/analytics/index.html.erb) for Analytics, there are at least three lines with multiple compound scopes in the view:

104: ` <% Article.order(updated_at: :desc).first(10).each_with_index do |article, i| %>`
133: `<% Article.order(follows_count: :desc).first(10).each_with_index do |article, i| %>`
160: `<% Visit.where(started_at: 7.days.ago..Time.now).group(:landing_page).order('count_id DESC').limit(13).count(:id).each_with_index do |visit, i| %>`

Each of these should be  a custom scope that is associated with the model. The following lines should read as follows:

104: ` <% Article.recently_updated do |article, i| %>`
133: `<% Article.most_followed do |article, i| %>`
160: `<% Visit.most_in_last_week do |visit, i| %>`

and the logic in that index should be in those scopes.

**Comment by campgurus** [comment]
Does "scope" mean creating new model methods for Article and Visit? eg in article.rb:

``` def recently_updated
  Article.order(updated_at: :desc).first(10)
end```

**Comment by campgurus** [comment]
Can we close this issue after @trystant's recent work?

**Comment by trystant** [comment]
I think that this can be closed
![screenshot 2018-05-20 at 10 54 16](https://user-images.githubusercontent.com/13509/40280074-3184461a-5c1c-11e8-9c35-1d0492ebef8d.png)
