### ISSUE TITLE
Upgrade to Rails 5.x

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#686]
We should start the prep work to upgrade to Rails 5.x, while leaving time & space for the 5.0.0 folk to do beta testing ;)

**Comment by trystant** [comment]
While checking out the [Rails Upgrade from 4.2 to 5.0](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0), I identified a few steps that will apply to us:

2.5 Rails Controller Testing
assigns and assert_template have been extracted to the rails-controller-testing gem. To continue using these methods in your controller tests, add gem 'rails-controller-testing' to your Gemfile.

If you are using Rspec for testing, please see the extra configuration required in the gem's documentation.

This is a good checklist, however.

**Comment by trystant** [comment]
There are increased security measures in 5.0 that make it worth an upgrade.

**Comment by trystant** [comment]
I'm doing an upgrade to 4.2.9, the latest 4.2 edition as a step towards Rails 5.

**Comment by rlgreen91** [comment]
I believe this should be our first priority of the new year, assuming that we finish all other current priorities.  @trystant I think 5.2 will be released by then, perhaps that can be our target?  Using Activestorage in lieu of gems is appealing.

**Comment by rlgreen91** [comment]
Note: this issue involves migrating from Rails 4.2.9 to the latest stable version of Rails.
