### ISSUE TITLE
Add generalized authorization via Pundit or Cancancan

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#691]
Currenty we use boolean attributes to help us check for authorization eg to see the admin dashboard. As we add roles and separate permissions by type of user, e.g. who gets access to the analytics panel?  Who can delete articles? It will be helpful to implement a more generalized solution of the type provided by Cancancan, Authorize and Pundit.

In choosing among these alternatives, Pundit seems IMO to have the advantage of simplicity, so I would lean toward that solution, but it is a fair topic for discussion if someone else has a different view.

Here is an article that relates to Pundit which may be helpful when we get to implementation: http://cookieshq.co.uk/posts/pundit/

**Comment by rlgreen91** [comment]
Pundit has been added to the app.
