### ISSUE TITLE
Recently Updated view formatting issues

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#711]
There are two challenges with the Recently Updated view. These include:
- [ ] The person's name often isn't completely seen
- [ ] The person's name is on two lines, or
- [ ] The date associated is on two lines

<img width="277" alt="screenshot 2016-07-12 07 42 09" src="https://cloud.githubusercontent.com/assets/13509/16765970/1695d0e4-4805-11e6-9ef3-36ec45ee4487.png">

This could be formatted better.

**Comment by campgurus** [comment]
This would be good to fix.

**Comment by trystant** [comment]
This is a work in progress. I need to make adjustments
<img width="303" alt="screenshot 2016-07-18 23 42 34" src="https://cloud.githubusercontent.com/assets/13509/16937954/58d909ee-4d41-11e6-9307-02fea07dc487.png">

**Comment by rlgreen91** [comment]
This appears to have been addressed in a PR.
