### ISSUE TITLE
Minor layout issue -- excess space at the top of the page

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#733]
I think this has to do with margin we added at the top of the page to accommodate the navigation header, but at this point it looks excessive to me.

<img width="1211" alt="screen shot 2016-07-21 at 12 31 36 pm" src="https://cloud.githubusercontent.com/assets/1260659/17030818/4f6561b4-4f3f-11e6-80f1-833eb1c7483b.png">

**Comment by trystant** [comment]
You mean the light gray space on top of the dark gray square?

**Comment by campgurus** [comment]
I think that looks odd as well, but I was speaking about the ~50 pixels below the logo/search box and the image/subject name.

**Comment by trystant** [comment]
We've halved the distance between the logo & case image.
![screenshot 2018-05-20 at 04 10 43](https://user-images.githubusercontent.com/13509/40276925-cbc6a4ae-5be3-11e8-8f33-f991981bf8db.png)
