### ISSUE TITLE
Managing cases with no victim name

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#775]
Right now, we don't have a convenient way to capture killings where the deceased is not named. having a generic "unknown" subject will result in strange urls etc.

As a result, we are constrained by law enforcement's decision to release or not release that information about the deceased.

**Comment by trystant** [comment]
To which cases does this apply right now?

**Comment by campgurus** [comment]
eg the case in Milwaukee, until today, the name of the victim was unavailable for several days, so we are stuck waiting for police to decide when we can report the case.

**Comment by trystant** [comment]
Considering the Massacres that are on the site, I think there's a facility for this now.
