### ISSUE TITLE
User can create two accounts with the same email

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#80]
As you can tell from the screenshot, a user can have two accounts with the same [email address](http://grandkru.com/images/multiple_accounts_same_email.png). We need to have a unique email address for each user.

**Comment by StlMaris123** [comment]
Is this issue still valid?

**Comment by rlgreen91** [comment]
@StlMaris123 I'm not sure, I'll need to look into it.  Please take a look at the pinned posts in the Slack channel - those posts lead to issues that we can guarantee need to be addressed and are clearly written.

**Comment by StlMaris123** [comment]
Tested this, `uniqueness` has been validated. You cannot create an account with an existing email address

**Comment by rlgreen91** [comment]
@StlMaris123 how exactly did you check?  Was it just by trying to make two accounts on a server running locally, or the actual website?

Can you just add a couple of tests verifying that if we try to create two accounts with the same email address, it will fail?  A unit test for the `user` model and a request spec should be fine.

**Comment by rlgreen91** [comment]
@StlMaris123 bumping this so you don't miss it

**Comment by rlgreen91** [comment]
@StlMaris123 What's the status on this issue?  You just need to add a spec verifying that creating two accounts with the same email fails, and a comment within the user registration controller that this is handled by Devise.

**Comment by rlgreen91** [comment]
@StlMaris123 What's the status on this issue?
