### ISSUE TITLE
Convert articles to case

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#825]
These incidents are actually cases, so the article needs to be changed to case

**Comment by trystant** [comment]
I've gotten close to the end of this ticket, but there are some additional pieces of the puzzle that need to be completed:

- [ ] The S3 URLs of the images need to be changed to include the word "cases" instead of "articles".
<img width="1400" alt="screenshot 2016-11-24 21 31 28" src="https://cloud.githubusercontent.com/assets/13509/20613002/820ce98c-b28d-11e6-99c8-dc693bf0a9b2.png">

I'm looking into a way to do that now.

**Comment by trystant** [comment]
For the record, copying all the URLs from "articles" to "cases" for the S3 assets has taken several hours using Cyberduck as an S3 client:

<img width="585" alt="screenshot 2016-11-25 04 24 33" src="https://cloud.githubusercontent.com/assets/13509/20620305/15fd22ae-b2c7-11e6-9740-14d677c4c9cc.png">

Luckily I don't need to be up & present, but this is one of those situations where waiting to do it later adds to the time involved in solving it.

**Comment by rlgreen91** [comment]
Have you finished, or is it still running?

**Comment by trystant** [comment]
That job is finished, but I need to deploy my changes to staging and do a full test.

**Comment by rlgreen91** [comment]
@trystant Can you explain what exactly you have done what still needs to be done?  My understanding is that this is what needs to be and has been done:

- [ ] Update copy on site to use "case"
- [ ] Rename article table to case
- [ ] Rename model, spec, and all associated methods
- [ ] Rename controller, routes, and all associated methods
- [ ] Rename views, stylesheets, helpers, and all associated methods
- [ ] Update S3 URLs
