### ISSUE TITLE
Add tooltip to Case Names in Analytics page

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#839]
Since some of the case names are not complete due to size, it would be helpful to have a tooltip with the case name on the page. This applies to this 
<img width="1249" alt="screenshot 2016-10-13 11 23 36" src="https://cloud.githubusercontent.com/assets/13509/19355214/979185be-9137-11e6-9d0c-63d14b2714ac.png">

**Comment by rlgreen91** [comment]
TIL I learned what a tooltip is.  I just always thought it was alt text.

**Comment by rlgreen91** [comment]
Given that we are looking to redesign this section of the landing page, there is a good chance that such a tooltip will not be needed.  As such, I will be closing this issue.

**Comment by rlgreen91** [comment]
Given that we no longer have an analytics page, let's close this.
