### ISSUE TITLE
Fix Google API Maps warnings upon arrival at homepage

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#851]
When one arrives at the homepage, the javascript console spits out the following Google Maps API warnings:

```
util.js:210 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keysuE.j @ util.js:210
util.js:210 Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-versionuE.j @ util.js:210
util.js:210 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-requireduE.j @ util.js:210
```

**Comment by rlgreen91** [comment]
No API keys?  Did they expire? Is that even possible?  Where else do we rely on others' APIs?

**Comment by trystant** [comment]
I don't know what has happened with the versions, but I'm guessing that there's an incompatibility with the Google Maps API and the gmaps4rails gem. Here's a screenshot of the explanation of the error messages:

<img width="860" alt="screenshot 2016-11-27 10 48 35" src="https://cloud.githubusercontent.com/assets/13509/20649481/2f25980a-b48f-11e6-94bc-fa804abe1f27.png">

**Comment by rlgreen91** [comment]
Are we using the latest version of this gem now?  I wonder if a new version of that gem resolves this problem.

**Comment by campgurus** [comment]
https://stackoverflow.com/questions/35890582/google-maps-api-warning-noapikeys

**Comment by trystant** [comment]
So this looks like the [gmaps4rails plugin][https://apneadiving.github.io/] is having this issue across the board. Time for a new gem.

**Comment by trystant** [comment]
I started working on the re-implementation of Google Maps. I need to change the `script src` references in order to get a simple map going. Once that's achieved, I'll organize the code to best practice w/ asset pipeline, then resurrect retrieving markers from the database..

**Comment by trystant** [comment]
I'm going to close this ticket since the unit of work has moved and is a separate piece of work
