### ISSUE TITLE
"Filter by State" label disappears from drop-down

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#887]
In each page, the search interface includes a drop-down menu with the "filter by state" label, but this label doesn't show up at all anymore.

**Comment by IsaacBell** [comment]
Will need to add JS to fix this further

**Comment by trystant** [comment]
This label seems to be restored
![screenshot 2018-05-20 at 06 13 01](https://user-images.githubusercontent.com/13509/40277879-dd9e0b2a-5bf4-11e8-9078-0de0b18dc9db.png)
