### ISSUE TITLE
Destroying an article with associated links from the admin panel causes error

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#9]
destroying the links first allows you to destroy the article without incident.

**Comment by trystant** [comment]
The particular error is available in this [Rollbar](https://rollbar.com/instance/uuid?uuid=927797ba-ef01-4de7-a11b-06a9a1854db2) link.

**Comment by trystant** [comment]
Just confirming that this is still happening.

**Comment by trystant** [comment]
I just confirmed tbat this is no longer an issue.
