### ISSUE TITLE
Weird dots underneath stars on required fields in forms

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#906]
So, on forms such as those for new cases and agencies, there are asterisks to indicate which fields are required.  But for some reason, there are dots underneath the asterisks.  If possible, remove the dots.

![image](https://cloud.githubusercontent.com/assets/1738068/26277728/5dbb4e74-3d53-11e7-9dc7-d16d3eef37cc.png)

**Comment by rachaelkiteme** [comment]
Hello, I would love to work on this issue

**Comment by rlgreen91** [comment]
Hi @rachaelkiteme I will add this to the list of features available for people to work on. I'll send you an email with more info.

**Comment by rachaelkiteme** [comment]
Will really appreciate this. Thank you so much for getting back to me, am
greatful.

Regards
Rachael

**Comment by rlgreen91** [comment]
Merged as #1354
