### ISSUE TITLE
Escape the html in the Maps flyover descriptions

### ISSUE THREAD

**Issue by IsaacBell** [EBWiki/EBWiki#909]
Example: https://ebwiki.org/articles/emanuel-jean-baptiste

![screenshot 2017-05-20 at 10 50 46 pm](https://cloud.githubusercontent.com/assets/2613157/26281035/f5b59ed6-3dae-11e7-8d98-441409e4420d.png)

**Comment by rlgreen91** [comment]
This has been addressed in #1593, #1623, #1627 and #1629
