### ISSUE TITLE
Redo search interface

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#946]
This is talked about somewhere else, I believe, but let's alter the search interface.

Reorganize the search box at the top have the input for Name, City, Keywords on the left and the search button on the right.  The text box and the search button should be of uniform width and height.

Please submit a screenshot of the new interface as part of your PR.

**Comment by campgurus** [comment]
related to issue #555

**Comment by rlgreen91** [comment]
Given that this is basically an extension of #555, I've copied the content over to there, and will now close this issue.

**Comment by rlgreen91** [comment]
Reopening this issue, and splitting the deliverables into two issues.

**Comment by rlgreen91** [comment]
Technically this was completed as part of #2980.  I'd consider the cases filtering issue to be a separate issue.
