### ISSUE TITLE
Resize text on pictures for home page in mobile

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#951]
On mobile browsers, the pictures on the home page are appropriately resized.  The text on them, however is not.

**Comment by trystant** [comment]
Hey @rlgreen91, of which mobile devices are we speaking?

**Comment by rlgreen91** [comment]
This was on my Samsung Galaxy S6.

**Comment by rlgreen91** [comment]
I'm not exactly sure when, but this has been addressed, so closing.
