### ISSUE TITLE
Change approach to creating new articles

### ISSUE THREAD

**Issue by rlgreen91** [EBWiki/EBWiki#956]
Currently in `app/controllers/articles_controller.rb`, we use this method to create a new article:

```
def create
    @article = current_user.articles.build(article_params)
    # This could be a very expensive query as the userbase gets larger.
    # TODO: Create a scope to send only to users who have chosen to receive email updates
    if @article.save
      flash[:success] = "Article was created! #{make_undo_link}"
      redirect_to @article
    else
      render 'new'
    end
  end
```

As noted, this query will get to be very expensive, if it's not already.  It would be better to pull the relevant user data and then call `article.build` with all of the parameters.

**Comment by campgurus** [comment]
is `current_user` expensive?

**Comment by rlgreen91** [comment]
It's not so much that `current_user` is expensive, it's more that I wonder how expensive `current_user.articles` could get.  However, I could just be worrying over nothing, especially since this is the standard way of doing this.  

This might get refactored in general, though, because I know we've talked about altering the form for articles. But I think we can go ahead and close this.
