### ISSUE TITLE
Need 'Back to Case' Button on History and Edit Pages

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#97]
Simple nav button or links would be helpful

**Comment by rlgreen91** [comment]
What specifically would you like? A back to article button on the history page, and a cancel button on the edit page?  There's a small "back" link on the edit page at the bottom.

**Comment by campgurus** [comment]
Yeah, this ight fall into the category of good first tie project for contributors. I meant exactly what you said. just making navigation more user friendly with more buttons instead of text links.

**Comment by rlgreen91** [comment]
To be more clear, this issue now involves adding a "back to article" button on the history page, and replacing the "back" link on the edit page with a cancel button.
