### ISSUE TITLE
EBWiki needs a separate database for analysis

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#988]
We currently just have the application database, but need to augment that with a separate database for analysis. This includes site visit information as well as the case data itself

**Comment by rlgreen91** [comment]
@trystant is this really still a need?  Tbh, our tables are still pretty small.  I don't think any of them have hit more than 100,000 rows yet.  When we do hit that, we can just look into the multi-database support Rails 6 has.  I say let's close this for now.

**Comment by trystant** [comment]
Yeah. This is a case of too soon .
