### ISSUE TITLE
Automatically complete login-required actions after sign-up is completed by new users

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#99]
Certain actions on EBW require a logged in user. So e.g., if a new visitor clicks the button to follow  @case, they are redirected to the login/sign-up screen. Once they complete the login/sign-up, they are redirected to the root page -- back to square one.

Alternatively, not sure how to do this yet, but it would be nice to automatically complete the action they were trying to take.  So in this case, their new user would be following @case without further action from the new user.

**Comment by trystant** [comment]
There is information on how to do this in the [Devise wiki](https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update):

**Comment by rlgreen91** [comment]
@trystant has this been addressed?

**Comment by rlgreen91** [comment]
@trystant asking again - was this ever implemented?

**Comment by trystant** [comment]
I don't believe so.

**Comment by rlgreen91** [comment]
Great.  Since we are using an older version of Devise, I'm going to make a set of issues that updates that incrementally and then adds the functionality.
