### ISSUE TITLE
The app needs an inventory on the gems in the Gemfile

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#991]
Basically, the [Gemfile](https://github.com/BOWiki/BOW/blob/master/Gemfile) needs an audit to determine whether the gems included are needed. Along the way, duplicates will be removed.

**Comment by trystant** [comment]
This is a descendant of #821, btw.

**Comment by trystant** [comment]
Used this [Markdown Table Generator](http://www.tablesgenerator.com/markdown_tables#) to make this:

|  Gem |  Used? |
|---|---|
|  'dotenv-rails', |   Yes |
| 'rails'  | Yes  |
| 'uglifier'  |  Yes |
|  'enumerated_type' | Yes  |
|   |   |
|   |   |
|   |   |
|   |   |
|   |   |
|   |   |
|   |   |
|   |   |
|   |   |
|   |   |

**Comment by rlgreen91** [comment]
This inventory was completed as part of the upgrade Ruby process.  All gems have been upgraded, removed, or will be removed after changes to related code.
