### ISSUE TITLE
Header with user logged in takes up too much vertical space

### ISSUE THREAD

**Issue by trystant** [EBWiki/EBWiki#997]
When logged in, the header for the site looks like this:

![screenshot 2017-08-26 at 8 59 41 am](https://user-images.githubusercontent.com/13509/29741534-0e37e34e-8a3d-11e7-8445-cfae35947ca4.png)

It should be all on the same line.

**Comment by AlessandroMinali** [comment]
I'll take a look at this

**Comment by trystant** [comment]
![screenshot 2018-05-13 at 13 02 09](https://user-images.githubusercontent.com/13509/39969708-fc8501e8-56ad-11e8-820e-1c19eabf1f88.png)
Looks a bit better.
